import { describe, expect, test } from "vitest";
import { renderApiPushAdapters } from "../api-push-adapter-writer";
import { reflectSyncTables } from "../drizzle-reflection";
import { syncManifest } from "../manifest";

const localSchema = await import("@repo/database");
const tables = reflectSyncTables(localSchema, syncManifest);

describe("API push adapter writer", () => {
  test("renders generated file header and adapter exports", () => {
    const source = renderApiPushAdapters(syncManifest, tables);

    expect(
      source.startsWith(
        "// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by @repo/sync-proto-generator.\n"
      )
    ).toBe(true);
    expect(source).toContain("export const PUSH_TABLE_ADAPTERS = [");
    expect(source).toContain(
      "export function getPushTableAdapter(tableName: string)"
    );
  });

  test("renders product minor-unit row mapping and static upsert set", () => {
    const source = renderApiPushAdapters(syncManifest, tables);

    expect(source).toContain(
      'priceMinorUnits: requiredInt64NumberField(row.priceMinorUnits, "products.priceMinorUnits")'
    );
    expect(source).toContain(
      'priceMinorUnits: sql.raw("excluded.price_minor_units")'
    );
    expect(source).toContain("softDeleteRowsByAdapter");
  });

  test("renders upsert excluded references with SQLite column names", () => {
    const source = renderApiPushAdapters(syncManifest, tables);

    expect(source).toContain(
      'priceMinorUnits: sql.raw("excluded.price_minor_units")'
    );
    expect(source).toContain('updatedAt: sql.raw("excluded.updated_at")');
    expect(source).not.toContain("excluded.priceMinorUnits");
    expect(source).not.toContain("excluded.updatedAt");
  });

  test("keeps staff outletId as row data while server-owning merchantId", () => {
    const source = renderApiPushAdapters(syncManifest, tables);

    expect(source).toContain("function staffRowToInsertRow");
    expect(source).toContain("outletId: nullableStringField(row.outletId)");
    expect(source).toContain(
      'return applyContextOwnership(normalized, context, "merchantId")'
    );
  });

  test("renders required and nullable int64 conversions", () => {
    const source = renderApiPushAdapters(syncManifest, tables);

    expect(source).toContain(
      'priceMinorUnits: requiredInt64NumberField(row.priceMinorUnits, "products.priceMinorUnits")'
    );
    expect(source).toContain(
      'sortOrder: requiredInt64NumberField(row.sortOrder, "products.sortOrder")'
    );
    expect(source).toContain(
      'width: nullableInt64NumberField(row.width, "assets.width")'
    );
    expect(source).toContain(
      'amountPaidMinorUnits: nullableInt64NumberField(row.amountPaidMinorUnits, "orders.amountPaidMinorUnits")'
    );
    expect(source).toContain(
      'originalPriceMinorUnits: nullableInt64NumberField(row.originalPriceMinorUnits, "order_items.originalPriceMinorUnits")'
    );
  });

  test("exports adapters in manifest push order", () => {
    const source = renderApiPushAdapters(syncManifest, tables);
    const adapterList = source.slice(
      source.indexOf("export const PUSH_TABLE_ADAPTERS = ["),
      source.indexOf("] as const;")
    );

    expect(adapterList.indexOf("StaffPushTableAdapter()")).toBeLessThan(
      adapterList.indexOf("CategoriesPushTableAdapter()")
    );
    expect(adapterList.indexOf("OrdersPushTableAdapter()")).toBeLessThan(
      adapterList.indexOf("OrderItemsPushTableAdapter()")
    );
  });
});
