import { describe, expect, test } from "vitest";
import {
  syncGeneratorConfig,
  syncProtoSchemas,
} from "../../../protobuf/sync-proto.config";
import { renderApiPushAdapters } from "../api-push-adapter-writer";
import { reflectSyncTables } from "../drizzle-reflection";

const tables = reflectSyncTables({
  config: syncGeneratorConfig,
  schemaModule: syncProtoSchemas.localSyncedSchema,
});
const SCOPE_PATTERN = /\bscope\b/i;
const TENANT_PATTERN = /\btenant\b/i;

describe("API push adapter writer", () => {
  test("renders generated file header and generic adapter exports", () => {
    const source = renderApiPushAdapters(
      tables,
      syncProtoSchemas.apiSyncedSchema
    );

    expect(
      source.startsWith(
        "// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by @repo/sync-proto-generator.\n"
      )
    ).toBe(true);
    expect(source).toContain("export interface GenericSyncTableAdapter");
    expect(source).toContain("export const PUSH_TABLE_ADAPTERS = [");
    expect(source).toContain("export const SYNC_UPSERT_ORDER = [");
    expect(source).toContain("export const SYNC_DELETE_ORDER = [");
    expect(source).toContain(
      "export function getPushTableAdapter(tableName: string)"
    );
  });

  test("renders generic proto row mapping and excluded primary key upsert sets", () => {
    const source = renderApiPushAdapters(
      tables,
      syncProtoSchemas.apiSyncedSchema
    );

    expect(source).toContain(
      'priceMinorUnits: requiredInt64NumberField(row.priceMinorUnits, "products.priceMinorUnits")'
    );
    expect(source).toContain(
      'priceMinorUnits: sql.raw("excluded.price_minor_units")'
    );
    expect(source).not.toContain('sql.raw("excluded.id")');
    expect(source).toContain("deleteRowsByAdapter");
  });

  test("renders chunked upserts and hard deletes", () => {
    const source = renderApiPushAdapters(
      tables,
      syncProtoSchemas.apiSyncedSchema
    );

    expect(source).toContain("const chunkSize = getWriteChunkSize(");
    expect(source).toContain("chunkRows(rows, chunkSize)");
    expect(source).toContain(
      "tx.delete(table).where(inArray(idColumn, chunk))"
    );
  });

  test("does not include tenant or scope policy in the generated adapter", () => {
    const source = renderApiPushAdapters(
      tables,
      syncProtoSchemas.apiSyncedSchema
    );

    expect(source).not.toMatch(SCOPE_PATTERN);
    expect(source).not.toMatch(TENANT_PATTERN);
    expect(source).not.toContain("applyContextOwnership");
  });

  test("exports upsert and delete order with FK-safe relationships", () => {
    const source = renderApiPushAdapters(
      tables,
      syncProtoSchemas.apiSyncedSchema
    );
    const upsertOrder = source.slice(
      source.indexOf("export const SYNC_UPSERT_ORDER = ["),
      source.indexOf("export const SYNC_DELETE_ORDER = [")
    );
    const deleteOrder = source.slice(
      source.indexOf("export const SYNC_DELETE_ORDER = ["),
      source.indexOf("export const PUSH_TABLE_ADAPTERS = [")
    );

    expect(upsertOrder.indexOf('"products"')).toBeLessThan(
      upsertOrder.indexOf('"outlet_products"')
    );
    expect(upsertOrder.indexOf('"orders"')).toBeLessThan(
      upsertOrder.indexOf('"order_items"')
    );
    expect(deleteOrder.indexOf('"order_items"')).toBeLessThan(
      deleteOrder.indexOf('"orders"')
    );
  });
});
