import { describe, expect, test } from "vitest";
import {
  syncGeneratorConfig,
  syncProtoSchemas,
} from "../../../protobuf/sync-proto.config";
import { reflectSyncTables } from "../drizzle-reflection";
import { renderSyncProto } from "../proto-writer";

describe("proto writer", () => {
  test("renders generated file warning header", () => {
    const tables = reflectSyncTables({
      config: syncGeneratorConfig,
      schemaModule: syncProtoSchemas.localSyncedSchema,
    });
    const proto = renderSyncProto(syncGeneratorConfig, tables);

    expect(
      proto.startsWith(
        "// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by @repo/sync-proto-generator.\n"
      )
    ).toBe(true);
  });

  test("renders product row with current manual field names", () => {
    const tables = reflectSyncTables({
      config: syncGeneratorConfig,
      schemaModule: syncProtoSchemas.localSyncedSchema,
    });
    const proto = renderSyncProto(syncGeneratorConfig, tables);

    expect(proto).toContain("message products_row");
    expect(proto).toContain("string merchantId = 2;");
    expect(proto).toContain("int64 priceMinorUnits = 5;");
    expect(proto).toContain("string imageAssetId = 7;");
  });

  test("renders change wrappers for every sync table", () => {
    const tables = reflectSyncTables({
      config: syncGeneratorConfig,
      schemaModule: syncProtoSchemas.localSyncedSchema,
    });
    const proto = renderSyncProto(syncGeneratorConfig, tables);

    expect(proto).toContain("message staff_changes");
    expect(proto).toContain("repeated staff_row changedRows = 1;");
    expect(proto).toContain("repeated string deletedIds = 2;");
  });

  test("does not render legacy json or changed_rows aliases", () => {
    const tables = reflectSyncTables({
      config: syncGeneratorConfig,
      schemaModule: syncProtoSchemas.localSyncedSchema,
    });
    const proto = renderSyncProto(syncGeneratorConfig, tables);

    expect(proto).not.toContain("SyncJsonTableChanges");
    expect(proto).not.toContain("created_json");
    expect(proto).not.toContain("updated_json");
    expect(proto).not.toContain(" created = ");
    expect(proto).not.toContain(" updated = ");
  });

  test("renders opaque pull and status cursors instead of event ids", () => {
    const tables = reflectSyncTables({
      config: syncGeneratorConfig,
      schemaModule: syncProtoSchemas.localSyncedSchema,
    });
    const proto = renderSyncProto(syncGeneratorConfig, tables);

    expect(proto).toContain("message SyncStatusRequest {");
    expect(proto).toContain("string cursor = 2;");
    expect(proto).toContain("message SyncStatusResponse {");
    expect(proto).toContain("string cursor = 3;");
    expect(proto).toContain("message SyncPullBatchRequest {");
    expect(proto).toContain("string cursor = 4;");
    expect(proto).toContain("message SyncPullBatchResponse {");
    expect(proto).toContain("string cursor = 100;");
    expect(proto).toContain("bool hasMore = 101;");
    expect(proto).toContain("string serverTime = 102;");
    expect(proto).not.toContain("lastServerEventId");
    expect(proto).not.toContain("latestEventId");
    expect(proto).not.toContain("needsFullResync");
    expect(proto).not.toContain("afterEventId");
    expect(proto).not.toContain("pageCursor");
    expect(proto).not.toContain("nextPageCursor");
  });
});
