import { describe, expect, test } from "vitest";
import {
  syncGeneratorConfig,
  syncProtoSchemas,
} from "../../../protobuf/sync-proto.config";
import { reflectSyncTables } from "../drizzle-reflection";
import { renderApiSyncMappers } from "../ts-mapper-writer";

describe("TypeScript API sync mapper writer", () => {
  test("renders generated file warning header", () => {
    const source = renderApiSyncMappers(
      reflectSyncTables({
        config: syncGeneratorConfig,
        schemaModule: syncProtoSchemas.localSyncedSchema,
      })
    );

    expect(
      source.startsWith(
        "// AUTO-GENERATED FILE. DO NOT EDIT.\n// Generated by @repo/sync-proto-generator.\n"
      )
    ).toBe(true);
  });

  test("renders product money field from explicit minor-unit property", () => {
    const source = renderApiSyncMappers(
      reflectSyncTables({
        config: syncGeneratorConfig,
        schemaModule: syncProtoSchemas.localSyncedSchema,
      })
    );

    expect(source).toContain(
      'priceMinorUnits: int64Field(row.priceMinorUnits, "products.priceMinorUnits")'
    );
    expect(source).not.toContain("row.price ?? row.priceMinorUnits");
  });

  test("renders typed decode for all sync tables", () => {
    const source = renderApiSyncMappers(
      reflectSyncTables({
        config: syncGeneratorConfig,
        schemaModule: syncProtoSchemas.localSyncedSchema,
      })
    );

    expect(source).toContain("if (request.staff)");
    expect(source).toContain("changes.staff = {");
    expect(source).toContain("changedRows: request.staff.changedRows");
    expect(source).not.toContain("JSON.parse");
    expect(source).not.toContain("created:");
    expect(source).not.toContain("updated:");
  });

  test("renders typed encode for all sync tables", () => {
    const source = renderApiSyncMappers(
      reflectSyncTables({
        config: syncGeneratorConfig,
        schemaModule: syncProtoSchemas.localSyncedSchema,
      })
    );

    expect(source).toContain(
      "staff: mapTableChanges(result.staff, staff_row_to_proto)"
    );
  });

  test("encodes pull responses from service keys, not ts-proto keys", () => {
    const source = renderApiSyncMappers(
      reflectSyncTables({
        config: syncGeneratorConfig,
        schemaModule: syncProtoSchemas.localSyncedSchema,
      })
    );

    expect(source).toContain(
      "order_items: mapTableChanges(result.order_items, order_items_row_to_proto)"
    );
    expect(source).toContain(
      "outlet_products: mapTableChanges(result.outlet_products, outlet_products_row_to_proto)"
    );
    expect(source).not.toContain("result.orderItems");
    expect(source).not.toContain("result.outletProducts");
    expect(source).not.toContain("createdRows");
    expect(source).not.toContain("updatedRows");
  });

  test("decodes push requests using ts-proto field names into service keys", () => {
    const source = renderApiSyncMappers(
      reflectSyncTables({
        config: syncGeneratorConfig,
        schemaModule: syncProtoSchemas.localSyncedSchema,
      })
    );

    expect(source).toContain("if (request.order_items) {");
    expect(source).toContain("changes.order_items = {");
    expect(source).toContain("if (request.outlet_products) {");
    expect(source).toContain("changes.outlet_products = {");
    expect(source).toContain("changedRows: request.order_items.changedRows");
    expect(source).not.toContain("request.order_items.created");
    expect(source).not.toContain("request.order_items.updated");
  });

  test("renders row to proto functions for every sync table", () => {
    const source = renderApiSyncMappers(
      reflectSyncTables({
        config: syncGeneratorConfig,
        schemaModule: syncProtoSchemas.localSyncedSchema,
      })
    );

    for (const table of reflectSyncTables({
      config: syncGeneratorConfig,
      schemaModule: syncProtoSchemas.localSyncedSchema,
    })) {
      expect(source).toContain(
        `function ${table.rowMessageName}_to_proto(row: Record<string, unknown>)`
      );
    }
  });
});
