#!/usr/bin/env bash

echo "Select preset:"
echo "  1) Phone Portrait           1080x2400  400dpi"
echo "  2) Phone Landscape          2400x1080  400dpi"
echo "  3) 10.5\" Tablet Portrait   1200x1920  240dpi"
echo "  4) 10.5\" Tablet Landscape  1920x1200  240dpi"
echo ""
read -rp "> " choice

case "$choice" in
    1)
        echo "Setting Phone Portrait (1080x2400, 400dpi)"
        doas waydroid shell wm size 1080x2400
        doas waydroid shell wm density 400
        ;;
    2)
        echo "Setting Phone Landscape (2400x1080, 400dpi)"
        doas waydroid shell wm size 2400x1080
        doas waydroid shell wm density 400
        ;;
    3)
        echo "Setting 10.5\" Tablet Portrait (1200x1920, 240dpi)"
        doas waydroid shell wm size 1200x1920
        doas waydroid shell wm density 240
        ;;
    4)
        echo "Setting 10.5\" Tablet Landscape (1920x1200, 240dpi)"
        doas waydroid shell wm size 1920x1200
        doas waydroid shell wm density 240
        ;;
    *)
        echo "Invalid choice"
        exit 1
        ;;
esac
