// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: proto/sync.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sakti.sync.v1";

export interface SyncPushRequest {
  outletId: string;
  payloadJson: string;
}

export interface SyncServerWin {
  table: string;
  ids: string[];
}

export interface SyncPushResponse {
  serverWins: SyncServerWin[];
  serverTime: string;
}

export interface SyncStatusRequest {
  outletId: string;
  lastServerEventId: number;
}

export interface SyncStatusResponse {
  changedTables: string[];
  hasChanges: boolean;
  latestEventId: number;
  needsFullResync: boolean;
  oldestAvailableEventId: number;
  hasOldestAvailableEventId: boolean;
}

export interface SyncPullEventsRequest {
  outletId: string;
  afterEventId: number;
}

export interface SyncTableRows {
  table: string;
  rowsJson: string;
}

export interface SyncPullEventsResponse {
  tables: SyncTableRows[];
  latestEventId: number;
  needsFullResync: boolean;
}

export interface SyncPullRequest {
  outletId: string;
  tables: string[];
  since: string;
}

export interface SyncPullResponse {
  tables: SyncTableRows[];
  serverTime: string;
}

function createBaseSyncPushRequest(): SyncPushRequest {
  return { outletId: "", payloadJson: "" };
}

export const SyncPushRequest: MessageFns<SyncPushRequest> = {
  encode(message: SyncPushRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outletId !== "") {
      writer.uint32(10).string(message.outletId);
    }
    if (message.payloadJson !== "") {
      writer.uint32(18).string(message.payloadJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncPushRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncPushRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outletId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payloadJson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncPushRequest {
    return {
      outletId: isSet(object.outletId)
        ? globalThis.String(object.outletId)
        : isSet(object.outlet_id)
        ? globalThis.String(object.outlet_id)
        : "",
      payloadJson: isSet(object.payloadJson)
        ? globalThis.String(object.payloadJson)
        : isSet(object.payload_json)
        ? globalThis.String(object.payload_json)
        : "",
    };
  },

  toJSON(message: SyncPushRequest): unknown {
    const obj: any = {};
    if (message.outletId !== "") {
      obj.outletId = message.outletId;
    }
    if (message.payloadJson !== "") {
      obj.payloadJson = message.payloadJson;
    }
    return obj;
  },

  create(base?: DeepPartial<SyncPushRequest>): SyncPushRequest {
    return SyncPushRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SyncPushRequest>): SyncPushRequest {
    const message = createBaseSyncPushRequest();
    message.outletId = object.outletId ?? "";
    message.payloadJson = object.payloadJson ?? "";
    return message;
  },
};

function createBaseSyncServerWin(): SyncServerWin {
  return { table: "", ids: [] };
}

export const SyncServerWin: MessageFns<SyncServerWin> = {
  encode(message: SyncServerWin, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.table !== "") {
      writer.uint32(10).string(message.table);
    }
    for (const v of message.ids) {
      writer.uint32(18).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncServerWin {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncServerWin();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.table = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.ids.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncServerWin {
    return {
      table: isSet(object.table) ? globalThis.String(object.table) : "",
      ids: globalThis.Array.isArray(object?.ids) ? object.ids.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: SyncServerWin): unknown {
    const obj: any = {};
    if (message.table !== "") {
      obj.table = message.table;
    }
    if (message.ids?.length) {
      obj.ids = message.ids;
    }
    return obj;
  },

  create(base?: DeepPartial<SyncServerWin>): SyncServerWin {
    return SyncServerWin.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SyncServerWin>): SyncServerWin {
    const message = createBaseSyncServerWin();
    message.table = object.table ?? "";
    message.ids = object.ids?.map((e) => e) || [];
    return message;
  },
};

function createBaseSyncPushResponse(): SyncPushResponse {
  return { serverWins: [], serverTime: "" };
}

export const SyncPushResponse: MessageFns<SyncPushResponse> = {
  encode(message: SyncPushResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.serverWins) {
      SyncServerWin.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.serverTime !== "") {
      writer.uint32(18).string(message.serverTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncPushResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncPushResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.serverWins.push(SyncServerWin.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverTime = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncPushResponse {
    return {
      serverWins: globalThis.Array.isArray(object?.serverWins)
        ? object.serverWins.map((e: any) => SyncServerWin.fromJSON(e))
        : globalThis.Array.isArray(object?.server_wins)
        ? object.server_wins.map((e: any) => SyncServerWin.fromJSON(e))
        : [],
      serverTime: isSet(object.serverTime)
        ? globalThis.String(object.serverTime)
        : isSet(object.server_time)
        ? globalThis.String(object.server_time)
        : "",
    };
  },

  toJSON(message: SyncPushResponse): unknown {
    const obj: any = {};
    if (message.serverWins?.length) {
      obj.serverWins = message.serverWins.map((e) => SyncServerWin.toJSON(e));
    }
    if (message.serverTime !== "") {
      obj.serverTime = message.serverTime;
    }
    return obj;
  },

  create(base?: DeepPartial<SyncPushResponse>): SyncPushResponse {
    return SyncPushResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SyncPushResponse>): SyncPushResponse {
    const message = createBaseSyncPushResponse();
    message.serverWins = object.serverWins?.map((e) => SyncServerWin.fromPartial(e)) || [];
    message.serverTime = object.serverTime ?? "";
    return message;
  },
};

function createBaseSyncStatusRequest(): SyncStatusRequest {
  return { outletId: "", lastServerEventId: 0 };
}

export const SyncStatusRequest: MessageFns<SyncStatusRequest> = {
  encode(message: SyncStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outletId !== "") {
      writer.uint32(10).string(message.outletId);
    }
    if (message.lastServerEventId !== 0) {
      writer.uint32(16).int64(message.lastServerEventId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outletId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.lastServerEventId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncStatusRequest {
    return {
      outletId: isSet(object.outletId)
        ? globalThis.String(object.outletId)
        : isSet(object.outlet_id)
        ? globalThis.String(object.outlet_id)
        : "",
      lastServerEventId: isSet(object.lastServerEventId)
        ? globalThis.Number(object.lastServerEventId)
        : isSet(object.last_server_event_id)
        ? globalThis.Number(object.last_server_event_id)
        : 0,
    };
  },

  toJSON(message: SyncStatusRequest): unknown {
    const obj: any = {};
    if (message.outletId !== "") {
      obj.outletId = message.outletId;
    }
    if (message.lastServerEventId !== 0) {
      obj.lastServerEventId = Math.round(message.lastServerEventId);
    }
    return obj;
  },

  create(base?: DeepPartial<SyncStatusRequest>): SyncStatusRequest {
    return SyncStatusRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SyncStatusRequest>): SyncStatusRequest {
    const message = createBaseSyncStatusRequest();
    message.outletId = object.outletId ?? "";
    message.lastServerEventId = object.lastServerEventId ?? 0;
    return message;
  },
};

function createBaseSyncStatusResponse(): SyncStatusResponse {
  return {
    changedTables: [],
    hasChanges: false,
    latestEventId: 0,
    needsFullResync: false,
    oldestAvailableEventId: 0,
    hasOldestAvailableEventId: false,
  };
}

export const SyncStatusResponse: MessageFns<SyncStatusResponse> = {
  encode(message: SyncStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.changedTables) {
      writer.uint32(10).string(v!);
    }
    if (message.hasChanges !== false) {
      writer.uint32(16).bool(message.hasChanges);
    }
    if (message.latestEventId !== 0) {
      writer.uint32(24).int64(message.latestEventId);
    }
    if (message.needsFullResync !== false) {
      writer.uint32(32).bool(message.needsFullResync);
    }
    if (message.oldestAvailableEventId !== 0) {
      writer.uint32(40).int64(message.oldestAvailableEventId);
    }
    if (message.hasOldestAvailableEventId !== false) {
      writer.uint32(48).bool(message.hasOldestAvailableEventId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.changedTables.push(reader.string());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.hasChanges = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.latestEventId = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.needsFullResync = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.oldestAvailableEventId = longToNumber(reader.int64());
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.hasOldestAvailableEventId = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncStatusResponse {
    return {
      changedTables: globalThis.Array.isArray(object?.changedTables)
        ? object.changedTables.map((e: any) => globalThis.String(e))
        : globalThis.Array.isArray(object?.changed_tables)
        ? object.changed_tables.map((e: any) => globalThis.String(e))
        : [],
      hasChanges: isSet(object.hasChanges)
        ? globalThis.Boolean(object.hasChanges)
        : isSet(object.has_changes)
        ? globalThis.Boolean(object.has_changes)
        : false,
      latestEventId: isSet(object.latestEventId)
        ? globalThis.Number(object.latestEventId)
        : isSet(object.latest_event_id)
        ? globalThis.Number(object.latest_event_id)
        : 0,
      needsFullResync: isSet(object.needsFullResync)
        ? globalThis.Boolean(object.needsFullResync)
        : isSet(object.needs_full_resync)
        ? globalThis.Boolean(object.needs_full_resync)
        : false,
      oldestAvailableEventId: isSet(object.oldestAvailableEventId)
        ? globalThis.Number(object.oldestAvailableEventId)
        : isSet(object.oldest_available_event_id)
        ? globalThis.Number(object.oldest_available_event_id)
        : 0,
      hasOldestAvailableEventId: isSet(object.hasOldestAvailableEventId)
        ? globalThis.Boolean(object.hasOldestAvailableEventId)
        : isSet(object.has_oldest_available_event_id)
        ? globalThis.Boolean(object.has_oldest_available_event_id)
        : false,
    };
  },

  toJSON(message: SyncStatusResponse): unknown {
    const obj: any = {};
    if (message.changedTables?.length) {
      obj.changedTables = message.changedTables;
    }
    if (message.hasChanges !== false) {
      obj.hasChanges = message.hasChanges;
    }
    if (message.latestEventId !== 0) {
      obj.latestEventId = Math.round(message.latestEventId);
    }
    if (message.needsFullResync !== false) {
      obj.needsFullResync = message.needsFullResync;
    }
    if (message.oldestAvailableEventId !== 0) {
      obj.oldestAvailableEventId = Math.round(message.oldestAvailableEventId);
    }
    if (message.hasOldestAvailableEventId !== false) {
      obj.hasOldestAvailableEventId = message.hasOldestAvailableEventId;
    }
    return obj;
  },

  create(base?: DeepPartial<SyncStatusResponse>): SyncStatusResponse {
    return SyncStatusResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SyncStatusResponse>): SyncStatusResponse {
    const message = createBaseSyncStatusResponse();
    message.changedTables = object.changedTables?.map((e) => e) || [];
    message.hasChanges = object.hasChanges ?? false;
    message.latestEventId = object.latestEventId ?? 0;
    message.needsFullResync = object.needsFullResync ?? false;
    message.oldestAvailableEventId = object.oldestAvailableEventId ?? 0;
    message.hasOldestAvailableEventId = object.hasOldestAvailableEventId ?? false;
    return message;
  },
};

function createBaseSyncPullEventsRequest(): SyncPullEventsRequest {
  return { outletId: "", afterEventId: 0 };
}

export const SyncPullEventsRequest: MessageFns<SyncPullEventsRequest> = {
  encode(message: SyncPullEventsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outletId !== "") {
      writer.uint32(10).string(message.outletId);
    }
    if (message.afterEventId !== 0) {
      writer.uint32(16).int64(message.afterEventId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncPullEventsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncPullEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outletId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.afterEventId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncPullEventsRequest {
    return {
      outletId: isSet(object.outletId)
        ? globalThis.String(object.outletId)
        : isSet(object.outlet_id)
        ? globalThis.String(object.outlet_id)
        : "",
      afterEventId: isSet(object.afterEventId)
        ? globalThis.Number(object.afterEventId)
        : isSet(object.after_event_id)
        ? globalThis.Number(object.after_event_id)
        : 0,
    };
  },

  toJSON(message: SyncPullEventsRequest): unknown {
    const obj: any = {};
    if (message.outletId !== "") {
      obj.outletId = message.outletId;
    }
    if (message.afterEventId !== 0) {
      obj.afterEventId = Math.round(message.afterEventId);
    }
    return obj;
  },

  create(base?: DeepPartial<SyncPullEventsRequest>): SyncPullEventsRequest {
    return SyncPullEventsRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SyncPullEventsRequest>): SyncPullEventsRequest {
    const message = createBaseSyncPullEventsRequest();
    message.outletId = object.outletId ?? "";
    message.afterEventId = object.afterEventId ?? 0;
    return message;
  },
};

function createBaseSyncTableRows(): SyncTableRows {
  return { table: "", rowsJson: "" };
}

export const SyncTableRows: MessageFns<SyncTableRows> = {
  encode(message: SyncTableRows, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.table !== "") {
      writer.uint32(10).string(message.table);
    }
    if (message.rowsJson !== "") {
      writer.uint32(18).string(message.rowsJson);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncTableRows {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncTableRows();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.table = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.rowsJson = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncTableRows {
    return {
      table: isSet(object.table) ? globalThis.String(object.table) : "",
      rowsJson: isSet(object.rowsJson)
        ? globalThis.String(object.rowsJson)
        : isSet(object.rows_json)
        ? globalThis.String(object.rows_json)
        : "",
    };
  },

  toJSON(message: SyncTableRows): unknown {
    const obj: any = {};
    if (message.table !== "") {
      obj.table = message.table;
    }
    if (message.rowsJson !== "") {
      obj.rowsJson = message.rowsJson;
    }
    return obj;
  },

  create(base?: DeepPartial<SyncTableRows>): SyncTableRows {
    return SyncTableRows.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SyncTableRows>): SyncTableRows {
    const message = createBaseSyncTableRows();
    message.table = object.table ?? "";
    message.rowsJson = object.rowsJson ?? "";
    return message;
  },
};

function createBaseSyncPullEventsResponse(): SyncPullEventsResponse {
  return { tables: [], latestEventId: 0, needsFullResync: false };
}

export const SyncPullEventsResponse: MessageFns<SyncPullEventsResponse> = {
  encode(message: SyncPullEventsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tables) {
      SyncTableRows.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.latestEventId !== 0) {
      writer.uint32(16).int64(message.latestEventId);
    }
    if (message.needsFullResync !== false) {
      writer.uint32(24).bool(message.needsFullResync);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncPullEventsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncPullEventsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tables.push(SyncTableRows.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.latestEventId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.needsFullResync = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncPullEventsResponse {
    return {
      tables: globalThis.Array.isArray(object?.tables) ? object.tables.map((e: any) => SyncTableRows.fromJSON(e)) : [],
      latestEventId: isSet(object.latestEventId)
        ? globalThis.Number(object.latestEventId)
        : isSet(object.latest_event_id)
        ? globalThis.Number(object.latest_event_id)
        : 0,
      needsFullResync: isSet(object.needsFullResync)
        ? globalThis.Boolean(object.needsFullResync)
        : isSet(object.needs_full_resync)
        ? globalThis.Boolean(object.needs_full_resync)
        : false,
    };
  },

  toJSON(message: SyncPullEventsResponse): unknown {
    const obj: any = {};
    if (message.tables?.length) {
      obj.tables = message.tables.map((e) => SyncTableRows.toJSON(e));
    }
    if (message.latestEventId !== 0) {
      obj.latestEventId = Math.round(message.latestEventId);
    }
    if (message.needsFullResync !== false) {
      obj.needsFullResync = message.needsFullResync;
    }
    return obj;
  },

  create(base?: DeepPartial<SyncPullEventsResponse>): SyncPullEventsResponse {
    return SyncPullEventsResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SyncPullEventsResponse>): SyncPullEventsResponse {
    const message = createBaseSyncPullEventsResponse();
    message.tables = object.tables?.map((e) => SyncTableRows.fromPartial(e)) || [];
    message.latestEventId = object.latestEventId ?? 0;
    message.needsFullResync = object.needsFullResync ?? false;
    return message;
  },
};

function createBaseSyncPullRequest(): SyncPullRequest {
  return { outletId: "", tables: [], since: "" };
}

export const SyncPullRequest: MessageFns<SyncPullRequest> = {
  encode(message: SyncPullRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outletId !== "") {
      writer.uint32(10).string(message.outletId);
    }
    for (const v of message.tables) {
      writer.uint32(18).string(v!);
    }
    if (message.since !== "") {
      writer.uint32(26).string(message.since);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncPullRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncPullRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outletId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.tables.push(reader.string());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.since = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncPullRequest {
    return {
      outletId: isSet(object.outletId)
        ? globalThis.String(object.outletId)
        : isSet(object.outlet_id)
        ? globalThis.String(object.outlet_id)
        : "",
      tables: globalThis.Array.isArray(object?.tables) ? object.tables.map((e: any) => globalThis.String(e)) : [],
      since: isSet(object.since) ? globalThis.String(object.since) : "",
    };
  },

  toJSON(message: SyncPullRequest): unknown {
    const obj: any = {};
    if (message.outletId !== "") {
      obj.outletId = message.outletId;
    }
    if (message.tables?.length) {
      obj.tables = message.tables;
    }
    if (message.since !== "") {
      obj.since = message.since;
    }
    return obj;
  },

  create(base?: DeepPartial<SyncPullRequest>): SyncPullRequest {
    return SyncPullRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SyncPullRequest>): SyncPullRequest {
    const message = createBaseSyncPullRequest();
    message.outletId = object.outletId ?? "";
    message.tables = object.tables?.map((e) => e) || [];
    message.since = object.since ?? "";
    return message;
  },
};

function createBaseSyncPullResponse(): SyncPullResponse {
  return { tables: [], serverTime: "" };
}

export const SyncPullResponse: MessageFns<SyncPullResponse> = {
  encode(message: SyncPullResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.tables) {
      SyncTableRows.encode(v!, writer.uint32(10).fork()).join();
    }
    if (message.serverTime !== "") {
      writer.uint32(18).string(message.serverTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SyncPullResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSyncPullResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.tables.push(SyncTableRows.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.serverTime = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SyncPullResponse {
    return {
      tables: globalThis.Array.isArray(object?.tables) ? object.tables.map((e: any) => SyncTableRows.fromJSON(e)) : [],
      serverTime: isSet(object.serverTime)
        ? globalThis.String(object.serverTime)
        : isSet(object.server_time)
        ? globalThis.String(object.server_time)
        : "",
    };
  },

  toJSON(message: SyncPullResponse): unknown {
    const obj: any = {};
    if (message.tables?.length) {
      obj.tables = message.tables.map((e) => SyncTableRows.toJSON(e));
    }
    if (message.serverTime !== "") {
      obj.serverTime = message.serverTime;
    }
    return obj;
  },

  create(base?: DeepPartial<SyncPullResponse>): SyncPullResponse {
    return SyncPullResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SyncPullResponse>): SyncPullResponse {
    const message = createBaseSyncPullResponse();
    message.tables = object.tables?.map((e) => SyncTableRows.fromPartial(e)) || [];
    message.serverTime = object.serverTime ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
