[package]
name = "sakti-pos"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "sakti_pos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
prost-build = "0.13"
protoc-bin-vendored = "3"
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-opener = "2"
tauri-plugin-android-fs = "28.1.0"
tauri-plugin-deep-link = "2.0.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio"] }
base64 = "0.22.1"
kamadak-exif = "0.6"
image = { version = "0.25.10", default-features = false, features = ["jpeg", "png"] }
reqwest = { version = "0.12", features = ["rustls-tls", "json"], default-features = false }
sha2 = "0.10.9"
tokio = { version = "1", features = ["fs"] }
prost = "0.13"
zenwebp = "0.4.4"
time = { version = "0.3", features = ["formatting"] }
log = "0.4.29"
tauri-plugin-log = "2.8.0"
uuid = { version = "1.23.1", features = ["v4"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev.package."*"]
opt-level = 3
