// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: assets.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sakti.assets.v1";

export interface Asset {
  id: string;
  merchantId: string;
  objectKey: string;
  originalFilename: string;
  contentType: string;
  byteSize: bigint;
  contentHash: string;
  kind: string;
  width: number;
  height: number;
  status: string;
  createdByUserId: string;
  deletedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface AssetHeader {
  name: string;
  value: string;
}

export interface AssetPresignUploadRequest {
  merchantId: string;
  contentHash: string;
  byteSize: bigint;
  contentType: string;
  kind: string;
  originalFilename: string;
  width: number;
  height: number;
  assetId: string;
  objectKey: string;
}

export interface AssetPresignUploadResponse {
  asset: Asset | undefined;
  uploadUrl: string;
  requiredHeaders: AssetHeader[];
}

export interface AssetCompleteUploadRequest {
  assetId: string;
  objectKey: string;
  contentHash: string;
  byteSize: bigint;
}

export interface AssetCompleteUploadResponse {
  asset: Asset | undefined;
}

export interface AssetPresignDownloadRequest {
  assetId: string;
}

export interface AssetPresignDownloadResponse {
  downloadUrl: string;
}

function createBaseAsset(): Asset {
  return {
    id: "",
    merchantId: "",
    objectKey: "",
    originalFilename: "",
    contentType: "",
    byteSize: 0n,
    contentHash: "",
    kind: "",
    width: 0,
    height: 0,
    status: "",
    createdByUserId: "",
    deletedAt: "",
    createdAt: "",
    updatedAt: "",
  };
}

export const Asset: MessageFns<Asset> = {
  encode(message: Asset, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.merchantId !== "") {
      writer.uint32(18).string(message.merchantId);
    }
    if (message.objectKey !== "") {
      writer.uint32(26).string(message.objectKey);
    }
    if (message.originalFilename !== "") {
      writer.uint32(34).string(message.originalFilename);
    }
    if (message.contentType !== "") {
      writer.uint32(42).string(message.contentType);
    }
    if (message.byteSize !== 0n) {
      if (BigInt.asIntN(64, message.byteSize) !== message.byteSize) {
        throw new globalThis.Error("value provided for field message.byteSize of type int64 too large");
      }
      writer.uint32(48).int64(message.byteSize);
    }
    if (message.contentHash !== "") {
      writer.uint32(58).string(message.contentHash);
    }
    if (message.kind !== "") {
      writer.uint32(66).string(message.kind);
    }
    if (message.width !== 0) {
      writer.uint32(72).int32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(80).int32(message.height);
    }
    if (message.status !== "") {
      writer.uint32(90).string(message.status);
    }
    if (message.createdByUserId !== "") {
      writer.uint32(98).string(message.createdByUserId);
    }
    if (message.deletedAt !== "") {
      writer.uint32(106).string(message.deletedAt);
    }
    if (message.createdAt !== "") {
      writer.uint32(114).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(122).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Asset {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAsset();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.merchantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.originalFilename = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.byteSize = reader.int64() as bigint;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.contentHash = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.kind = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 80) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.createdByUserId = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.deletedAt = reader.string();
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Asset {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      merchantId: isSet(object.merchantId)
        ? globalThis.String(object.merchantId)
        : isSet(object.merchant_id)
        ? globalThis.String(object.merchant_id)
        : "",
      objectKey: isSet(object.objectKey)
        ? globalThis.String(object.objectKey)
        : isSet(object.object_key)
        ? globalThis.String(object.object_key)
        : "",
      originalFilename: isSet(object.originalFilename)
        ? globalThis.String(object.originalFilename)
        : isSet(object.original_filename)
        ? globalThis.String(object.original_filename)
        : "",
      contentType: isSet(object.contentType)
        ? globalThis.String(object.contentType)
        : isSet(object.content_type)
        ? globalThis.String(object.content_type)
        : "",
      byteSize: isSet(object.byteSize)
        ? BigInt(object.byteSize)
        : isSet(object.byte_size)
        ? BigInt(object.byte_size)
        : 0n,
      contentHash: isSet(object.contentHash)
        ? globalThis.String(object.contentHash)
        : isSet(object.content_hash)
        ? globalThis.String(object.content_hash)
        : "",
      kind: isSet(object.kind) ? globalThis.String(object.kind) : "",
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      createdByUserId: isSet(object.createdByUserId)
        ? globalThis.String(object.createdByUserId)
        : isSet(object.created_by_user_id)
        ? globalThis.String(object.created_by_user_id)
        : "",
      deletedAt: isSet(object.deletedAt)
        ? globalThis.String(object.deletedAt)
        : isSet(object.deleted_at)
        ? globalThis.String(object.deleted_at)
        : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
        ? globalThis.String(object.created_at)
        : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
        ? globalThis.String(object.updated_at)
        : "",
    };
  },

  toJSON(message: Asset): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.merchantId !== "") {
      obj.merchantId = message.merchantId;
    }
    if (message.objectKey !== "") {
      obj.objectKey = message.objectKey;
    }
    if (message.originalFilename !== "") {
      obj.originalFilename = message.originalFilename;
    }
    if (message.contentType !== "") {
      obj.contentType = message.contentType;
    }
    if (message.byteSize !== 0n) {
      obj.byteSize = message.byteSize.toString();
    }
    if (message.contentHash !== "") {
      obj.contentHash = message.contentHash;
    }
    if (message.kind !== "") {
      obj.kind = message.kind;
    }
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.createdByUserId !== "") {
      obj.createdByUserId = message.createdByUserId;
    }
    if (message.deletedAt !== "") {
      obj.deletedAt = message.deletedAt;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create(base?: DeepPartial<Asset>): Asset {
    return Asset.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Asset>): Asset {
    const message = createBaseAsset();
    message.id = object.id ?? "";
    message.merchantId = object.merchantId ?? "";
    message.objectKey = object.objectKey ?? "";
    message.originalFilename = object.originalFilename ?? "";
    message.contentType = object.contentType ?? "";
    message.byteSize = object.byteSize ?? 0n;
    message.contentHash = object.contentHash ?? "";
    message.kind = object.kind ?? "";
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    message.status = object.status ?? "";
    message.createdByUserId = object.createdByUserId ?? "";
    message.deletedAt = object.deletedAt ?? "";
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseAssetHeader(): AssetHeader {
  return { name: "", value: "" };
}

export const AssetHeader: MessageFns<AssetHeader> = {
  encode(message: AssetHeader, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.value !== "") {
      writer.uint32(18).string(message.value);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssetHeader {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetHeader();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetHeader {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      value: isSet(object.value) ? globalThis.String(object.value) : "",
    };
  },

  toJSON(message: AssetHeader): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.value !== "") {
      obj.value = message.value;
    }
    return obj;
  },

  create(base?: DeepPartial<AssetHeader>): AssetHeader {
    return AssetHeader.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AssetHeader>): AssetHeader {
    const message = createBaseAssetHeader();
    message.name = object.name ?? "";
    message.value = object.value ?? "";
    return message;
  },
};

function createBaseAssetPresignUploadRequest(): AssetPresignUploadRequest {
  return {
    merchantId: "",
    contentHash: "",
    byteSize: 0n,
    contentType: "",
    kind: "",
    originalFilename: "",
    width: 0,
    height: 0,
    assetId: "",
    objectKey: "",
  };
}

export const AssetPresignUploadRequest: MessageFns<AssetPresignUploadRequest> = {
  encode(message: AssetPresignUploadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.merchantId !== "") {
      writer.uint32(10).string(message.merchantId);
    }
    if (message.contentHash !== "") {
      writer.uint32(18).string(message.contentHash);
    }
    if (message.byteSize !== 0n) {
      if (BigInt.asIntN(64, message.byteSize) !== message.byteSize) {
        throw new globalThis.Error("value provided for field message.byteSize of type int64 too large");
      }
      writer.uint32(24).int64(message.byteSize);
    }
    if (message.contentType !== "") {
      writer.uint32(34).string(message.contentType);
    }
    if (message.kind !== "") {
      writer.uint32(42).string(message.kind);
    }
    if (message.originalFilename !== "") {
      writer.uint32(50).string(message.originalFilename);
    }
    if (message.width !== 0) {
      writer.uint32(56).int32(message.width);
    }
    if (message.height !== 0) {
      writer.uint32(64).int32(message.height);
    }
    if (message.assetId !== "") {
      writer.uint32(130).string(message.assetId);
    }
    if (message.objectKey !== "") {
      writer.uint32(138).string(message.objectKey);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssetPresignUploadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetPresignUploadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.contentHash = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.byteSize = reader.int64() as bigint;
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.contentType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.kind = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.originalFilename = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.width = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.height = reader.int32();
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.assetId = reader.string();
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetPresignUploadRequest {
    return {
      merchantId: isSet(object.merchantId)
        ? globalThis.String(object.merchantId)
        : isSet(object.merchant_id)
        ? globalThis.String(object.merchant_id)
        : "",
      contentHash: isSet(object.contentHash)
        ? globalThis.String(object.contentHash)
        : isSet(object.content_hash)
        ? globalThis.String(object.content_hash)
        : "",
      byteSize: isSet(object.byteSize)
        ? BigInt(object.byteSize)
        : isSet(object.byte_size)
        ? BigInt(object.byte_size)
        : 0n,
      contentType: isSet(object.contentType)
        ? globalThis.String(object.contentType)
        : isSet(object.content_type)
        ? globalThis.String(object.content_type)
        : "",
      kind: isSet(object.kind) ? globalThis.String(object.kind) : "",
      originalFilename: isSet(object.originalFilename)
        ? globalThis.String(object.originalFilename)
        : isSet(object.original_filename)
        ? globalThis.String(object.original_filename)
        : "",
      width: isSet(object.width) ? globalThis.Number(object.width) : 0,
      height: isSet(object.height) ? globalThis.Number(object.height) : 0,
      assetId: isSet(object.assetId)
        ? globalThis.String(object.assetId)
        : isSet(object.asset_id)
        ? globalThis.String(object.asset_id)
        : "",
      objectKey: isSet(object.objectKey)
        ? globalThis.String(object.objectKey)
        : isSet(object.object_key)
        ? globalThis.String(object.object_key)
        : "",
    };
  },

  toJSON(message: AssetPresignUploadRequest): unknown {
    const obj: any = {};
    if (message.merchantId !== "") {
      obj.merchantId = message.merchantId;
    }
    if (message.contentHash !== "") {
      obj.contentHash = message.contentHash;
    }
    if (message.byteSize !== 0n) {
      obj.byteSize = message.byteSize.toString();
    }
    if (message.contentType !== "") {
      obj.contentType = message.contentType;
    }
    if (message.kind !== "") {
      obj.kind = message.kind;
    }
    if (message.originalFilename !== "") {
      obj.originalFilename = message.originalFilename;
    }
    if (message.width !== 0) {
      obj.width = Math.round(message.width);
    }
    if (message.height !== 0) {
      obj.height = Math.round(message.height);
    }
    if (message.assetId !== "") {
      obj.assetId = message.assetId;
    }
    if (message.objectKey !== "") {
      obj.objectKey = message.objectKey;
    }
    return obj;
  },

  create(base?: DeepPartial<AssetPresignUploadRequest>): AssetPresignUploadRequest {
    return AssetPresignUploadRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AssetPresignUploadRequest>): AssetPresignUploadRequest {
    const message = createBaseAssetPresignUploadRequest();
    message.merchantId = object.merchantId ?? "";
    message.contentHash = object.contentHash ?? "";
    message.byteSize = object.byteSize ?? 0n;
    message.contentType = object.contentType ?? "";
    message.kind = object.kind ?? "";
    message.originalFilename = object.originalFilename ?? "";
    message.width = object.width ?? 0;
    message.height = object.height ?? 0;
    message.assetId = object.assetId ?? "";
    message.objectKey = object.objectKey ?? "";
    return message;
  },
};

function createBaseAssetPresignUploadResponse(): AssetPresignUploadResponse {
  return { asset: undefined, uploadUrl: "", requiredHeaders: [] };
}

export const AssetPresignUploadResponse: MessageFns<AssetPresignUploadResponse> = {
  encode(message: AssetPresignUploadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.asset !== undefined) {
      Asset.encode(message.asset, writer.uint32(10).fork()).join();
    }
    if (message.uploadUrl !== "") {
      writer.uint32(18).string(message.uploadUrl);
    }
    for (const v of message.requiredHeaders) {
      AssetHeader.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssetPresignUploadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetPresignUploadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.asset = Asset.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.uploadUrl = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.requiredHeaders.push(AssetHeader.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetPresignUploadResponse {
    return {
      asset: isSet(object.asset) ? Asset.fromJSON(object.asset) : undefined,
      uploadUrl: isSet(object.uploadUrl)
        ? globalThis.String(object.uploadUrl)
        : isSet(object.upload_url)
        ? globalThis.String(object.upload_url)
        : "",
      requiredHeaders: globalThis.Array.isArray(object?.requiredHeaders)
        ? object.requiredHeaders.map((e: any) => AssetHeader.fromJSON(e))
        : globalThis.Array.isArray(object?.required_headers)
        ? object.required_headers.map((e: any) => AssetHeader.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AssetPresignUploadResponse): unknown {
    const obj: any = {};
    if (message.asset !== undefined) {
      obj.asset = Asset.toJSON(message.asset);
    }
    if (message.uploadUrl !== "") {
      obj.uploadUrl = message.uploadUrl;
    }
    if (message.requiredHeaders?.length) {
      obj.requiredHeaders = message.requiredHeaders.map((e) => AssetHeader.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<AssetPresignUploadResponse>): AssetPresignUploadResponse {
    return AssetPresignUploadResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AssetPresignUploadResponse>): AssetPresignUploadResponse {
    const message = createBaseAssetPresignUploadResponse();
    message.asset = (object.asset !== undefined && object.asset !== null) ? Asset.fromPartial(object.asset) : undefined;
    message.uploadUrl = object.uploadUrl ?? "";
    message.requiredHeaders = object.requiredHeaders?.map((e) => AssetHeader.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAssetCompleteUploadRequest(): AssetCompleteUploadRequest {
  return { assetId: "", objectKey: "", contentHash: "", byteSize: 0n };
}

export const AssetCompleteUploadRequest: MessageFns<AssetCompleteUploadRequest> = {
  encode(message: AssetCompleteUploadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.assetId !== "") {
      writer.uint32(10).string(message.assetId);
    }
    if (message.objectKey !== "") {
      writer.uint32(18).string(message.objectKey);
    }
    if (message.contentHash !== "") {
      writer.uint32(26).string(message.contentHash);
    }
    if (message.byteSize !== 0n) {
      if (BigInt.asIntN(64, message.byteSize) !== message.byteSize) {
        throw new globalThis.Error("value provided for field message.byteSize of type int64 too large");
      }
      writer.uint32(32).int64(message.byteSize);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssetCompleteUploadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetCompleteUploadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.assetId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.objectKey = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.contentHash = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.byteSize = reader.int64() as bigint;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetCompleteUploadRequest {
    return {
      assetId: isSet(object.assetId)
        ? globalThis.String(object.assetId)
        : isSet(object.asset_id)
        ? globalThis.String(object.asset_id)
        : "",
      objectKey: isSet(object.objectKey)
        ? globalThis.String(object.objectKey)
        : isSet(object.object_key)
        ? globalThis.String(object.object_key)
        : "",
      contentHash: isSet(object.contentHash)
        ? globalThis.String(object.contentHash)
        : isSet(object.content_hash)
        ? globalThis.String(object.content_hash)
        : "",
      byteSize: isSet(object.byteSize)
        ? BigInt(object.byteSize)
        : isSet(object.byte_size)
        ? BigInt(object.byte_size)
        : 0n,
    };
  },

  toJSON(message: AssetCompleteUploadRequest): unknown {
    const obj: any = {};
    if (message.assetId !== "") {
      obj.assetId = message.assetId;
    }
    if (message.objectKey !== "") {
      obj.objectKey = message.objectKey;
    }
    if (message.contentHash !== "") {
      obj.contentHash = message.contentHash;
    }
    if (message.byteSize !== 0n) {
      obj.byteSize = message.byteSize.toString();
    }
    return obj;
  },

  create(base?: DeepPartial<AssetCompleteUploadRequest>): AssetCompleteUploadRequest {
    return AssetCompleteUploadRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AssetCompleteUploadRequest>): AssetCompleteUploadRequest {
    const message = createBaseAssetCompleteUploadRequest();
    message.assetId = object.assetId ?? "";
    message.objectKey = object.objectKey ?? "";
    message.contentHash = object.contentHash ?? "";
    message.byteSize = object.byteSize ?? 0n;
    return message;
  },
};

function createBaseAssetCompleteUploadResponse(): AssetCompleteUploadResponse {
  return { asset: undefined };
}

export const AssetCompleteUploadResponse: MessageFns<AssetCompleteUploadResponse> = {
  encode(message: AssetCompleteUploadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.asset !== undefined) {
      Asset.encode(message.asset, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssetCompleteUploadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetCompleteUploadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.asset = Asset.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetCompleteUploadResponse {
    return { asset: isSet(object.asset) ? Asset.fromJSON(object.asset) : undefined };
  },

  toJSON(message: AssetCompleteUploadResponse): unknown {
    const obj: any = {};
    if (message.asset !== undefined) {
      obj.asset = Asset.toJSON(message.asset);
    }
    return obj;
  },

  create(base?: DeepPartial<AssetCompleteUploadResponse>): AssetCompleteUploadResponse {
    return AssetCompleteUploadResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AssetCompleteUploadResponse>): AssetCompleteUploadResponse {
    const message = createBaseAssetCompleteUploadResponse();
    message.asset = (object.asset !== undefined && object.asset !== null) ? Asset.fromPartial(object.asset) : undefined;
    return message;
  },
};

function createBaseAssetPresignDownloadRequest(): AssetPresignDownloadRequest {
  return { assetId: "" };
}

export const AssetPresignDownloadRequest: MessageFns<AssetPresignDownloadRequest> = {
  encode(message: AssetPresignDownloadRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.assetId !== "") {
      writer.uint32(10).string(message.assetId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssetPresignDownloadRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetPresignDownloadRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.assetId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetPresignDownloadRequest {
    return {
      assetId: isSet(object.assetId)
        ? globalThis.String(object.assetId)
        : isSet(object.asset_id)
        ? globalThis.String(object.asset_id)
        : "",
    };
  },

  toJSON(message: AssetPresignDownloadRequest): unknown {
    const obj: any = {};
    if (message.assetId !== "") {
      obj.assetId = message.assetId;
    }
    return obj;
  },

  create(base?: DeepPartial<AssetPresignDownloadRequest>): AssetPresignDownloadRequest {
    return AssetPresignDownloadRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AssetPresignDownloadRequest>): AssetPresignDownloadRequest {
    const message = createBaseAssetPresignDownloadRequest();
    message.assetId = object.assetId ?? "";
    return message;
  },
};

function createBaseAssetPresignDownloadResponse(): AssetPresignDownloadResponse {
  return { downloadUrl: "" };
}

export const AssetPresignDownloadResponse: MessageFns<AssetPresignDownloadResponse> = {
  encode(message: AssetPresignDownloadResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.downloadUrl !== "") {
      writer.uint32(10).string(message.downloadUrl);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AssetPresignDownloadResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAssetPresignDownloadResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.downloadUrl = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AssetPresignDownloadResponse {
    return {
      downloadUrl: isSet(object.downloadUrl)
        ? globalThis.String(object.downloadUrl)
        : isSet(object.download_url)
        ? globalThis.String(object.download_url)
        : "",
    };
  },

  toJSON(message: AssetPresignDownloadResponse): unknown {
    const obj: any = {};
    if (message.downloadUrl !== "") {
      obj.downloadUrl = message.downloadUrl;
    }
    return obj;
  },

  create(base?: DeepPartial<AssetPresignDownloadResponse>): AssetPresignDownloadResponse {
    return AssetPresignDownloadResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AssetPresignDownloadResponse>): AssetPresignDownloadResponse {
    const message = createBaseAssetPresignDownloadResponse();
    message.downloadUrl = object.downloadUrl ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
