// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: auth.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { ApiUser } from "./common";

export const protobufPackage = "sakti.auth.v1";

export interface AuthRegisterRequest {
  email: string;
  password: string;
  name: string;
}

export interface AuthLoginRequest {
  email: string;
  password: string;
}

export interface SessionMerchant {
  merchantId: string;
  name: string;
  role: string;
}

export interface AuthResponse {
  sessionToken: string;
  user: ApiUser | undefined;
}

export interface AuthSessionResponse {
  user: ApiUser | undefined;
  hasUser: boolean;
  merchants: SessionMerchant[];
}

export interface LogoutResponse {
  success: boolean;
}

function createBaseAuthRegisterRequest(): AuthRegisterRequest {
  return { email: "", password: "", name: "" };
}

export const AuthRegisterRequest: MessageFns<AuthRegisterRequest> = {
  encode(message: AuthRegisterRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthRegisterRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthRegisterRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthRegisterRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: AuthRegisterRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create(base?: DeepPartial<AuthRegisterRequest>): AuthRegisterRequest {
    return AuthRegisterRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AuthRegisterRequest>): AuthRegisterRequest {
    const message = createBaseAuthRegisterRequest();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseAuthLoginRequest(): AuthLoginRequest {
  return { email: "", password: "" };
}

export const AuthLoginRequest: MessageFns<AuthLoginRequest> = {
  encode(message: AuthLoginRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.email !== "") {
      writer.uint32(10).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(18).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthLoginRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthLoginRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthLoginRequest {
    return {
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: AuthLoginRequest): unknown {
    const obj: any = {};
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create(base?: DeepPartial<AuthLoginRequest>): AuthLoginRequest {
    return AuthLoginRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AuthLoginRequest>): AuthLoginRequest {
    const message = createBaseAuthLoginRequest();
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseSessionMerchant(): SessionMerchant {
  return { merchantId: "", name: "", role: "" };
}

export const SessionMerchant: MessageFns<SessionMerchant> = {
  encode(message: SessionMerchant, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.merchantId !== "") {
      writer.uint32(10).string(message.merchantId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.role !== "") {
      writer.uint32(26).string(message.role);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SessionMerchant {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSessionMerchant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.role = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SessionMerchant {
    return {
      merchantId: isSet(object.merchantId)
        ? globalThis.String(object.merchantId)
        : isSet(object.merchant_id)
        ? globalThis.String(object.merchant_id)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
    };
  },

  toJSON(message: SessionMerchant): unknown {
    const obj: any = {};
    if (message.merchantId !== "") {
      obj.merchantId = message.merchantId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    return obj;
  },

  create(base?: DeepPartial<SessionMerchant>): SessionMerchant {
    return SessionMerchant.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<SessionMerchant>): SessionMerchant {
    const message = createBaseSessionMerchant();
    message.merchantId = object.merchantId ?? "";
    message.name = object.name ?? "";
    message.role = object.role ?? "";
    return message;
  },
};

function createBaseAuthResponse(): AuthResponse {
  return { sessionToken: "", user: undefined };
}

export const AuthResponse: MessageFns<AuthResponse> = {
  encode(message: AuthResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.sessionToken !== "") {
      writer.uint32(10).string(message.sessionToken);
    }
    if (message.user !== undefined) {
      ApiUser.encode(message.user, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.sessionToken = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.user = ApiUser.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthResponse {
    return {
      sessionToken: isSet(object.sessionToken)
        ? globalThis.String(object.sessionToken)
        : isSet(object.session_token)
        ? globalThis.String(object.session_token)
        : "",
      user: isSet(object.user) ? ApiUser.fromJSON(object.user) : undefined,
    };
  },

  toJSON(message: AuthResponse): unknown {
    const obj: any = {};
    if (message.sessionToken !== "") {
      obj.sessionToken = message.sessionToken;
    }
    if (message.user !== undefined) {
      obj.user = ApiUser.toJSON(message.user);
    }
    return obj;
  },

  create(base?: DeepPartial<AuthResponse>): AuthResponse {
    return AuthResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AuthResponse>): AuthResponse {
    const message = createBaseAuthResponse();
    message.sessionToken = object.sessionToken ?? "";
    message.user = (object.user !== undefined && object.user !== null) ? ApiUser.fromPartial(object.user) : undefined;
    return message;
  },
};

function createBaseAuthSessionResponse(): AuthSessionResponse {
  return { user: undefined, hasUser: false, merchants: [] };
}

export const AuthSessionResponse: MessageFns<AuthSessionResponse> = {
  encode(message: AuthSessionResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.user !== undefined) {
      ApiUser.encode(message.user, writer.uint32(10).fork()).join();
    }
    if (message.hasUser !== false) {
      writer.uint32(16).bool(message.hasUser);
    }
    for (const v of message.merchants) {
      SessionMerchant.encode(v!, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AuthSessionResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAuthSessionResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.user = ApiUser.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.hasUser = reader.bool();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.merchants.push(SessionMerchant.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AuthSessionResponse {
    return {
      user: isSet(object.user) ? ApiUser.fromJSON(object.user) : undefined,
      hasUser: isSet(object.hasUser)
        ? globalThis.Boolean(object.hasUser)
        : isSet(object.has_user)
        ? globalThis.Boolean(object.has_user)
        : false,
      merchants: globalThis.Array.isArray(object?.merchants)
        ? object.merchants.map((e: any) => SessionMerchant.fromJSON(e))
        : [],
    };
  },

  toJSON(message: AuthSessionResponse): unknown {
    const obj: any = {};
    if (message.user !== undefined) {
      obj.user = ApiUser.toJSON(message.user);
    }
    if (message.hasUser !== false) {
      obj.hasUser = message.hasUser;
    }
    if (message.merchants?.length) {
      obj.merchants = message.merchants.map((e) => SessionMerchant.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<AuthSessionResponse>): AuthSessionResponse {
    return AuthSessionResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<AuthSessionResponse>): AuthSessionResponse {
    const message = createBaseAuthSessionResponse();
    message.user = (object.user !== undefined && object.user !== null) ? ApiUser.fromPartial(object.user) : undefined;
    message.hasUser = object.hasUser ?? false;
    message.merchants = object.merchants?.map((e) => SessionMerchant.fromPartial(e)) || [];
    return message;
  },
};

function createBaseLogoutResponse(): LogoutResponse {
  return { success: false };
}

export const LogoutResponse: MessageFns<LogoutResponse> = {
  encode(message: LogoutResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): LogoutResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLogoutResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): LogoutResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: LogoutResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create(base?: DeepPartial<LogoutResponse>): LogoutResponse {
    return LogoutResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<LogoutResponse>): LogoutResponse {
    const message = createBaseLogoutResponse();
    message.success = object.success ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
