// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: common.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "sakti.common.v1";

export type Empty = {};

export interface DeleteResponse {
  success: boolean;
}

export interface ApiUser {
  email: string;
  id: string;
  name: string;
}

export interface Merchant {
  createdAt: string;
  id: string;
  name: string;
  updatedAt: string;
}

export interface Outlet {
  address: string;
  createdAt: string;
  hasAddress: boolean;
  id: string;
  isActive: boolean;
  merchantId: string;
  name: string;
  updatedAt: string;
}

export interface Register {
  createdAt: string;
  hasPairingCode: boolean;
  hasPairingExpiresAt: boolean;
  id: string;
  isActive: boolean;
  name: string;
  outletId: string;
  pairingCode: string;
  pairingExpiresAt: string;
  shortId: string;
  updatedAt: string;
}

export interface Staff {
  createdAt: string;
  hasOutletId: boolean;
  hasPin: boolean;
  id: string;
  isActive: boolean;
  merchantId: string;
  name: string;
  outletId: string;
  role: string;
  updatedAt: string;
}

function createBaseEmpty(): Empty {
  return {};
}

export const Empty: MessageFns<Empty> = {
  encode(_: Empty, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Empty {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEmpty();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): Empty {
    return {};
  },

  toJSON(_: Empty): unknown {
    const obj: any = {};
    return obj;
  },

  create(base?: DeepPartial<Empty>): Empty {
    return Empty.fromPartial(base ?? {});
  },
  fromPartial(_: DeepPartial<Empty>): Empty {
    const message = createBaseEmpty();
    return message;
  },
};

function createBaseDeleteResponse(): DeleteResponse {
  return { success: false };
}

export const DeleteResponse: MessageFns<DeleteResponse> = {
  encode(
    message: DeleteResponse,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeleteResponse {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeleteResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeleteResponse {
    return {
      success: isSet(object.success)
        ? globalThis.Boolean(object.success)
        : false,
    };
  },

  toJSON(message: DeleteResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create(base?: DeepPartial<DeleteResponse>): DeleteResponse {
    return DeleteResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<DeleteResponse>): DeleteResponse {
    const message = createBaseDeleteResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseApiUser(): ApiUser {
  return { id: "", email: "", name: "" };
}

export const ApiUser: MessageFns<ApiUser> = {
  encode(
    message: ApiUser,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ApiUser {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseApiUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ApiUser {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: ApiUser): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create(base?: DeepPartial<ApiUser>): ApiUser {
    return ApiUser.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<ApiUser>): ApiUser {
    const message = createBaseApiUser();
    message.id = object.id ?? "";
    message.email = object.email ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseMerchant(): Merchant {
  return { id: "", name: "", createdAt: "", updatedAt: "" };
}

export const Merchant: MessageFns<Merchant> = {
  encode(
    message: Merchant,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.createdAt !== "") {
      writer.uint32(26).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(34).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Merchant {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMerchant();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Merchant {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
          ? globalThis.String(object.created_at)
          : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
          ? globalThis.String(object.updated_at)
          : "",
    };
  },

  toJSON(message: Merchant): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create(base?: DeepPartial<Merchant>): Merchant {
    return Merchant.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Merchant>): Merchant {
    const message = createBaseMerchant();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseOutlet(): Outlet {
  return {
    id: "",
    merchantId: "",
    name: "",
    address: "",
    hasAddress: false,
    isActive: false,
    createdAt: "",
    updatedAt: "",
  };
}

export const Outlet: MessageFns<Outlet> = {
  encode(
    message: Outlet,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.merchantId !== "") {
      writer.uint32(18).string(message.merchantId);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.address !== "") {
      writer.uint32(34).string(message.address);
    }
    if (message.hasAddress !== false) {
      writer.uint32(40).bool(message.hasAddress);
    }
    if (message.isActive !== false) {
      writer.uint32(48).bool(message.isActive);
    }
    if (message.createdAt !== "") {
      writer.uint32(58).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(66).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Outlet {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutlet();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.merchantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.hasAddress = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Outlet {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      merchantId: isSet(object.merchantId)
        ? globalThis.String(object.merchantId)
        : isSet(object.merchant_id)
          ? globalThis.String(object.merchant_id)
          : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      hasAddress: isSet(object.hasAddress)
        ? globalThis.Boolean(object.hasAddress)
        : isSet(object.has_address)
          ? globalThis.Boolean(object.has_address)
          : false,
      isActive: isSet(object.isActive)
        ? globalThis.Boolean(object.isActive)
        : isSet(object.is_active)
          ? globalThis.Boolean(object.is_active)
          : false,
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
          ? globalThis.String(object.created_at)
          : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
          ? globalThis.String(object.updated_at)
          : "",
    };
  },

  toJSON(message: Outlet): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.merchantId !== "") {
      obj.merchantId = message.merchantId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.hasAddress !== false) {
      obj.hasAddress = message.hasAddress;
    }
    if (message.isActive !== false) {
      obj.isActive = message.isActive;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create(base?: DeepPartial<Outlet>): Outlet {
    return Outlet.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Outlet>): Outlet {
    const message = createBaseOutlet();
    message.id = object.id ?? "";
    message.merchantId = object.merchantId ?? "";
    message.name = object.name ?? "";
    message.address = object.address ?? "";
    message.hasAddress = object.hasAddress ?? false;
    message.isActive = object.isActive ?? false;
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseRegister(): Register {
  return {
    id: "",
    outletId: "",
    name: "",
    shortId: "",
    pairingCode: "",
    hasPairingCode: false,
    pairingExpiresAt: "",
    hasPairingExpiresAt: false,
    isActive: false,
    createdAt: "",
    updatedAt: "",
  };
}

export const Register: MessageFns<Register> = {
  encode(
    message: Register,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.outletId !== "") {
      writer.uint32(18).string(message.outletId);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.shortId !== "") {
      writer.uint32(34).string(message.shortId);
    }
    if (message.pairingCode !== "") {
      writer.uint32(42).string(message.pairingCode);
    }
    if (message.hasPairingCode !== false) {
      writer.uint32(48).bool(message.hasPairingCode);
    }
    if (message.pairingExpiresAt !== "") {
      writer.uint32(58).string(message.pairingExpiresAt);
    }
    if (message.hasPairingExpiresAt !== false) {
      writer.uint32(64).bool(message.hasPairingExpiresAt);
    }
    if (message.isActive !== false) {
      writer.uint32(72).bool(message.isActive);
    }
    if (message.createdAt !== "") {
      writer.uint32(82).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(90).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Register {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegister();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.outletId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.shortId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.pairingCode = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.hasPairingCode = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.pairingExpiresAt = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.hasPairingExpiresAt = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Register {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      outletId: isSet(object.outletId)
        ? globalThis.String(object.outletId)
        : isSet(object.outlet_id)
          ? globalThis.String(object.outlet_id)
          : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      shortId: isSet(object.shortId)
        ? globalThis.String(object.shortId)
        : isSet(object.short_id)
          ? globalThis.String(object.short_id)
          : "",
      pairingCode: isSet(object.pairingCode)
        ? globalThis.String(object.pairingCode)
        : isSet(object.pairing_code)
          ? globalThis.String(object.pairing_code)
          : "",
      hasPairingCode: isSet(object.hasPairingCode)
        ? globalThis.Boolean(object.hasPairingCode)
        : isSet(object.has_pairing_code)
          ? globalThis.Boolean(object.has_pairing_code)
          : false,
      pairingExpiresAt: isSet(object.pairingExpiresAt)
        ? globalThis.String(object.pairingExpiresAt)
        : isSet(object.pairing_expires_at)
          ? globalThis.String(object.pairing_expires_at)
          : "",
      hasPairingExpiresAt: isSet(object.hasPairingExpiresAt)
        ? globalThis.Boolean(object.hasPairingExpiresAt)
        : isSet(object.has_pairing_expires_at)
          ? globalThis.Boolean(object.has_pairing_expires_at)
          : false,
      isActive: isSet(object.isActive)
        ? globalThis.Boolean(object.isActive)
        : isSet(object.is_active)
          ? globalThis.Boolean(object.is_active)
          : false,
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
          ? globalThis.String(object.created_at)
          : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
          ? globalThis.String(object.updated_at)
          : "",
    };
  },

  toJSON(message: Register): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.outletId !== "") {
      obj.outletId = message.outletId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.shortId !== "") {
      obj.shortId = message.shortId;
    }
    if (message.pairingCode !== "") {
      obj.pairingCode = message.pairingCode;
    }
    if (message.hasPairingCode !== false) {
      obj.hasPairingCode = message.hasPairingCode;
    }
    if (message.pairingExpiresAt !== "") {
      obj.pairingExpiresAt = message.pairingExpiresAt;
    }
    if (message.hasPairingExpiresAt !== false) {
      obj.hasPairingExpiresAt = message.hasPairingExpiresAt;
    }
    if (message.isActive !== false) {
      obj.isActive = message.isActive;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create(base?: DeepPartial<Register>): Register {
    return Register.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Register>): Register {
    const message = createBaseRegister();
    message.id = object.id ?? "";
    message.outletId = object.outletId ?? "";
    message.name = object.name ?? "";
    message.shortId = object.shortId ?? "";
    message.pairingCode = object.pairingCode ?? "";
    message.hasPairingCode = object.hasPairingCode ?? false;
    message.pairingExpiresAt = object.pairingExpiresAt ?? "";
    message.hasPairingExpiresAt = object.hasPairingExpiresAt ?? false;
    message.isActive = object.isActive ?? false;
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

function createBaseStaff(): Staff {
  return {
    id: "",
    merchantId: "",
    outletId: "",
    hasOutletId: false,
    name: "",
    role: "",
    isActive: false,
    hasPin: false,
    createdAt: "",
    updatedAt: "",
  };
}

export const Staff: MessageFns<Staff> = {
  encode(
    message: Staff,
    writer: BinaryWriter = new BinaryWriter()
  ): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.merchantId !== "") {
      writer.uint32(18).string(message.merchantId);
    }
    if (message.outletId !== "") {
      writer.uint32(26).string(message.outletId);
    }
    if (message.hasOutletId !== false) {
      writer.uint32(32).bool(message.hasOutletId);
    }
    if (message.name !== "") {
      writer.uint32(42).string(message.name);
    }
    if (message.role !== "") {
      writer.uint32(50).string(message.role);
    }
    if (message.isActive !== false) {
      writer.uint32(56).bool(message.isActive);
    }
    if (message.hasPin !== false) {
      writer.uint32(64).bool(message.hasPin);
    }
    if (message.createdAt !== "") {
      writer.uint32(74).string(message.createdAt);
    }
    if (message.updatedAt !== "") {
      writer.uint32(82).string(message.updatedAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Staff {
    const reader =
      input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaff();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.merchantId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.outletId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.hasOutletId = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.role = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.hasPin = reader.bool();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.updatedAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Staff {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      merchantId: isSet(object.merchantId)
        ? globalThis.String(object.merchantId)
        : isSet(object.merchant_id)
          ? globalThis.String(object.merchant_id)
          : "",
      outletId: isSet(object.outletId)
        ? globalThis.String(object.outletId)
        : isSet(object.outlet_id)
          ? globalThis.String(object.outlet_id)
          : "",
      hasOutletId: isSet(object.hasOutletId)
        ? globalThis.Boolean(object.hasOutletId)
        : isSet(object.has_outlet_id)
          ? globalThis.Boolean(object.has_outlet_id)
          : false,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      isActive: isSet(object.isActive)
        ? globalThis.Boolean(object.isActive)
        : isSet(object.is_active)
          ? globalThis.Boolean(object.is_active)
          : false,
      hasPin: isSet(object.hasPin)
        ? globalThis.Boolean(object.hasPin)
        : isSet(object.has_pin)
          ? globalThis.Boolean(object.has_pin)
          : false,
      createdAt: isSet(object.createdAt)
        ? globalThis.String(object.createdAt)
        : isSet(object.created_at)
          ? globalThis.String(object.created_at)
          : "",
      updatedAt: isSet(object.updatedAt)
        ? globalThis.String(object.updatedAt)
        : isSet(object.updated_at)
          ? globalThis.String(object.updated_at)
          : "",
    };
  },

  toJSON(message: Staff): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.merchantId !== "") {
      obj.merchantId = message.merchantId;
    }
    if (message.outletId !== "") {
      obj.outletId = message.outletId;
    }
    if (message.hasOutletId !== false) {
      obj.hasOutletId = message.hasOutletId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.isActive !== false) {
      obj.isActive = message.isActive;
    }
    if (message.hasPin !== false) {
      obj.hasPin = message.hasPin;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    if (message.updatedAt !== "") {
      obj.updatedAt = message.updatedAt;
    }
    return obj;
  },

  create(base?: DeepPartial<Staff>): Staff {
    return Staff.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<Staff>): Staff {
    const message = createBaseStaff();
    message.id = object.id ?? "";
    message.merchantId = object.merchantId ?? "";
    message.outletId = object.outletId ?? "";
    message.hasOutletId = object.hasOutletId ?? false;
    message.name = object.name ?? "";
    message.role = object.role ?? "";
    message.isActive = object.isActive ?? false;
    message.hasPin = object.hasPin ?? false;
    message.createdAt = object.createdAt ?? "";
    message.updatedAt = object.updatedAt ?? "";
    return message;
  },
};

type Builtin =
  | Date
  | Function
  | Uint8Array
  | string
  | number
  | boolean
  | undefined;

export type DeepPartial<T> = T extends Builtin
  ? T
  : T extends globalThis.Array<infer U>
    ? globalThis.Array<DeepPartial<U>>
    : T extends ReadonlyArray<infer U>
      ? ReadonlyArray<DeepPartial<U>>
      : T extends {}
        ? { [K in keyof T]?: DeepPartial<T[K]> }
        : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  create(base?: DeepPartial<T>): T;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  fromJSON(object: any): T;
  fromPartial(object: DeepPartial<T>): T;
  toJSON(message: T): unknown;
}
