// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: merchants.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { SessionMerchant } from "./auth";
import { Merchant } from "./common";

export const protobufPackage = "sakti.merchants.v1";

export interface MerchantListResponse {
  merchants: SessionMerchant[];
}

export interface MerchantCreateRequest {
  name: string;
}

export interface MerchantCreateResponse {
  merchant: Merchant | undefined;
}

function createBaseMerchantListResponse(): MerchantListResponse {
  return { merchants: [] };
}

export const MerchantListResponse: MessageFns<MerchantListResponse> = {
  encode(message: MerchantListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.merchants) {
      SessionMerchant.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MerchantListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMerchantListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchants.push(SessionMerchant.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MerchantListResponse {
    return {
      merchants: globalThis.Array.isArray(object?.merchants)
        ? object.merchants.map((e: any) => SessionMerchant.fromJSON(e))
        : [],
    };
  },

  toJSON(message: MerchantListResponse): unknown {
    const obj: any = {};
    if (message.merchants?.length) {
      obj.merchants = message.merchants.map((e) => SessionMerchant.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<MerchantListResponse>): MerchantListResponse {
    return MerchantListResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MerchantListResponse>): MerchantListResponse {
    const message = createBaseMerchantListResponse();
    message.merchants = object.merchants?.map((e) => SessionMerchant.fromPartial(e)) || [];
    return message;
  },
};

function createBaseMerchantCreateRequest(): MerchantCreateRequest {
  return { name: "" };
}

export const MerchantCreateRequest: MessageFns<MerchantCreateRequest> = {
  encode(message: MerchantCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MerchantCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMerchantCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MerchantCreateRequest {
    return { name: isSet(object.name) ? globalThis.String(object.name) : "" };
  },

  toJSON(message: MerchantCreateRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create(base?: DeepPartial<MerchantCreateRequest>): MerchantCreateRequest {
    return MerchantCreateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MerchantCreateRequest>): MerchantCreateRequest {
    const message = createBaseMerchantCreateRequest();
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseMerchantCreateResponse(): MerchantCreateResponse {
  return { merchant: undefined };
}

export const MerchantCreateResponse: MessageFns<MerchantCreateResponse> = {
  encode(message: MerchantCreateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.merchant !== undefined) {
      Merchant.encode(message.merchant, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MerchantCreateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMerchantCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchant = Merchant.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MerchantCreateResponse {
    return { merchant: isSet(object.merchant) ? Merchant.fromJSON(object.merchant) : undefined };
  },

  toJSON(message: MerchantCreateResponse): unknown {
    const obj: any = {};
    if (message.merchant !== undefined) {
      obj.merchant = Merchant.toJSON(message.merchant);
    }
    return obj;
  },

  create(base?: DeepPartial<MerchantCreateResponse>): MerchantCreateResponse {
    return MerchantCreateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<MerchantCreateResponse>): MerchantCreateResponse {
    const message = createBaseMerchantCreateResponse();
    message.merchant = (object.merchant !== undefined && object.merchant !== null)
      ? Merchant.fromPartial(object.merchant)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
