// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: outlets.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Outlet, Register } from "./common";

export const protobufPackage = "sakti.outlets.v1";

export interface OutletListRequest {
  merchantId: string;
}

export interface OutletListResponse {
  outlets: Outlet[];
}

export interface OutletCreateRequest {
  merchantId: string;
  name: string;
  address: string;
  hasAddress: boolean;
  timezone: string;
}

export interface OutletCreateResponse {
  outlet: Outlet | undefined;
  register: Register | undefined;
  hasRegister: boolean;
}

export interface OutletUpdateRequest {
  id: string;
  name: string;
  hasName: boolean;
  address: string;
  hasAddress: boolean;
  isActive: boolean;
  hasIsActive: boolean;
  timezone: string;
  hasTimezone: boolean;
  receiptName: string;
  hasReceiptName: boolean;
  receiptAddress: string;
  hasReceiptAddress: boolean;
}

export interface OutletUpdateResponse {
  outlet: Outlet | undefined;
}

function createBaseOutletListRequest(): OutletListRequest {
  return { merchantId: "" };
}

export const OutletListRequest: MessageFns<OutletListRequest> = {
  encode(message: OutletListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.merchantId !== "") {
      writer.uint32(10).string(message.merchantId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutletListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutletListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchantId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutletListRequest {
    return {
      merchantId: isSet(object.merchantId)
        ? globalThis.String(object.merchantId)
        : isSet(object.merchant_id)
        ? globalThis.String(object.merchant_id)
        : "",
    };
  },

  toJSON(message: OutletListRequest): unknown {
    const obj: any = {};
    if (message.merchantId !== "") {
      obj.merchantId = message.merchantId;
    }
    return obj;
  },

  create(base?: DeepPartial<OutletListRequest>): OutletListRequest {
    return OutletListRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OutletListRequest>): OutletListRequest {
    const message = createBaseOutletListRequest();
    message.merchantId = object.merchantId ?? "";
    return message;
  },
};

function createBaseOutletListResponse(): OutletListResponse {
  return { outlets: [] };
}

export const OutletListResponse: MessageFns<OutletListResponse> = {
  encode(message: OutletListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.outlets) {
      Outlet.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutletListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutletListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outlets.push(Outlet.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutletListResponse {
    return {
      outlets: globalThis.Array.isArray(object?.outlets) ? object.outlets.map((e: any) => Outlet.fromJSON(e)) : [],
    };
  },

  toJSON(message: OutletListResponse): unknown {
    const obj: any = {};
    if (message.outlets?.length) {
      obj.outlets = message.outlets.map((e) => Outlet.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<OutletListResponse>): OutletListResponse {
    return OutletListResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OutletListResponse>): OutletListResponse {
    const message = createBaseOutletListResponse();
    message.outlets = object.outlets?.map((e) => Outlet.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOutletCreateRequest(): OutletCreateRequest {
  return { merchantId: "", name: "", address: "", hasAddress: false, timezone: "" };
}

export const OutletCreateRequest: MessageFns<OutletCreateRequest> = {
  encode(message: OutletCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.merchantId !== "") {
      writer.uint32(10).string(message.merchantId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.address !== "") {
      writer.uint32(26).string(message.address);
    }
    if (message.hasAddress !== false) {
      writer.uint32(32).bool(message.hasAddress);
    }
    if (message.timezone !== "") {
      writer.uint32(42).string(message.timezone);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutletCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutletCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.hasAddress = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.timezone = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutletCreateRequest {
    return {
      merchantId: isSet(object.merchantId)
        ? globalThis.String(object.merchantId)
        : isSet(object.merchant_id)
        ? globalThis.String(object.merchant_id)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      hasAddress: isSet(object.hasAddress)
        ? globalThis.Boolean(object.hasAddress)
        : isSet(object.has_address)
        ? globalThis.Boolean(object.has_address)
        : false,
      timezone: isSet(object.timezone) ? globalThis.String(object.timezone) : "",
    };
  },

  toJSON(message: OutletCreateRequest): unknown {
    const obj: any = {};
    if (message.merchantId !== "") {
      obj.merchantId = message.merchantId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.hasAddress !== false) {
      obj.hasAddress = message.hasAddress;
    }
    if (message.timezone !== "") {
      obj.timezone = message.timezone;
    }
    return obj;
  },

  create(base?: DeepPartial<OutletCreateRequest>): OutletCreateRequest {
    return OutletCreateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OutletCreateRequest>): OutletCreateRequest {
    const message = createBaseOutletCreateRequest();
    message.merchantId = object.merchantId ?? "";
    message.name = object.name ?? "";
    message.address = object.address ?? "";
    message.hasAddress = object.hasAddress ?? false;
    message.timezone = object.timezone ?? "";
    return message;
  },
};

function createBaseOutletCreateResponse(): OutletCreateResponse {
  return { outlet: undefined, register: undefined, hasRegister: false };
}

export const OutletCreateResponse: MessageFns<OutletCreateResponse> = {
  encode(message: OutletCreateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outlet !== undefined) {
      Outlet.encode(message.outlet, writer.uint32(10).fork()).join();
    }
    if (message.register !== undefined) {
      Register.encode(message.register, writer.uint32(18).fork()).join();
    }
    if (message.hasRegister !== false) {
      writer.uint32(24).bool(message.hasRegister);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutletCreateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutletCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outlet = Outlet.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.register = Register.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.hasRegister = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutletCreateResponse {
    return {
      outlet: isSet(object.outlet) ? Outlet.fromJSON(object.outlet) : undefined,
      register: isSet(object.register) ? Register.fromJSON(object.register) : undefined,
      hasRegister: isSet(object.hasRegister)
        ? globalThis.Boolean(object.hasRegister)
        : isSet(object.has_register)
        ? globalThis.Boolean(object.has_register)
        : false,
    };
  },

  toJSON(message: OutletCreateResponse): unknown {
    const obj: any = {};
    if (message.outlet !== undefined) {
      obj.outlet = Outlet.toJSON(message.outlet);
    }
    if (message.register !== undefined) {
      obj.register = Register.toJSON(message.register);
    }
    if (message.hasRegister !== false) {
      obj.hasRegister = message.hasRegister;
    }
    return obj;
  },

  create(base?: DeepPartial<OutletCreateResponse>): OutletCreateResponse {
    return OutletCreateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OutletCreateResponse>): OutletCreateResponse {
    const message = createBaseOutletCreateResponse();
    message.outlet = (object.outlet !== undefined && object.outlet !== null)
      ? Outlet.fromPartial(object.outlet)
      : undefined;
    message.register = (object.register !== undefined && object.register !== null)
      ? Register.fromPartial(object.register)
      : undefined;
    message.hasRegister = object.hasRegister ?? false;
    return message;
  },
};

function createBaseOutletUpdateRequest(): OutletUpdateRequest {
  return {
    id: "",
    name: "",
    hasName: false,
    address: "",
    hasAddress: false,
    isActive: false,
    hasIsActive: false,
    timezone: "",
    hasTimezone: false,
    receiptName: "",
    hasReceiptName: false,
    receiptAddress: "",
    hasReceiptAddress: false,
  };
}

export const OutletUpdateRequest: MessageFns<OutletUpdateRequest> = {
  encode(message: OutletUpdateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.hasName !== false) {
      writer.uint32(24).bool(message.hasName);
    }
    if (message.address !== "") {
      writer.uint32(34).string(message.address);
    }
    if (message.hasAddress !== false) {
      writer.uint32(40).bool(message.hasAddress);
    }
    if (message.isActive !== false) {
      writer.uint32(48).bool(message.isActive);
    }
    if (message.hasIsActive !== false) {
      writer.uint32(56).bool(message.hasIsActive);
    }
    if (message.timezone !== "") {
      writer.uint32(66).string(message.timezone);
    }
    if (message.hasTimezone !== false) {
      writer.uint32(72).bool(message.hasTimezone);
    }
    if (message.receiptName !== "") {
      writer.uint32(82).string(message.receiptName);
    }
    if (message.hasReceiptName !== false) {
      writer.uint32(88).bool(message.hasReceiptName);
    }
    if (message.receiptAddress !== "") {
      writer.uint32(98).string(message.receiptAddress);
    }
    if (message.hasReceiptAddress !== false) {
      writer.uint32(104).bool(message.hasReceiptAddress);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutletUpdateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutletUpdateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.hasName = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.hasAddress = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.isActive = reader.bool();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.hasIsActive = reader.bool();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.timezone = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.hasTimezone = reader.bool();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.receiptName = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.hasReceiptName = reader.bool();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.receiptAddress = reader.string();
          continue;
        }
        case 13: {
          if (tag !== 104) {
            break;
          }

          message.hasReceiptAddress = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutletUpdateRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      hasName: isSet(object.hasName)
        ? globalThis.Boolean(object.hasName)
        : isSet(object.has_name)
        ? globalThis.Boolean(object.has_name)
        : false,
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      hasAddress: isSet(object.hasAddress)
        ? globalThis.Boolean(object.hasAddress)
        : isSet(object.has_address)
        ? globalThis.Boolean(object.has_address)
        : false,
      isActive: isSet(object.isActive)
        ? globalThis.Boolean(object.isActive)
        : isSet(object.is_active)
        ? globalThis.Boolean(object.is_active)
        : false,
      hasIsActive: isSet(object.hasIsActive)
        ? globalThis.Boolean(object.hasIsActive)
        : isSet(object.has_is_active)
        ? globalThis.Boolean(object.has_is_active)
        : false,
      timezone: isSet(object.timezone) ? globalThis.String(object.timezone) : "",
      hasTimezone: isSet(object.hasTimezone)
        ? globalThis.Boolean(object.hasTimezone)
        : isSet(object.has_timezone)
        ? globalThis.Boolean(object.has_timezone)
        : false,
      receiptName: isSet(object.receiptName)
        ? globalThis.String(object.receiptName)
        : isSet(object.receipt_name)
        ? globalThis.String(object.receipt_name)
        : "",
      hasReceiptName: isSet(object.hasReceiptName)
        ? globalThis.Boolean(object.hasReceiptName)
        : isSet(object.has_receipt_name)
        ? globalThis.Boolean(object.has_receipt_name)
        : false,
      receiptAddress: isSet(object.receiptAddress)
        ? globalThis.String(object.receiptAddress)
        : isSet(object.receipt_address)
        ? globalThis.String(object.receipt_address)
        : "",
      hasReceiptAddress: isSet(object.hasReceiptAddress)
        ? globalThis.Boolean(object.hasReceiptAddress)
        : isSet(object.has_receipt_address)
        ? globalThis.Boolean(object.has_receipt_address)
        : false,
    };
  },

  toJSON(message: OutletUpdateRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.hasName !== false) {
      obj.hasName = message.hasName;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.hasAddress !== false) {
      obj.hasAddress = message.hasAddress;
    }
    if (message.isActive !== false) {
      obj.isActive = message.isActive;
    }
    if (message.hasIsActive !== false) {
      obj.hasIsActive = message.hasIsActive;
    }
    if (message.timezone !== "") {
      obj.timezone = message.timezone;
    }
    if (message.hasTimezone !== false) {
      obj.hasTimezone = message.hasTimezone;
    }
    if (message.receiptName !== "") {
      obj.receiptName = message.receiptName;
    }
    if (message.hasReceiptName !== false) {
      obj.hasReceiptName = message.hasReceiptName;
    }
    if (message.receiptAddress !== "") {
      obj.receiptAddress = message.receiptAddress;
    }
    if (message.hasReceiptAddress !== false) {
      obj.hasReceiptAddress = message.hasReceiptAddress;
    }
    return obj;
  },

  create(base?: DeepPartial<OutletUpdateRequest>): OutletUpdateRequest {
    return OutletUpdateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OutletUpdateRequest>): OutletUpdateRequest {
    const message = createBaseOutletUpdateRequest();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.hasName = object.hasName ?? false;
    message.address = object.address ?? "";
    message.hasAddress = object.hasAddress ?? false;
    message.isActive = object.isActive ?? false;
    message.hasIsActive = object.hasIsActive ?? false;
    message.timezone = object.timezone ?? "";
    message.hasTimezone = object.hasTimezone ?? false;
    message.receiptName = object.receiptName ?? "";
    message.hasReceiptName = object.hasReceiptName ?? false;
    message.receiptAddress = object.receiptAddress ?? "";
    message.hasReceiptAddress = object.hasReceiptAddress ?? false;
    return message;
  },
};

function createBaseOutletUpdateResponse(): OutletUpdateResponse {
  return { outlet: undefined };
}

export const OutletUpdateResponse: MessageFns<OutletUpdateResponse> = {
  encode(message: OutletUpdateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outlet !== undefined) {
      Outlet.encode(message.outlet, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OutletUpdateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOutletUpdateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outlet = Outlet.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OutletUpdateResponse {
    return { outlet: isSet(object.outlet) ? Outlet.fromJSON(object.outlet) : undefined };
  },

  toJSON(message: OutletUpdateResponse): unknown {
    const obj: any = {};
    if (message.outlet !== undefined) {
      obj.outlet = Outlet.toJSON(message.outlet);
    }
    return obj;
  },

  create(base?: DeepPartial<OutletUpdateResponse>): OutletUpdateResponse {
    return OutletUpdateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<OutletUpdateResponse>): OutletUpdateResponse {
    const message = createBaseOutletUpdateResponse();
    message.outlet = (object.outlet !== undefined && object.outlet !== null)
      ? Outlet.fromPartial(object.outlet)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
