// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: registers.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Outlet, Register } from "./common";

export const protobufPackage = "sakti.registers.v1";

export interface RegisterPairRequest {
  pairingCode: string;
}

export interface RegisterPairResponse {
  register: Register | undefined;
  outlet: Outlet | undefined;
  hasOutlet: boolean;
}

export interface RegisterCreateRequest {
  outletId: string;
  name: string;
}

export interface RegisterCreateResponse {
  register: Register | undefined;
}

export interface RegisterListRequest {
  outletId: string;
}

export interface RegisterListResponse {
  registers: Register[];
}

export interface RegisterDeleteRequest {
  id: string;
}

function createBaseRegisterPairRequest(): RegisterPairRequest {
  return { pairingCode: "" };
}

export const RegisterPairRequest: MessageFns<RegisterPairRequest> = {
  encode(message: RegisterPairRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.pairingCode !== "") {
      writer.uint32(10).string(message.pairingCode);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterPairRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterPairRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.pairingCode = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterPairRequest {
    return {
      pairingCode: isSet(object.pairingCode)
        ? globalThis.String(object.pairingCode)
        : isSet(object.pairing_code)
        ? globalThis.String(object.pairing_code)
        : "",
    };
  },

  toJSON(message: RegisterPairRequest): unknown {
    const obj: any = {};
    if (message.pairingCode !== "") {
      obj.pairingCode = message.pairingCode;
    }
    return obj;
  },

  create(base?: DeepPartial<RegisterPairRequest>): RegisterPairRequest {
    return RegisterPairRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RegisterPairRequest>): RegisterPairRequest {
    const message = createBaseRegisterPairRequest();
    message.pairingCode = object.pairingCode ?? "";
    return message;
  },
};

function createBaseRegisterPairResponse(): RegisterPairResponse {
  return { register: undefined, outlet: undefined, hasOutlet: false };
}

export const RegisterPairResponse: MessageFns<RegisterPairResponse> = {
  encode(message: RegisterPairResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.register !== undefined) {
      Register.encode(message.register, writer.uint32(10).fork()).join();
    }
    if (message.outlet !== undefined) {
      Outlet.encode(message.outlet, writer.uint32(18).fork()).join();
    }
    if (message.hasOutlet !== false) {
      writer.uint32(24).bool(message.hasOutlet);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterPairResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterPairResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.register = Register.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.outlet = Outlet.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.hasOutlet = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterPairResponse {
    return {
      register: isSet(object.register) ? Register.fromJSON(object.register) : undefined,
      outlet: isSet(object.outlet) ? Outlet.fromJSON(object.outlet) : undefined,
      hasOutlet: isSet(object.hasOutlet)
        ? globalThis.Boolean(object.hasOutlet)
        : isSet(object.has_outlet)
        ? globalThis.Boolean(object.has_outlet)
        : false,
    };
  },

  toJSON(message: RegisterPairResponse): unknown {
    const obj: any = {};
    if (message.register !== undefined) {
      obj.register = Register.toJSON(message.register);
    }
    if (message.outlet !== undefined) {
      obj.outlet = Outlet.toJSON(message.outlet);
    }
    if (message.hasOutlet !== false) {
      obj.hasOutlet = message.hasOutlet;
    }
    return obj;
  },

  create(base?: DeepPartial<RegisterPairResponse>): RegisterPairResponse {
    return RegisterPairResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RegisterPairResponse>): RegisterPairResponse {
    const message = createBaseRegisterPairResponse();
    message.register = (object.register !== undefined && object.register !== null)
      ? Register.fromPartial(object.register)
      : undefined;
    message.outlet = (object.outlet !== undefined && object.outlet !== null)
      ? Outlet.fromPartial(object.outlet)
      : undefined;
    message.hasOutlet = object.hasOutlet ?? false;
    return message;
  },
};

function createBaseRegisterCreateRequest(): RegisterCreateRequest {
  return { outletId: "", name: "" };
}

export const RegisterCreateRequest: MessageFns<RegisterCreateRequest> = {
  encode(message: RegisterCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outletId !== "") {
      writer.uint32(10).string(message.outletId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outletId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterCreateRequest {
    return {
      outletId: isSet(object.outletId)
        ? globalThis.String(object.outletId)
        : isSet(object.outlet_id)
        ? globalThis.String(object.outlet_id)
        : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: RegisterCreateRequest): unknown {
    const obj: any = {};
    if (message.outletId !== "") {
      obj.outletId = message.outletId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create(base?: DeepPartial<RegisterCreateRequest>): RegisterCreateRequest {
    return RegisterCreateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RegisterCreateRequest>): RegisterCreateRequest {
    const message = createBaseRegisterCreateRequest();
    message.outletId = object.outletId ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseRegisterCreateResponse(): RegisterCreateResponse {
  return { register: undefined };
}

export const RegisterCreateResponse: MessageFns<RegisterCreateResponse> = {
  encode(message: RegisterCreateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.register !== undefined) {
      Register.encode(message.register, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterCreateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.register = Register.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterCreateResponse {
    return { register: isSet(object.register) ? Register.fromJSON(object.register) : undefined };
  },

  toJSON(message: RegisterCreateResponse): unknown {
    const obj: any = {};
    if (message.register !== undefined) {
      obj.register = Register.toJSON(message.register);
    }
    return obj;
  },

  create(base?: DeepPartial<RegisterCreateResponse>): RegisterCreateResponse {
    return RegisterCreateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RegisterCreateResponse>): RegisterCreateResponse {
    const message = createBaseRegisterCreateResponse();
    message.register = (object.register !== undefined && object.register !== null)
      ? Register.fromPartial(object.register)
      : undefined;
    return message;
  },
};

function createBaseRegisterListRequest(): RegisterListRequest {
  return { outletId: "" };
}

export const RegisterListRequest: MessageFns<RegisterListRequest> = {
  encode(message: RegisterListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.outletId !== "") {
      writer.uint32(10).string(message.outletId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.outletId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterListRequest {
    return {
      outletId: isSet(object.outletId)
        ? globalThis.String(object.outletId)
        : isSet(object.outlet_id)
        ? globalThis.String(object.outlet_id)
        : "",
    };
  },

  toJSON(message: RegisterListRequest): unknown {
    const obj: any = {};
    if (message.outletId !== "") {
      obj.outletId = message.outletId;
    }
    return obj;
  },

  create(base?: DeepPartial<RegisterListRequest>): RegisterListRequest {
    return RegisterListRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RegisterListRequest>): RegisterListRequest {
    const message = createBaseRegisterListRequest();
    message.outletId = object.outletId ?? "";
    return message;
  },
};

function createBaseRegisterListResponse(): RegisterListResponse {
  return { registers: [] };
}

export const RegisterListResponse: MessageFns<RegisterListResponse> = {
  encode(message: RegisterListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.registers) {
      Register.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.registers.push(Register.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterListResponse {
    return {
      registers: globalThis.Array.isArray(object?.registers)
        ? object.registers.map((e: any) => Register.fromJSON(e))
        : [],
    };
  },

  toJSON(message: RegisterListResponse): unknown {
    const obj: any = {};
    if (message.registers?.length) {
      obj.registers = message.registers.map((e) => Register.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<RegisterListResponse>): RegisterListResponse {
    return RegisterListResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RegisterListResponse>): RegisterListResponse {
    const message = createBaseRegisterListResponse();
    message.registers = object.registers?.map((e) => Register.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRegisterDeleteRequest(): RegisterDeleteRequest {
  return { id: "" };
}

export const RegisterDeleteRequest: MessageFns<RegisterDeleteRequest> = {
  encode(message: RegisterDeleteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RegisterDeleteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRegisterDeleteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RegisterDeleteRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: RegisterDeleteRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<RegisterDeleteRequest>): RegisterDeleteRequest {
    return RegisterDeleteRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<RegisterDeleteRequest>): RegisterDeleteRequest {
    const message = createBaseRegisterDeleteRequest();
    message.id = object.id ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
