// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v3.19.1
// source: staff.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Staff } from "./common";

export const protobufPackage = "sakti.staff.v1";

export interface StaffCurrentRequest {
  merchantId: string;
}

export interface StaffCurrentResponse {
  claimed: boolean;
  reason: string;
  staff: Staff | undefined;
  hasStaff: boolean;
}

export interface StaffCreateRequest {
  merchantId: string;
  outletId: string;
  hasOutletId: boolean;
  name: string;
  pin: string;
  role: string;
}

export interface StaffCreateResponse {
  staff: Staff | undefined;
}

export interface StaffListRequest {
  merchantId: string;
}

export interface StaffListResponse {
  staff: Staff[];
}

export interface StaffUpdatePinRequest {
  id: string;
  pin: string;
}

export interface StaffUpdatePinResponse {
  staff: Staff | undefined;
}

export interface StaffDeleteRequest {
  id: string;
}

function createBaseStaffCurrentRequest(): StaffCurrentRequest {
  return { merchantId: "" };
}

export const StaffCurrentRequest: MessageFns<StaffCurrentRequest> = {
  encode(message: StaffCurrentRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.merchantId !== "") {
      writer.uint32(10).string(message.merchantId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StaffCurrentRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffCurrentRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchantId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StaffCurrentRequest {
    return {
      merchantId: isSet(object.merchantId)
        ? globalThis.String(object.merchantId)
        : isSet(object.merchant_id)
        ? globalThis.String(object.merchant_id)
        : "",
    };
  },

  toJSON(message: StaffCurrentRequest): unknown {
    const obj: any = {};
    if (message.merchantId !== "") {
      obj.merchantId = message.merchantId;
    }
    return obj;
  },

  create(base?: DeepPartial<StaffCurrentRequest>): StaffCurrentRequest {
    return StaffCurrentRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StaffCurrentRequest>): StaffCurrentRequest {
    const message = createBaseStaffCurrentRequest();
    message.merchantId = object.merchantId ?? "";
    return message;
  },
};

function createBaseStaffCurrentResponse(): StaffCurrentResponse {
  return { claimed: false, reason: "", staff: undefined, hasStaff: false };
}

export const StaffCurrentResponse: MessageFns<StaffCurrentResponse> = {
  encode(message: StaffCurrentResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.claimed !== false) {
      writer.uint32(8).bool(message.claimed);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    if (message.staff !== undefined) {
      Staff.encode(message.staff, writer.uint32(26).fork()).join();
    }
    if (message.hasStaff !== false) {
      writer.uint32(32).bool(message.hasStaff);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StaffCurrentResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffCurrentResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.claimed = reader.bool();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.staff = Staff.decode(reader, reader.uint32());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.hasStaff = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StaffCurrentResponse {
    return {
      claimed: isSet(object.claimed) ? globalThis.Boolean(object.claimed) : false,
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
      staff: isSet(object.staff) ? Staff.fromJSON(object.staff) : undefined,
      hasStaff: isSet(object.hasStaff)
        ? globalThis.Boolean(object.hasStaff)
        : isSet(object.has_staff)
        ? globalThis.Boolean(object.has_staff)
        : false,
    };
  },

  toJSON(message: StaffCurrentResponse): unknown {
    const obj: any = {};
    if (message.claimed !== false) {
      obj.claimed = message.claimed;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    if (message.staff !== undefined) {
      obj.staff = Staff.toJSON(message.staff);
    }
    if (message.hasStaff !== false) {
      obj.hasStaff = message.hasStaff;
    }
    return obj;
  },

  create(base?: DeepPartial<StaffCurrentResponse>): StaffCurrentResponse {
    return StaffCurrentResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StaffCurrentResponse>): StaffCurrentResponse {
    const message = createBaseStaffCurrentResponse();
    message.claimed = object.claimed ?? false;
    message.reason = object.reason ?? "";
    message.staff = (object.staff !== undefined && object.staff !== null) ? Staff.fromPartial(object.staff) : undefined;
    message.hasStaff = object.hasStaff ?? false;
    return message;
  },
};

function createBaseStaffCreateRequest(): StaffCreateRequest {
  return { merchantId: "", outletId: "", hasOutletId: false, name: "", pin: "", role: "" };
}

export const StaffCreateRequest: MessageFns<StaffCreateRequest> = {
  encode(message: StaffCreateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.merchantId !== "") {
      writer.uint32(10).string(message.merchantId);
    }
    if (message.outletId !== "") {
      writer.uint32(18).string(message.outletId);
    }
    if (message.hasOutletId !== false) {
      writer.uint32(24).bool(message.hasOutletId);
    }
    if (message.name !== "") {
      writer.uint32(34).string(message.name);
    }
    if (message.pin !== "") {
      writer.uint32(42).string(message.pin);
    }
    if (message.role !== "") {
      writer.uint32(50).string(message.role);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StaffCreateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffCreateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchantId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.outletId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.hasOutletId = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.pin = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.role = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StaffCreateRequest {
    return {
      merchantId: isSet(object.merchantId)
        ? globalThis.String(object.merchantId)
        : isSet(object.merchant_id)
        ? globalThis.String(object.merchant_id)
        : "",
      outletId: isSet(object.outletId)
        ? globalThis.String(object.outletId)
        : isSet(object.outlet_id)
        ? globalThis.String(object.outlet_id)
        : "",
      hasOutletId: isSet(object.hasOutletId)
        ? globalThis.Boolean(object.hasOutletId)
        : isSet(object.has_outlet_id)
        ? globalThis.Boolean(object.has_outlet_id)
        : false,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      pin: isSet(object.pin) ? globalThis.String(object.pin) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
    };
  },

  toJSON(message: StaffCreateRequest): unknown {
    const obj: any = {};
    if (message.merchantId !== "") {
      obj.merchantId = message.merchantId;
    }
    if (message.outletId !== "") {
      obj.outletId = message.outletId;
    }
    if (message.hasOutletId !== false) {
      obj.hasOutletId = message.hasOutletId;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.pin !== "") {
      obj.pin = message.pin;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    return obj;
  },

  create(base?: DeepPartial<StaffCreateRequest>): StaffCreateRequest {
    return StaffCreateRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StaffCreateRequest>): StaffCreateRequest {
    const message = createBaseStaffCreateRequest();
    message.merchantId = object.merchantId ?? "";
    message.outletId = object.outletId ?? "";
    message.hasOutletId = object.hasOutletId ?? false;
    message.name = object.name ?? "";
    message.pin = object.pin ?? "";
    message.role = object.role ?? "";
    return message;
  },
};

function createBaseStaffCreateResponse(): StaffCreateResponse {
  return { staff: undefined };
}

export const StaffCreateResponse: MessageFns<StaffCreateResponse> = {
  encode(message: StaffCreateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.staff !== undefined) {
      Staff.encode(message.staff, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StaffCreateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffCreateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.staff = Staff.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StaffCreateResponse {
    return { staff: isSet(object.staff) ? Staff.fromJSON(object.staff) : undefined };
  },

  toJSON(message: StaffCreateResponse): unknown {
    const obj: any = {};
    if (message.staff !== undefined) {
      obj.staff = Staff.toJSON(message.staff);
    }
    return obj;
  },

  create(base?: DeepPartial<StaffCreateResponse>): StaffCreateResponse {
    return StaffCreateResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StaffCreateResponse>): StaffCreateResponse {
    const message = createBaseStaffCreateResponse();
    message.staff = (object.staff !== undefined && object.staff !== null) ? Staff.fromPartial(object.staff) : undefined;
    return message;
  },
};

function createBaseStaffListRequest(): StaffListRequest {
  return { merchantId: "" };
}

export const StaffListRequest: MessageFns<StaffListRequest> = {
  encode(message: StaffListRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.merchantId !== "") {
      writer.uint32(10).string(message.merchantId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StaffListRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffListRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.merchantId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StaffListRequest {
    return {
      merchantId: isSet(object.merchantId)
        ? globalThis.String(object.merchantId)
        : isSet(object.merchant_id)
        ? globalThis.String(object.merchant_id)
        : "",
    };
  },

  toJSON(message: StaffListRequest): unknown {
    const obj: any = {};
    if (message.merchantId !== "") {
      obj.merchantId = message.merchantId;
    }
    return obj;
  },

  create(base?: DeepPartial<StaffListRequest>): StaffListRequest {
    return StaffListRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StaffListRequest>): StaffListRequest {
    const message = createBaseStaffListRequest();
    message.merchantId = object.merchantId ?? "";
    return message;
  },
};

function createBaseStaffListResponse(): StaffListResponse {
  return { staff: [] };
}

export const StaffListResponse: MessageFns<StaffListResponse> = {
  encode(message: StaffListResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.staff) {
      Staff.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StaffListResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffListResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.staff.push(Staff.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StaffListResponse {
    return { staff: globalThis.Array.isArray(object?.staff) ? object.staff.map((e: any) => Staff.fromJSON(e)) : [] };
  },

  toJSON(message: StaffListResponse): unknown {
    const obj: any = {};
    if (message.staff?.length) {
      obj.staff = message.staff.map((e) => Staff.toJSON(e));
    }
    return obj;
  },

  create(base?: DeepPartial<StaffListResponse>): StaffListResponse {
    return StaffListResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StaffListResponse>): StaffListResponse {
    const message = createBaseStaffListResponse();
    message.staff = object.staff?.map((e) => Staff.fromPartial(e)) || [];
    return message;
  },
};

function createBaseStaffUpdatePinRequest(): StaffUpdatePinRequest {
  return { id: "", pin: "" };
}

export const StaffUpdatePinRequest: MessageFns<StaffUpdatePinRequest> = {
  encode(message: StaffUpdatePinRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.pin !== "") {
      writer.uint32(18).string(message.pin);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StaffUpdatePinRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffUpdatePinRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pin = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StaffUpdatePinRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      pin: isSet(object.pin) ? globalThis.String(object.pin) : "",
    };
  },

  toJSON(message: StaffUpdatePinRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.pin !== "") {
      obj.pin = message.pin;
    }
    return obj;
  },

  create(base?: DeepPartial<StaffUpdatePinRequest>): StaffUpdatePinRequest {
    return StaffUpdatePinRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StaffUpdatePinRequest>): StaffUpdatePinRequest {
    const message = createBaseStaffUpdatePinRequest();
    message.id = object.id ?? "";
    message.pin = object.pin ?? "";
    return message;
  },
};

function createBaseStaffUpdatePinResponse(): StaffUpdatePinResponse {
  return { staff: undefined };
}

export const StaffUpdatePinResponse: MessageFns<StaffUpdatePinResponse> = {
  encode(message: StaffUpdatePinResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.staff !== undefined) {
      Staff.encode(message.staff, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StaffUpdatePinResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffUpdatePinResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.staff = Staff.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StaffUpdatePinResponse {
    return { staff: isSet(object.staff) ? Staff.fromJSON(object.staff) : undefined };
  },

  toJSON(message: StaffUpdatePinResponse): unknown {
    const obj: any = {};
    if (message.staff !== undefined) {
      obj.staff = Staff.toJSON(message.staff);
    }
    return obj;
  },

  create(base?: DeepPartial<StaffUpdatePinResponse>): StaffUpdatePinResponse {
    return StaffUpdatePinResponse.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StaffUpdatePinResponse>): StaffUpdatePinResponse {
    const message = createBaseStaffUpdatePinResponse();
    message.staff = (object.staff !== undefined && object.staff !== null) ? Staff.fromPartial(object.staff) : undefined;
    return message;
  },
};

function createBaseStaffDeleteRequest(): StaffDeleteRequest {
  return { id: "" };
}

export const StaffDeleteRequest: MessageFns<StaffDeleteRequest> = {
  encode(message: StaffDeleteRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): StaffDeleteRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseStaffDeleteRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): StaffDeleteRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: StaffDeleteRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create(base?: DeepPartial<StaffDeleteRequest>): StaffDeleteRequest {
    return StaffDeleteRequest.fromPartial(base ?? {});
  },
  fromPartial(object: DeepPartial<StaffDeleteRequest>): StaffDeleteRequest {
    const message = createBaseStaffDeleteRequest();
    message.id = object.id ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | bigint | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create(base?: DeepPartial<T>): T;
  fromPartial(object: DeepPartial<T>): T;
}
