// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by @repo/sync-proto-generator.

const INTEGER_STRING_PATTERN = /^-?\d+$/;

function int64Field(value: unknown, fieldName: string): bigint {
  if (typeof value === "bigint") return value;
  if (typeof value === "number" && Number.isSafeInteger(value)) return BigInt(value);
  if (typeof value === "string" && INTEGER_STRING_PATTERN.test(value)) return BigInt(value);
  if (value == null) return 0n;
  throw new Error("Invalid int64 value for " + fieldName);
}

function stringField(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function boolField(value: unknown): boolean {
  return value === true || value === 1;
}

function coerceBigInt(value: number | bigint): bigint {
  return typeof value === "bigint" ? value : BigInt(value);
}

function assets_row_to_proto(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    merchantId: stringField(row.merchantId),
    objectKey: stringField(row.objectKey),
    originalFilename: stringField(row.originalFilename),
    contentType: stringField(row.contentType),
    byteSize: int64Field(row.byteSize, "assets.byteSize"),
    contentHash: stringField(row.contentHash),
    kind: stringField(row.kind),
    width: int64Field(row.width, "assets.width"),
    height: int64Field(row.height, "assets.height"),
    status: stringField(row.status),
    createdByUserId: stringField(row.createdByUserId),
    deletedAt: stringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

function categories_row_to_proto(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    merchantId: stringField(row.merchantId),
    name: stringField(row.name),
    sortOrder: int64Field(row.sortOrder, "categories.sortOrder"),
    isActive: boolField(row.isActive),
    deletedAt: stringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

function merchants_row_to_proto(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    name: stringField(row.name),
    deletedAt: stringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

function order_items_row_to_proto(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    orderId: stringField(row.orderId),
    outletId: stringField(row.outletId),
    productId: stringField(row.productId),
    productName: stringField(row.productName),
    quantity: int64Field(row.quantity, "order_items.quantity"),
    unitPriceMinorUnits: int64Field(row.unitPriceMinorUnits, "order_items.unitPriceMinorUnits"),
    originalPriceMinorUnits: int64Field(row.originalPriceMinorUnits, "order_items.originalPriceMinorUnits"),
    subtotalMinorUnits: int64Field(row.subtotalMinorUnits, "order_items.subtotalMinorUnits"),
    updatedAt: stringField(row.updatedAt),
    deletedAt: stringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
  };
}

function orders_row_to_proto(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    outletId: stringField(row.outletId),
    registerId: stringField(row.registerId),
    staffId: stringField(row.staffId),
    orderNumber: stringField(row.orderNumber),
    totalMinorUnits: int64Field(row.totalMinorUnits, "orders.totalMinorUnits"),
    paymentMethod: stringField(row.paymentMethod),
    amountPaidMinorUnits: int64Field(row.amountPaidMinorUnits, "orders.amountPaidMinorUnits"),
    changeAmountMinorUnits: int64Field(row.changeAmountMinorUnits, "orders.changeAmountMinorUnits"),
    status: stringField(row.status),
    deletedAt: stringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

function outlet_products_row_to_proto(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    outletId: stringField(row.outletId),
    productId: stringField(row.productId),
    priceMinorUnits: int64Field(row.priceMinorUnits, "outlet_products.priceMinorUnits"),
    isAvailable: boolField(row.isAvailable),
    sortOrder: int64Field(row.sortOrder, "outlet_products.sortOrder"),
    deletedAt: stringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

function outlets_row_to_proto(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    merchantId: stringField(row.merchantId),
    timezone: stringField(row.timezone),
    name: stringField(row.name),
    address: stringField(row.address),
    receiptName: stringField(row.receiptName),
    receiptAddress: stringField(row.receiptAddress),
    isActive: boolField(row.isActive),
    deletedAt: stringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

function products_row_to_proto(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    merchantId: stringField(row.merchantId),
    categoryId: stringField(row.categoryId),
    name: stringField(row.name),
    priceMinorUnits: int64Field(row.priceMinorUnits, "products.priceMinorUnits"),
    imageUrl: stringField(row.imageUrl),
    imageAssetId: stringField(row.imageAssetId),
    isActive: boolField(row.isActive),
    sortOrder: int64Field(row.sortOrder, "products.sortOrder"),
    deletedAt: stringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

function registers_row_to_proto(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    outletId: stringField(row.outletId),
    name: stringField(row.name),
    shortId: stringField(row.shortId),
    pairingCode: stringField(row.pairingCode),
    pairingExpiresAt: stringField(row.pairingExpiresAt),
    isActive: boolField(row.isActive),
    lastSeenAt: stringField(row.lastSeenAt),
    deletedAt: stringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

function staff_row_to_proto(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    merchantId: stringField(row.merchantId),
    cloudUserId: stringField(row.cloudUserId),
    outletId: stringField(row.outletId),
    name: stringField(row.name),
    pin: stringField(row.pin),
    role: stringField(row.role),
    isActive: boolField(row.isActive),
    deletedAt: stringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

function mapTableChanges<Row>(
  changes: { changedRows: Record<string, unknown>[]; deletedIds: string[] } | undefined,
  mapper: (row: Record<string, unknown>) => Row
): { changedRows: Row[]; deletedIds: string[] } | undefined {
  if (!changes) return;
  return {
    changedRows: changes.changedRows.map(mapper),
    deletedIds: changes.deletedIds,
  };
}

export function decodeGeneratedPushBatchRequest(request: Record<string, any>) {
  const changes: Record<string, { changedRows: Record<string, unknown>[]; deletedIds: string[] }> = {};

  if (request.assets) {
    changes.assets = {
      changedRows: request.assets.changedRows.map((row: any) => ({ ...row })),
      deletedIds: request.assets.deletedIds,
    };
  }

  if (request.categories) {
    changes.categories = {
      changedRows: request.categories.changedRows.map((row: any) => ({ ...row })),
      deletedIds: request.categories.deletedIds,
    };
  }

  if (request.merchants) {
    changes.merchants = {
      changedRows: request.merchants.changedRows.map((row: any) => ({ ...row })),
      deletedIds: request.merchants.deletedIds,
    };
  }

  if (request.order_items) {
    changes.order_items = {
      changedRows: request.order_items.changedRows.map((row: any) => ({ ...row })),
      deletedIds: request.order_items.deletedIds,
    };
  }

  if (request.orders) {
    changes.orders = {
      changedRows: request.orders.changedRows.map((row: any) => ({ ...row })),
      deletedIds: request.orders.deletedIds,
    };
  }

  if (request.outlet_products) {
    changes.outlet_products = {
      changedRows: request.outlet_products.changedRows.map((row: any) => ({ ...row })),
      deletedIds: request.outlet_products.deletedIds,
    };
  }

  if (request.outlets) {
    changes.outlets = {
      changedRows: request.outlets.changedRows.map((row: any) => ({ ...row })),
      deletedIds: request.outlets.deletedIds,
    };
  }

  if (request.products) {
    changes.products = {
      changedRows: request.products.changedRows.map((row: any) => ({ ...row })),
      deletedIds: request.products.deletedIds,
    };
  }

  if (request.registers) {
    changes.registers = {
      changedRows: request.registers.changedRows.map((row: any) => ({ ...row })),
      deletedIds: request.registers.deletedIds,
    };
  }

  if (request.staff) {
    changes.staff = {
      changedRows: request.staff.changedRows.map((row: any) => ({ ...row })),
      deletedIds: request.staff.deletedIds,
    };
  }

  return changes;
}

export function encodeGeneratedPullBatchResponse(result: Record<string, any>) {
  return {
    assets: mapTableChanges(result.assets, assets_row_to_proto),
    categories: mapTableChanges(result.categories, categories_row_to_proto),
    merchants: mapTableChanges(result.merchants, merchants_row_to_proto),
    order_items: mapTableChanges(result.order_items, order_items_row_to_proto),
    orders: mapTableChanges(result.orders, orders_row_to_proto),
    outlet_products: mapTableChanges(result.outlet_products, outlet_products_row_to_proto),
    outlets: mapTableChanges(result.outlets, outlets_row_to_proto),
    products: mapTableChanges(result.products, products_row_to_proto),
    registers: mapTableChanges(result.registers, registers_row_to_proto),
    staff: mapTableChanges(result.staff, staff_row_to_proto),
    hasMore: result.hasMore ?? false,
    cursor: result.cursor ?? "",
    serverTime: result.serverTime,
  };
}
