// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by @repo/sync-proto-generator.

import { merchants, assets, categories, outlets, registers, staff, orders, orderItems, products, outletProducts } from "@repo/database/api-synced-schema";
import { inArray, sql } from "drizzle-orm";
import { protobufInt64ToSafeNumber } from "./protobuf";

const SQLITE_BIND_LIMIT = 999;
const INTEGER_STRING_PATTERN = /^-?\d+$/;

import type { SQLiteTable } from "drizzle-orm/sqlite-core";

export type TransactionLike = {
  insert: <TTable extends SQLiteTable>(table: TTable) => {
    values: (rows: Record<string, unknown>[]) => {
      onConflictDoUpdate: (input: { set: Record<string, unknown>; target: unknown }) => Promise<unknown> | unknown;
    };
  };
  select: <TSelection extends Record<string, unknown>>(fields: TSelection) => {
    from: (table: SQLiteTable) => {
      where: (condition: unknown) => unknown;
    };
  };
  update: <TTable extends SQLiteTable>(table: TTable) => {
    set: (values: Record<string, unknown>) => {
      where: (condition: unknown) => unknown;
    };
  };
  delete: <TTable extends SQLiteTable>(table: TTable) => {
    where: (condition: unknown) => Promise<unknown> | unknown;
  };
};

export interface GenericSyncTableAdapter {
  deleteRows(tx: TransactionLike, ids: string[]): Promise<void>;
  mapProtoRow(row: Record<string, unknown>): Record<string, unknown>;
  tableName: string;
  upsertRows(tx: TransactionLike, rows: Record<string, unknown>[]): Promise<void>;
  writeColumnCount: number;
}

function chunkRows<T>(rows: T[], chunkSize: number): T[][] {
  const chunks: T[][] = [];
  if (chunkSize <= 0) return chunks;
  for (let index = 0; index < rows.length; index += chunkSize) {
    chunks.push(rows.slice(index, index + chunkSize));
  }
  return chunks;
}

function getWriteChunkSize(writeColumnCount: number): number {
  return Math.max(1, Math.floor(SQLITE_BIND_LIMIT / writeColumnCount));
}

function boolField(value: unknown): boolean {
  return value === true || value === 1;
}

function nullableStringField(value: unknown): string | null {
  if (value == null) return null;
  return typeof value === "string" && value.length > 0 ? value : null;
}

function stringField(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function nullableInt64NumberField(value: unknown, fieldName: string): number | null {
  if (value == null || value === "") return null;
  return requiredInt64NumberField(value, fieldName);
}

function requiredInt64NumberField(value: unknown, fieldName: string): number {
  if (typeof value === "bigint") return protobufInt64ToSafeNumber(value, fieldName);
  if (typeof value === "number" && Number.isSafeInteger(value)) return value;
  if (typeof value === "string" && INTEGER_STRING_PATTERN.test(value)) return protobufInt64ToSafeNumber(BigInt(value), fieldName);
  return 0;
}

async function deleteRowsByAdapter(
  tx: TransactionLike,
  table: SQLiteTable,
  ids: string[]
): Promise<void> {
  if (ids.length === 0) return;
  const chunkSize = getWriteChunkSize(1);
  const idColumn = (table as unknown as { id: never }).id;
  for (const chunk of chunkRows(ids, chunkSize)) {
    await tx.delete(table).where(inArray(idColumn, chunk));
  }
}

function merchants_map_proto_row(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    name: stringField(row.name),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

async function merchants_upsert_rows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  if (rows.length === 0) return;
  const chunkSize = getWriteChunkSize(6);
  for (const chunk of chunkRows(rows, chunkSize)) {
    await tx.insert(
      merchants
    ).values(chunk).onConflictDoUpdate({
      target: merchants.id,
      set: {
      name: sql.raw("excluded.name"),
      deletedAt: sql.raw("excluded.deleted_at"),
      createdAt: sql.raw("excluded.created_at"),
      updatedAt: sql.raw("excluded.updated_at"),
      syncUpdatedAt: sql.raw("excluded.sync_updated_at"),
      },
    });
  }
}

async function merchants_delete_rows(tx: TransactionLike, ids: string[]) {
  return deleteRowsByAdapter(tx, merchants, ids);
}

function merchants_sync_table_adapter() {
  return {
    deleteRows: merchants_delete_rows,
    mapProtoRow: merchants_map_proto_row,
    tableName: "merchants",
    upsertRows: merchants_upsert_rows,
    writeColumnCount: 6,
  } as const;
}

function assets_map_proto_row(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    merchantId: stringField(row.merchantId),
    objectKey: stringField(row.objectKey),
    originalFilename: nullableStringField(row.originalFilename),
    contentType: stringField(row.contentType),
    byteSize: requiredInt64NumberField(row.byteSize, "assets.byteSize"),
    contentHash: stringField(row.contentHash),
    kind: stringField(row.kind),
    width: nullableInt64NumberField(row.width, "assets.width"),
    height: nullableInt64NumberField(row.height, "assets.height"),
    status: stringField(row.status),
    createdByUserId: nullableStringField(row.createdByUserId),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

async function assets_upsert_rows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  if (rows.length === 0) return;
  const chunkSize = getWriteChunkSize(16);
  for (const chunk of chunkRows(rows, chunkSize)) {
    await tx.insert(
      assets
    ).values(chunk).onConflictDoUpdate({
      target: assets.id,
      set: {
      merchantId: sql.raw("excluded.merchant_id"),
      objectKey: sql.raw("excluded.object_key"),
      originalFilename: sql.raw("excluded.original_filename"),
      contentType: sql.raw("excluded.content_type"),
      byteSize: sql.raw("excluded.byte_size"),
      contentHash: sql.raw("excluded.content_hash"),
      kind: sql.raw("excluded.kind"),
      width: sql.raw("excluded.width"),
      height: sql.raw("excluded.height"),
      status: sql.raw("excluded.status"),
      createdByUserId: sql.raw("excluded.created_by_user_id"),
      deletedAt: sql.raw("excluded.deleted_at"),
      createdAt: sql.raw("excluded.created_at"),
      updatedAt: sql.raw("excluded.updated_at"),
      syncUpdatedAt: sql.raw("excluded.sync_updated_at"),
      },
    });
  }
}

async function assets_delete_rows(tx: TransactionLike, ids: string[]) {
  return deleteRowsByAdapter(tx, assets, ids);
}

function assets_sync_table_adapter() {
  return {
    deleteRows: assets_delete_rows,
    mapProtoRow: assets_map_proto_row,
    tableName: "assets",
    upsertRows: assets_upsert_rows,
    writeColumnCount: 16,
  } as const;
}

function categories_map_proto_row(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    merchantId: stringField(row.merchantId),
    name: stringField(row.name),
    sortOrder: requiredInt64NumberField(row.sortOrder, "categories.sortOrder"),
    isActive: boolField(row.isActive),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

async function categories_upsert_rows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  if (rows.length === 0) return;
  const chunkSize = getWriteChunkSize(9);
  for (const chunk of chunkRows(rows, chunkSize)) {
    await tx.insert(
      categories
    ).values(chunk).onConflictDoUpdate({
      target: categories.id,
      set: {
      merchantId: sql.raw("excluded.merchant_id"),
      name: sql.raw("excluded.name"),
      sortOrder: sql.raw("excluded.sort_order"),
      isActive: sql.raw("excluded.is_active"),
      deletedAt: sql.raw("excluded.deleted_at"),
      createdAt: sql.raw("excluded.created_at"),
      updatedAt: sql.raw("excluded.updated_at"),
      syncUpdatedAt: sql.raw("excluded.sync_updated_at"),
      },
    });
  }
}

async function categories_delete_rows(tx: TransactionLike, ids: string[]) {
  return deleteRowsByAdapter(tx, categories, ids);
}

function categories_sync_table_adapter() {
  return {
    deleteRows: categories_delete_rows,
    mapProtoRow: categories_map_proto_row,
    tableName: "categories",
    upsertRows: categories_upsert_rows,
    writeColumnCount: 9,
  } as const;
}

function outlets_map_proto_row(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    merchantId: stringField(row.merchantId),
    timezone: stringField(row.timezone),
    name: stringField(row.name),
    address: nullableStringField(row.address),
    receiptName: nullableStringField(row.receiptName),
    receiptAddress: nullableStringField(row.receiptAddress),
    isActive: boolField(row.isActive),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

async function outlets_upsert_rows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  if (rows.length === 0) return;
  const chunkSize = getWriteChunkSize(12);
  for (const chunk of chunkRows(rows, chunkSize)) {
    await tx.insert(
      outlets
    ).values(chunk).onConflictDoUpdate({
      target: outlets.id,
      set: {
      merchantId: sql.raw("excluded.merchant_id"),
      timezone: sql.raw("excluded.timezone"),
      name: sql.raw("excluded.name"),
      address: sql.raw("excluded.address"),
      receiptName: sql.raw("excluded.receipt_name"),
      receiptAddress: sql.raw("excluded.receipt_address"),
      isActive: sql.raw("excluded.is_active"),
      deletedAt: sql.raw("excluded.deleted_at"),
      createdAt: sql.raw("excluded.created_at"),
      updatedAt: sql.raw("excluded.updated_at"),
      syncUpdatedAt: sql.raw("excluded.sync_updated_at"),
      },
    });
  }
}

async function outlets_delete_rows(tx: TransactionLike, ids: string[]) {
  return deleteRowsByAdapter(tx, outlets, ids);
}

function outlets_sync_table_adapter() {
  return {
    deleteRows: outlets_delete_rows,
    mapProtoRow: outlets_map_proto_row,
    tableName: "outlets",
    upsertRows: outlets_upsert_rows,
    writeColumnCount: 12,
  } as const;
}

function registers_map_proto_row(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    outletId: stringField(row.outletId),
    name: stringField(row.name),
    shortId: stringField(row.shortId),
    pairingCode: nullableStringField(row.pairingCode),
    pairingExpiresAt: nullableStringField(row.pairingExpiresAt),
    isActive: boolField(row.isActive),
    lastSeenAt: nullableStringField(row.lastSeenAt),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

async function registers_upsert_rows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  if (rows.length === 0) return;
  const chunkSize = getWriteChunkSize(12);
  for (const chunk of chunkRows(rows, chunkSize)) {
    await tx.insert(
      registers
    ).values(chunk).onConflictDoUpdate({
      target: registers.id,
      set: {
      outletId: sql.raw("excluded.outlet_id"),
      name: sql.raw("excluded.name"),
      shortId: sql.raw("excluded.short_id"),
      pairingCode: sql.raw("excluded.pairing_code"),
      pairingExpiresAt: sql.raw("excluded.pairing_expires_at"),
      isActive: sql.raw("excluded.is_active"),
      lastSeenAt: sql.raw("excluded.last_seen_at"),
      deletedAt: sql.raw("excluded.deleted_at"),
      createdAt: sql.raw("excluded.created_at"),
      updatedAt: sql.raw("excluded.updated_at"),
      syncUpdatedAt: sql.raw("excluded.sync_updated_at"),
      },
    });
  }
}

async function registers_delete_rows(tx: TransactionLike, ids: string[]) {
  return deleteRowsByAdapter(tx, registers, ids);
}

function registers_sync_table_adapter() {
  return {
    deleteRows: registers_delete_rows,
    mapProtoRow: registers_map_proto_row,
    tableName: "registers",
    upsertRows: registers_upsert_rows,
    writeColumnCount: 12,
  } as const;
}

function staff_map_proto_row(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    merchantId: stringField(row.merchantId),
    cloudUserId: nullableStringField(row.cloudUserId),
    outletId: nullableStringField(row.outletId),
    name: stringField(row.name),
    pin: nullableStringField(row.pin),
    role: stringField(row.role),
    isActive: boolField(row.isActive),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

async function staff_upsert_rows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  if (rows.length === 0) return;
  const chunkSize = getWriteChunkSize(12);
  for (const chunk of chunkRows(rows, chunkSize)) {
    await tx.insert(
      staff
    ).values(chunk).onConflictDoUpdate({
      target: staff.id,
      set: {
      merchantId: sql.raw("excluded.merchant_id"),
      cloudUserId: sql.raw("excluded.cloud_user_id"),
      outletId: sql.raw("excluded.outlet_id"),
      name: sql.raw("excluded.name"),
      pin: sql.raw("excluded.pin"),
      role: sql.raw("excluded.role"),
      isActive: sql.raw("excluded.is_active"),
      deletedAt: sql.raw("excluded.deleted_at"),
      createdAt: sql.raw("excluded.created_at"),
      updatedAt: sql.raw("excluded.updated_at"),
      syncUpdatedAt: sql.raw("excluded.sync_updated_at"),
      },
    });
  }
}

async function staff_delete_rows(tx: TransactionLike, ids: string[]) {
  return deleteRowsByAdapter(tx, staff, ids);
}

function staff_sync_table_adapter() {
  return {
    deleteRows: staff_delete_rows,
    mapProtoRow: staff_map_proto_row,
    tableName: "staff",
    upsertRows: staff_upsert_rows,
    writeColumnCount: 12,
  } as const;
}

function orders_map_proto_row(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    outletId: stringField(row.outletId),
    registerId: nullableStringField(row.registerId),
    staffId: nullableStringField(row.staffId),
    orderNumber: stringField(row.orderNumber),
    totalMinorUnits: requiredInt64NumberField(row.totalMinorUnits, "orders.totalMinorUnits"),
    paymentMethod: stringField(row.paymentMethod),
    amountPaidMinorUnits: nullableInt64NumberField(row.amountPaidMinorUnits, "orders.amountPaidMinorUnits"),
    changeAmountMinorUnits: nullableInt64NumberField(row.changeAmountMinorUnits, "orders.changeAmountMinorUnits"),
    status: stringField(row.status),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

async function orders_upsert_rows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  if (rows.length === 0) return;
  const chunkSize = getWriteChunkSize(14);
  for (const chunk of chunkRows(rows, chunkSize)) {
    await tx.insert(
      orders
    ).values(chunk).onConflictDoUpdate({
      target: orders.id,
      set: {
      outletId: sql.raw("excluded.outlet_id"),
      registerId: sql.raw("excluded.register_id"),
      staffId: sql.raw("excluded.staff_id"),
      orderNumber: sql.raw("excluded.order_number"),
      totalMinorUnits: sql.raw("excluded.total_minor_units"),
      paymentMethod: sql.raw("excluded.payment_method"),
      amountPaidMinorUnits: sql.raw("excluded.amount_paid_minor_units"),
      changeAmountMinorUnits: sql.raw("excluded.change_amount_minor_units"),
      status: sql.raw("excluded.status"),
      deletedAt: sql.raw("excluded.deleted_at"),
      createdAt: sql.raw("excluded.created_at"),
      updatedAt: sql.raw("excluded.updated_at"),
      syncUpdatedAt: sql.raw("excluded.sync_updated_at"),
      },
    });
  }
}

async function orders_delete_rows(tx: TransactionLike, ids: string[]) {
  return deleteRowsByAdapter(tx, orders, ids);
}

function orders_sync_table_adapter() {
  return {
    deleteRows: orders_delete_rows,
    mapProtoRow: orders_map_proto_row,
    tableName: "orders",
    upsertRows: orders_upsert_rows,
    writeColumnCount: 14,
  } as const;
}

function order_items_map_proto_row(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    orderId: stringField(row.orderId),
    outletId: stringField(row.outletId),
    productId: nullableStringField(row.productId),
    productName: stringField(row.productName),
    quantity: requiredInt64NumberField(row.quantity, "order_items.quantity"),
    unitPriceMinorUnits: requiredInt64NumberField(row.unitPriceMinorUnits, "order_items.unitPriceMinorUnits"),
    originalPriceMinorUnits: nullableInt64NumberField(row.originalPriceMinorUnits, "order_items.originalPriceMinorUnits"),
    subtotalMinorUnits: requiredInt64NumberField(row.subtotalMinorUnits, "order_items.subtotalMinorUnits"),
    updatedAt: stringField(row.updatedAt),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
  };
}

async function order_items_upsert_rows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  if (rows.length === 0) return;
  const chunkSize = getWriteChunkSize(13);
  for (const chunk of chunkRows(rows, chunkSize)) {
    await tx.insert(
      orderItems
    ).values(chunk).onConflictDoUpdate({
      target: orderItems.id,
      set: {
      orderId: sql.raw("excluded.order_id"),
      outletId: sql.raw("excluded.outlet_id"),
      productId: sql.raw("excluded.product_id"),
      productName: sql.raw("excluded.product_name"),
      quantity: sql.raw("excluded.quantity"),
      unitPriceMinorUnits: sql.raw("excluded.unit_price_minor_units"),
      originalPriceMinorUnits: sql.raw("excluded.original_price_minor_units"),
      subtotalMinorUnits: sql.raw("excluded.subtotal_minor_units"),
      updatedAt: sql.raw("excluded.updated_at"),
      deletedAt: sql.raw("excluded.deleted_at"),
      createdAt: sql.raw("excluded.created_at"),
      syncUpdatedAt: sql.raw("excluded.sync_updated_at"),
      },
    });
  }
}

async function order_items_delete_rows(tx: TransactionLike, ids: string[]) {
  return deleteRowsByAdapter(tx, orderItems, ids);
}

function order_items_sync_table_adapter() {
  return {
    deleteRows: order_items_delete_rows,
    mapProtoRow: order_items_map_proto_row,
    tableName: "order_items",
    upsertRows: order_items_upsert_rows,
    writeColumnCount: 13,
  } as const;
}

function products_map_proto_row(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    merchantId: stringField(row.merchantId),
    categoryId: nullableStringField(row.categoryId),
    name: stringField(row.name),
    priceMinorUnits: requiredInt64NumberField(row.priceMinorUnits, "products.priceMinorUnits"),
    imageUrl: nullableStringField(row.imageUrl),
    imageAssetId: nullableStringField(row.imageAssetId),
    isActive: boolField(row.isActive),
    sortOrder: requiredInt64NumberField(row.sortOrder, "products.sortOrder"),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

async function products_upsert_rows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  if (rows.length === 0) return;
  const chunkSize = getWriteChunkSize(13);
  for (const chunk of chunkRows(rows, chunkSize)) {
    await tx.insert(
      products
    ).values(chunk).onConflictDoUpdate({
      target: products.id,
      set: {
      merchantId: sql.raw("excluded.merchant_id"),
      categoryId: sql.raw("excluded.category_id"),
      name: sql.raw("excluded.name"),
      priceMinorUnits: sql.raw("excluded.price_minor_units"),
      imageUrl: sql.raw("excluded.image_url"),
      imageAssetId: sql.raw("excluded.image_asset_id"),
      isActive: sql.raw("excluded.is_active"),
      sortOrder: sql.raw("excluded.sort_order"),
      deletedAt: sql.raw("excluded.deleted_at"),
      createdAt: sql.raw("excluded.created_at"),
      updatedAt: sql.raw("excluded.updated_at"),
      syncUpdatedAt: sql.raw("excluded.sync_updated_at"),
      },
    });
  }
}

async function products_delete_rows(tx: TransactionLike, ids: string[]) {
  return deleteRowsByAdapter(tx, products, ids);
}

function products_sync_table_adapter() {
  return {
    deleteRows: products_delete_rows,
    mapProtoRow: products_map_proto_row,
    tableName: "products",
    upsertRows: products_upsert_rows,
    writeColumnCount: 13,
  } as const;
}

function outlet_products_map_proto_row(row: Record<string, unknown>) {
  return {
    id: stringField(row.id),
    outletId: stringField(row.outletId),
    productId: stringField(row.productId),
    priceMinorUnits: nullableInt64NumberField(row.priceMinorUnits, "outlet_products.priceMinorUnits"),
    isAvailable: boolField(row.isAvailable),
    sortOrder: nullableInt64NumberField(row.sortOrder, "outlet_products.sortOrder"),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
}

async function outlet_products_upsert_rows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  if (rows.length === 0) return;
  const chunkSize = getWriteChunkSize(10);
  for (const chunk of chunkRows(rows, chunkSize)) {
    await tx.insert(
      outletProducts
    ).values(chunk).onConflictDoUpdate({
      target: outletProducts.id,
      set: {
      outletId: sql.raw("excluded.outlet_id"),
      productId: sql.raw("excluded.product_id"),
      priceMinorUnits: sql.raw("excluded.price_minor_units"),
      isAvailable: sql.raw("excluded.is_available"),
      sortOrder: sql.raw("excluded.sort_order"),
      deletedAt: sql.raw("excluded.deleted_at"),
      createdAt: sql.raw("excluded.created_at"),
      updatedAt: sql.raw("excluded.updated_at"),
      syncUpdatedAt: sql.raw("excluded.sync_updated_at"),
      },
    });
  }
}

async function outlet_products_delete_rows(tx: TransactionLike, ids: string[]) {
  return deleteRowsByAdapter(tx, outletProducts, ids);
}

function outlet_products_sync_table_adapter() {
  return {
    deleteRows: outlet_products_delete_rows,
    mapProtoRow: outlet_products_map_proto_row,
    tableName: "outlet_products",
    upsertRows: outlet_products_upsert_rows,
    writeColumnCount: 10,
  } as const;
}

export const SYNC_UPSERT_ORDER = ["merchants", "assets", "categories", "outlets", "registers", "staff", "orders", "order_items", "products", "outlet_products"] as const;
export const SYNC_DELETE_ORDER = ["outlet_products", "products", "order_items", "orders", "staff", "registers", "outlets", "categories", "assets", "merchants"] as const;

export const PUSH_TABLE_ADAPTERS = [
  merchants_sync_table_adapter(),
  assets_sync_table_adapter(),
  categories_sync_table_adapter(),
  outlets_sync_table_adapter(),
  registers_sync_table_adapter(),
  staff_sync_table_adapter(),
  orders_sync_table_adapter(),
  order_items_sync_table_adapter(),
  products_sync_table_adapter(),
  outlet_products_sync_table_adapter(),
] as const;

export function getPushTableAdapter(tableName: string) {
  return PUSH_TABLE_ADAPTERS.find((adapter) => adapter.tableName === tableName);
}
