// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by @repo/sync-proto-generator.

import { assets, categories, merchants, orderItems, orders, outletProducts, outlets, products, registers, staff } from "@repo/database/api-schema";
import { inArray, sql } from "drizzle-orm";
import { protobufInt64ToSafeNumber } from "./protobuf";

const INTEGER_STRING_PATTERN = /^-?\d+$/;

import type { SQLiteTable } from "drizzle-orm/sqlite-core";

export type TransactionLike = {
  insert: <TTable extends SQLiteTable>(table: TTable) => {
    values: (rows: Record<string, unknown>[]) => {
      onConflictDoNothing: () => Promise<unknown> | unknown;
      onConflictDoUpdate: (input: { set: Record<string, unknown>; target: unknown }) => Promise<unknown> | unknown;
    };
  };
  select: <TFields extends Record<string, unknown>>(fields: TFields) => {
    from: <TTable extends SQLiteTable>(table: TTable) => {
      where: (condition: unknown) => Promise<unknown[]> | { limit: (value: number) => Promise<unknown[]> | unknown };
    };
  };
  update: <TTable extends SQLiteTable>(table: TTable) => {
    set: (patch: Record<string, unknown>) => {
      where: (condition: unknown) => Promise<unknown> | unknown;
    };
  };
};

export interface PushAdapterContext {
  merchantId: string;
  outletId: string;
}

export interface PushTableAdapter {
  readonly scope: "merchant" | "outlet";
  readonly serviceKey: string;
  readonly tableName: string;
  readonly writeColumnCount: number;
  mapRow(row: Record<string, unknown>, context: PushAdapterContext): Record<string, unknown>;
  selectExistingRows(tx: TransactionLike, ids: string[]): Promise<Record<string, unknown>[]>;
  upsertRows(tx: TransactionLike, rows: Record<string, unknown>[]): Promise<void>;
  softDeleteRows(tx: TransactionLike, ids: string[], now: string): Promise<void>;
}

function stringField(value: unknown): string {
  return typeof value === "string" ? value : "";
}

function nullableStringField(value: unknown): string | null {
  if (value == null) return null;
  if (typeof value === "string") return value.length === 0 ? null : value;
  return null;
}

function boolField(value: unknown): boolean {
  return value === true || value === 1;
}

function requiredInt64NumberField(value: unknown, fieldName: string): number {
  if (typeof value === "bigint") return protobufInt64ToSafeNumber(value, fieldName);
  if (typeof value === "number" && Number.isSafeInteger(value)) return value;
  if (typeof value === "string" && INTEGER_STRING_PATTERN.test(value)) return protobufInt64ToSafeNumber(BigInt(value), fieldName);
  return 0;
}

function nullableInt64NumberField(value: unknown, fieldName: string): number | null {
  if (value == null || value === "") return null;
  return requiredInt64NumberField(value, fieldName);
}

function applyContextOwnership(
  row: Record<string, unknown>,
  context: PushAdapterContext,
  ownershipColumn: "merchantId" | "outletId" | null
): Record<string, unknown> {
  if (!ownershipColumn) return row;
  return {
    ...row,
    [ownershipColumn]: ownershipColumn === "merchantId" ? context.merchantId : context.outletId,
  };
}

async function selectExistingRowsById(
  tx: TransactionLike,
  table: SQLiteTable,
  projection: Record<string, unknown>,
  ids: string[]
): Promise<Record<string, unknown>[]> {
  if (ids.length === 0) return [];
  const idColumn = (table as unknown as { id: never }).id;
  const rows = await resolveRowsLike(
    tx.select(projection).from(table).where(inArray(idColumn, ids)),
    ids.length
  );
  return Array.isArray(rows) ? rows as Record<string, unknown>[] : [];
}

async function resolveRowsLike(value: unknown, limit: number): Promise<unknown> {
  if (Array.isArray(value)) return value;
  if (typeof value === "object" && value !== null && "limit" in value && typeof (value as { limit: unknown }).limit === "function") {
    return await resolveRowsLike(await (value as { limit: (value: number) => unknown }).limit(limit), limit);
  }
  return await value;
}

async function upsertRowsByAdapter(
  tx: TransactionLike,
  table: SQLiteTable,
  set: Record<string, unknown>,
  rows: Record<string, unknown>[]
): Promise<void> {
  if (rows.length === 0) return;
  const idColumn = (table as unknown as { id: never }).id;
  await tx.insert(table).values(rows).onConflictDoUpdate({ set, target: idColumn });
}

async function softDeleteRowsByAdapter(
  tx: TransactionLike,
  table: SQLiteTable,
  ids: string[],
  now: string
): Promise<void> {
  if (ids.length === 0) return;
  const idColumn = (table as unknown as { id: never }).id;
  await tx.update(table).set({ deletedAt: now, updatedAt: now }).where(inArray(idColumn, ids));
}

function merchantsRowToInsertRow(row: Record<string, unknown>, context: PushAdapterContext) {
  const normalized = {
    id: stringField(row.id),
    name: stringField(row.name),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
  return applyContextOwnership(normalized, context, null);
}

function merchantsSelectExistingRows(tx: TransactionLike, ids: string[]) {
  return selectExistingRowsById(tx, merchants, { id: merchants.id, updatedAt: merchants.updatedAt }, ids);
}

function merchantsUpsertRows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  return upsertRowsByAdapter(tx, merchants, {
    name: sql.raw("excluded.name"),
    deletedAt: sql.raw("excluded.deleted_at"),
    createdAt: sql.raw("excluded.created_at"),
    updatedAt: sql.raw("excluded.updated_at"),
  }, rows);
}

function merchantsSoftDeleteRows(tx: TransactionLike, ids: string[], now: string) {
  return softDeleteRowsByAdapter(tx, merchants, ids, now);
}

function MerchantsPushTableAdapter() {
  return {
    mapRow: merchantsRowToInsertRow,
    scope: "merchant",
    selectExistingRows: merchantsSelectExistingRows,
    serviceKey: "merchants",
    softDeleteRows: merchantsSoftDeleteRows,
    tableName: "merchants",
    upsertRows: merchantsUpsertRows,
    writeColumnCount: 5,
  } as const;
}

function outletsRowToInsertRow(row: Record<string, unknown>, context: PushAdapterContext) {
  const normalized = {
    id: stringField(row.id),
    timezone: stringField(row.timezone),
    name: stringField(row.name),
    address: nullableStringField(row.address),
    receiptName: nullableStringField(row.receiptName),
    receiptAddress: nullableStringField(row.receiptAddress),
    isActive: boolField(row.isActive),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
  return applyContextOwnership(normalized, context, "merchantId");
}

function outletsSelectExistingRows(tx: TransactionLike, ids: string[]) {
  return selectExistingRowsById(tx, outlets, { id: outlets.id, updatedAt: outlets.updatedAt }, ids);
}

function outletsUpsertRows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  return upsertRowsByAdapter(tx, outlets, {
    merchantId: sql.raw("excluded.merchant_id"),
    timezone: sql.raw("excluded.timezone"),
    name: sql.raw("excluded.name"),
    address: sql.raw("excluded.address"),
    receiptName: sql.raw("excluded.receipt_name"),
    receiptAddress: sql.raw("excluded.receipt_address"),
    isActive: sql.raw("excluded.is_active"),
    deletedAt: sql.raw("excluded.deleted_at"),
    createdAt: sql.raw("excluded.created_at"),
    updatedAt: sql.raw("excluded.updated_at"),
  }, rows);
}

function outletsSoftDeleteRows(tx: TransactionLike, ids: string[], now: string) {
  return softDeleteRowsByAdapter(tx, outlets, ids, now);
}

function OutletsPushTableAdapter() {
  return {
    mapRow: outletsRowToInsertRow,
    scope: "merchant",
    selectExistingRows: outletsSelectExistingRows,
    serviceKey: "outlets",
    softDeleteRows: outletsSoftDeleteRows,
    tableName: "outlets",
    upsertRows: outletsUpsertRows,
    writeColumnCount: 11,
  } as const;
}

function registersRowToInsertRow(row: Record<string, unknown>, context: PushAdapterContext) {
  const normalized = {
    id: stringField(row.id),
    name: stringField(row.name),
    shortId: stringField(row.shortId),
    pairingCode: nullableStringField(row.pairingCode),
    pairingExpiresAt: nullableStringField(row.pairingExpiresAt),
    isActive: boolField(row.isActive),
    lastSeenAt: nullableStringField(row.lastSeenAt),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
  return applyContextOwnership(normalized, context, "outletId");
}

function registersSelectExistingRows(tx: TransactionLike, ids: string[]) {
  return selectExistingRowsById(tx, registers, { id: registers.id, updatedAt: registers.updatedAt }, ids);
}

function registersUpsertRows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  return upsertRowsByAdapter(tx, registers, {
    outletId: sql.raw("excluded.outlet_id"),
    name: sql.raw("excluded.name"),
    shortId: sql.raw("excluded.short_id"),
    pairingCode: sql.raw("excluded.pairing_code"),
    pairingExpiresAt: sql.raw("excluded.pairing_expires_at"),
    isActive: sql.raw("excluded.is_active"),
    lastSeenAt: sql.raw("excluded.last_seen_at"),
    deletedAt: sql.raw("excluded.deleted_at"),
    createdAt: sql.raw("excluded.created_at"),
    updatedAt: sql.raw("excluded.updated_at"),
  }, rows);
}

function registersSoftDeleteRows(tx: TransactionLike, ids: string[], now: string) {
  return softDeleteRowsByAdapter(tx, registers, ids, now);
}

function RegistersPushTableAdapter() {
  return {
    mapRow: registersRowToInsertRow,
    scope: "outlet",
    selectExistingRows: registersSelectExistingRows,
    serviceKey: "registers",
    softDeleteRows: registersSoftDeleteRows,
    tableName: "registers",
    upsertRows: registersUpsertRows,
    writeColumnCount: 11,
  } as const;
}

function staffRowToInsertRow(row: Record<string, unknown>, context: PushAdapterContext) {
  const normalized = {
    id: stringField(row.id),
    cloudUserId: nullableStringField(row.cloudUserId),
    outletId: nullableStringField(row.outletId),
    name: stringField(row.name),
    pin: nullableStringField(row.pin),
    role: stringField(row.role),
    isActive: boolField(row.isActive),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
  return applyContextOwnership(normalized, context, "merchantId");
}

function staffSelectExistingRows(tx: TransactionLike, ids: string[]) {
  return selectExistingRowsById(tx, staff, { id: staff.id, updatedAt: staff.updatedAt }, ids);
}

function staffUpsertRows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  return upsertRowsByAdapter(tx, staff, {
    merchantId: sql.raw("excluded.merchant_id"),
    cloudUserId: sql.raw("excluded.cloud_user_id"),
    outletId: sql.raw("excluded.outlet_id"),
    name: sql.raw("excluded.name"),
    pin: sql.raw("excluded.pin"),
    role: sql.raw("excluded.role"),
    isActive: sql.raw("excluded.is_active"),
    deletedAt: sql.raw("excluded.deleted_at"),
    createdAt: sql.raw("excluded.created_at"),
    updatedAt: sql.raw("excluded.updated_at"),
  }, rows);
}

function staffSoftDeleteRows(tx: TransactionLike, ids: string[], now: string) {
  return softDeleteRowsByAdapter(tx, staff, ids, now);
}

function StaffPushTableAdapter() {
  return {
    mapRow: staffRowToInsertRow,
    scope: "merchant",
    selectExistingRows: staffSelectExistingRows,
    serviceKey: "staff",
    softDeleteRows: staffSoftDeleteRows,
    tableName: "staff",
    upsertRows: staffUpsertRows,
    writeColumnCount: 11,
  } as const;
}

function categoriesRowToInsertRow(row: Record<string, unknown>, context: PushAdapterContext) {
  const normalized = {
    id: stringField(row.id),
    name: stringField(row.name),
    sortOrder: requiredInt64NumberField(row.sortOrder, "categories.sortOrder"),
    isActive: boolField(row.isActive),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
  return applyContextOwnership(normalized, context, "merchantId");
}

function categoriesSelectExistingRows(tx: TransactionLike, ids: string[]) {
  return selectExistingRowsById(tx, categories, { id: categories.id, updatedAt: categories.updatedAt }, ids);
}

function categoriesUpsertRows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  return upsertRowsByAdapter(tx, categories, {
    merchantId: sql.raw("excluded.merchant_id"),
    name: sql.raw("excluded.name"),
    sortOrder: sql.raw("excluded.sort_order"),
    isActive: sql.raw("excluded.is_active"),
    deletedAt: sql.raw("excluded.deleted_at"),
    createdAt: sql.raw("excluded.created_at"),
    updatedAt: sql.raw("excluded.updated_at"),
  }, rows);
}

function categoriesSoftDeleteRows(tx: TransactionLike, ids: string[], now: string) {
  return softDeleteRowsByAdapter(tx, categories, ids, now);
}

function CategoriesPushTableAdapter() {
  return {
    mapRow: categoriesRowToInsertRow,
    scope: "merchant",
    selectExistingRows: categoriesSelectExistingRows,
    serviceKey: "categories",
    softDeleteRows: categoriesSoftDeleteRows,
    tableName: "categories",
    upsertRows: categoriesUpsertRows,
    writeColumnCount: 8,
  } as const;
}

function assetsRowToInsertRow(row: Record<string, unknown>, context: PushAdapterContext) {
  const normalized = {
    id: stringField(row.id),
    objectKey: stringField(row.objectKey),
    originalFilename: nullableStringField(row.originalFilename),
    contentType: stringField(row.contentType),
    byteSize: requiredInt64NumberField(row.byteSize, "assets.byteSize"),
    contentHash: stringField(row.contentHash),
    kind: stringField(row.kind),
    width: nullableInt64NumberField(row.width, "assets.width"),
    height: nullableInt64NumberField(row.height, "assets.height"),
    status: stringField(row.status),
    createdByUserId: nullableStringField(row.createdByUserId),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
  return applyContextOwnership(normalized, context, "merchantId");
}

function assetsSelectExistingRows(tx: TransactionLike, ids: string[]) {
  return selectExistingRowsById(tx, assets, { id: assets.id, updatedAt: assets.updatedAt }, ids);
}

function assetsUpsertRows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  return upsertRowsByAdapter(tx, assets, {
    merchantId: sql.raw("excluded.merchant_id"),
    objectKey: sql.raw("excluded.object_key"),
    originalFilename: sql.raw("excluded.original_filename"),
    contentType: sql.raw("excluded.content_type"),
    byteSize: sql.raw("excluded.byte_size"),
    contentHash: sql.raw("excluded.content_hash"),
    kind: sql.raw("excluded.kind"),
    width: sql.raw("excluded.width"),
    height: sql.raw("excluded.height"),
    status: sql.raw("excluded.status"),
    createdByUserId: sql.raw("excluded.created_by_user_id"),
    deletedAt: sql.raw("excluded.deleted_at"),
    createdAt: sql.raw("excluded.created_at"),
    updatedAt: sql.raw("excluded.updated_at"),
  }, rows);
}

function assetsSoftDeleteRows(tx: TransactionLike, ids: string[], now: string) {
  return softDeleteRowsByAdapter(tx, assets, ids, now);
}

function AssetsPushTableAdapter() {
  return {
    mapRow: assetsRowToInsertRow,
    scope: "merchant",
    selectExistingRows: assetsSelectExistingRows,
    serviceKey: "assets",
    softDeleteRows: assetsSoftDeleteRows,
    tableName: "assets",
    upsertRows: assetsUpsertRows,
    writeColumnCount: 15,
  } as const;
}

function productsRowToInsertRow(row: Record<string, unknown>, context: PushAdapterContext) {
  const normalized = {
    id: stringField(row.id),
    categoryId: nullableStringField(row.categoryId),
    name: stringField(row.name),
    priceMinorUnits: requiredInt64NumberField(row.priceMinorUnits, "products.priceMinorUnits"),
    imageUrl: nullableStringField(row.imageUrl),
    imageAssetId: nullableStringField(row.imageAssetId),
    isActive: boolField(row.isActive),
    sortOrder: requiredInt64NumberField(row.sortOrder, "products.sortOrder"),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
  return applyContextOwnership(normalized, context, "merchantId");
}

function productsSelectExistingRows(tx: TransactionLike, ids: string[]) {
  return selectExistingRowsById(tx, products, { id: products.id, updatedAt: products.updatedAt }, ids);
}

function productsUpsertRows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  return upsertRowsByAdapter(tx, products, {
    merchantId: sql.raw("excluded.merchant_id"),
    categoryId: sql.raw("excluded.category_id"),
    name: sql.raw("excluded.name"),
    priceMinorUnits: sql.raw("excluded.price_minor_units"),
    imageUrl: sql.raw("excluded.image_url"),
    imageAssetId: sql.raw("excluded.image_asset_id"),
    isActive: sql.raw("excluded.is_active"),
    sortOrder: sql.raw("excluded.sort_order"),
    deletedAt: sql.raw("excluded.deleted_at"),
    createdAt: sql.raw("excluded.created_at"),
    updatedAt: sql.raw("excluded.updated_at"),
  }, rows);
}

function productsSoftDeleteRows(tx: TransactionLike, ids: string[], now: string) {
  return softDeleteRowsByAdapter(tx, products, ids, now);
}

function ProductsPushTableAdapter() {
  return {
    mapRow: productsRowToInsertRow,
    scope: "merchant",
    selectExistingRows: productsSelectExistingRows,
    serviceKey: "products",
    softDeleteRows: productsSoftDeleteRows,
    tableName: "products",
    upsertRows: productsUpsertRows,
    writeColumnCount: 12,
  } as const;
}

function outletProductsRowToInsertRow(row: Record<string, unknown>, context: PushAdapterContext) {
  const normalized = {
    id: stringField(row.id),
    productId: stringField(row.productId),
    priceMinorUnits: nullableInt64NumberField(row.priceMinorUnits, "outlet_products.priceMinorUnits"),
    isAvailable: boolField(row.isAvailable),
    sortOrder: nullableInt64NumberField(row.sortOrder, "outlet_products.sortOrder"),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
  return applyContextOwnership(normalized, context, "outletId");
}

function outletProductsSelectExistingRows(tx: TransactionLike, ids: string[]) {
  return selectExistingRowsById(tx, outletProducts, { id: outletProducts.id, updatedAt: outletProducts.updatedAt }, ids);
}

function outletProductsUpsertRows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  return upsertRowsByAdapter(tx, outletProducts, {
    outletId: sql.raw("excluded.outlet_id"),
    productId: sql.raw("excluded.product_id"),
    priceMinorUnits: sql.raw("excluded.price_minor_units"),
    isAvailable: sql.raw("excluded.is_available"),
    sortOrder: sql.raw("excluded.sort_order"),
    deletedAt: sql.raw("excluded.deleted_at"),
    createdAt: sql.raw("excluded.created_at"),
    updatedAt: sql.raw("excluded.updated_at"),
  }, rows);
}

function outletProductsSoftDeleteRows(tx: TransactionLike, ids: string[], now: string) {
  return softDeleteRowsByAdapter(tx, outletProducts, ids, now);
}

function OutletProductsPushTableAdapter() {
  return {
    mapRow: outletProductsRowToInsertRow,
    scope: "outlet",
    selectExistingRows: outletProductsSelectExistingRows,
    serviceKey: "outlet_products",
    softDeleteRows: outletProductsSoftDeleteRows,
    tableName: "outlet_products",
    upsertRows: outletProductsUpsertRows,
    writeColumnCount: 9,
  } as const;
}

function ordersRowToInsertRow(row: Record<string, unknown>, context: PushAdapterContext) {
  const normalized = {
    id: stringField(row.id),
    registerId: nullableStringField(row.registerId),
    staffId: nullableStringField(row.staffId),
    orderNumber: stringField(row.orderNumber),
    totalMinorUnits: requiredInt64NumberField(row.totalMinorUnits, "orders.totalMinorUnits"),
    paymentMethod: stringField(row.paymentMethod),
    amountPaidMinorUnits: nullableInt64NumberField(row.amountPaidMinorUnits, "orders.amountPaidMinorUnits"),
    changeAmountMinorUnits: nullableInt64NumberField(row.changeAmountMinorUnits, "orders.changeAmountMinorUnits"),
    status: stringField(row.status),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
  return applyContextOwnership(normalized, context, "outletId");
}

function ordersSelectExistingRows(tx: TransactionLike, ids: string[]) {
  return selectExistingRowsById(tx, orders, { id: orders.id, updatedAt: orders.updatedAt }, ids);
}

function ordersUpsertRows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  return upsertRowsByAdapter(tx, orders, {
    outletId: sql.raw("excluded.outlet_id"),
    registerId: sql.raw("excluded.register_id"),
    staffId: sql.raw("excluded.staff_id"),
    orderNumber: sql.raw("excluded.order_number"),
    totalMinorUnits: sql.raw("excluded.total_minor_units"),
    paymentMethod: sql.raw("excluded.payment_method"),
    amountPaidMinorUnits: sql.raw("excluded.amount_paid_minor_units"),
    changeAmountMinorUnits: sql.raw("excluded.change_amount_minor_units"),
    status: sql.raw("excluded.status"),
    deletedAt: sql.raw("excluded.deleted_at"),
    createdAt: sql.raw("excluded.created_at"),
    updatedAt: sql.raw("excluded.updated_at"),
  }, rows);
}

function ordersSoftDeleteRows(tx: TransactionLike, ids: string[], now: string) {
  return softDeleteRowsByAdapter(tx, orders, ids, now);
}

function OrdersPushTableAdapter() {
  return {
    mapRow: ordersRowToInsertRow,
    scope: "outlet",
    selectExistingRows: ordersSelectExistingRows,
    serviceKey: "orders",
    softDeleteRows: ordersSoftDeleteRows,
    tableName: "orders",
    upsertRows: ordersUpsertRows,
    writeColumnCount: 13,
  } as const;
}

function orderItemsRowToInsertRow(row: Record<string, unknown>, context: PushAdapterContext) {
  const normalized = {
    id: stringField(row.id),
    orderId: stringField(row.orderId),
    productId: nullableStringField(row.productId),
    productName: stringField(row.productName),
    quantity: requiredInt64NumberField(row.quantity, "order_items.quantity"),
    unitPriceMinorUnits: requiredInt64NumberField(row.unitPriceMinorUnits, "order_items.unitPriceMinorUnits"),
    originalPriceMinorUnits: nullableInt64NumberField(row.originalPriceMinorUnits, "order_items.originalPriceMinorUnits"),
    subtotalMinorUnits: requiredInt64NumberField(row.subtotalMinorUnits, "order_items.subtotalMinorUnits"),
    deletedAt: nullableStringField(row.deletedAt),
    createdAt: stringField(row.createdAt),
    updatedAt: stringField(row.updatedAt),
  };
  return applyContextOwnership(normalized, context, "outletId");
}

function orderItemsSelectExistingRows(tx: TransactionLike, ids: string[]) {
  return selectExistingRowsById(tx, orderItems, { id: orderItems.id, createdAt: orderItems.createdAt }, ids);
}

function orderItemsUpsertRows(tx: TransactionLike, rows: Record<string, unknown>[]) {
  return upsertRowsByAdapter(tx, orderItems, {
    orderId: sql.raw("excluded.order_id"),
    outletId: sql.raw("excluded.outlet_id"),
    productId: sql.raw("excluded.product_id"),
    productName: sql.raw("excluded.product_name"),
    quantity: sql.raw("excluded.quantity"),
    unitPriceMinorUnits: sql.raw("excluded.unit_price_minor_units"),
    originalPriceMinorUnits: sql.raw("excluded.original_price_minor_units"),
    subtotalMinorUnits: sql.raw("excluded.subtotal_minor_units"),
    deletedAt: sql.raw("excluded.deleted_at"),
    createdAt: sql.raw("excluded.created_at"),
    updatedAt: sql.raw("excluded.updated_at"),
  }, rows);
}

function orderItemsSoftDeleteRows(tx: TransactionLike, ids: string[], now: string) {
  return softDeleteRowsByAdapter(tx, orderItems, ids, now);
}

function OrderItemsPushTableAdapter() {
  return {
    mapRow: orderItemsRowToInsertRow,
    scope: "outlet",
    selectExistingRows: orderItemsSelectExistingRows,
    serviceKey: "order_items",
    softDeleteRows: orderItemsSoftDeleteRows,
    tableName: "order_items",
    upsertRows: orderItemsUpsertRows,
    writeColumnCount: 12,
  } as const;
}

export const PUSH_TABLE_ADAPTERS = [
  MerchantsPushTableAdapter(),
  OutletsPushTableAdapter(),
  RegistersPushTableAdapter(),
  StaffPushTableAdapter(),
  CategoriesPushTableAdapter(),
  AssetsPushTableAdapter(),
  ProductsPushTableAdapter(),
  OutletProductsPushTableAdapter(),
  OrdersPushTableAdapter(),
  OrderItemsPushTableAdapter(),
] as const;

export function getPushTableAdapter(tableName: string) {
  return PUSH_TABLE_ADAPTERS.find((adapter) => adapter.tableName === tableName);
}
