import type { SyncGeneratorConfig } from "./config-types";
import type { ReflectedSyncTable } from "./drizzle-reflection";

function renderRowMessage(table: ReflectedSyncTable): string {
  const lines = [`message ${table.rowMessageName} {`];
  for (const [index, column] of table.columns.entries()) {
    lines.push(`  ${column.protoType} ${column.protoName} = ${index + 1};`);
  }
  lines.push("}");
  return lines.join("\n");
}

function renderChangesMessage(table: ReflectedSyncTable): string {
  return [
    `message ${table.changeMessageName} {`,
    `  repeated ${table.rowMessageName} changedRows = 1;`,
    "  repeated string deletedIds = 2;",
    "}",
  ].join("\n");
}

function renderPushRequest(
  config: SyncGeneratorConfig,
  tables: ReflectedSyncTable[]
): string {
  const lines = [
    "message SyncPushBatchRequest {",
    "  string outletId = 1;",
    "  string idempotencyKey = 2;",
  ];
  for (const [index, table] of tables.entries()) {
    lines.push(
      `  ${table.changeMessageName} ${table.protoFieldName} = ${
        config.requestTypedFieldStart + index
      };`
    );
  }
  lines.push("}");
  return lines.join("\n");
}

function renderPullResponse(
  config: SyncGeneratorConfig,
  tables: ReflectedSyncTable[]
): string {
  const lines = ["message SyncPullBatchResponse {"];
  for (const [index, table] of tables.entries()) {
    lines.push(
      `  ${table.changeMessageName} ${table.protoFieldName} = ${
        config.requestTypedFieldStart + index
      };`
    );
  }
  lines.push("  int64 latestEventId = 100;");
  lines.push("  bool needsFullResync = 101;");
  lines.push("  string serverTime = 102;");
  lines.push("  bool hasMore = 103;");
  lines.push("  string nextPageCursor = 104;");
  lines.push("}");
  return lines.join("\n");
}

export function renderSyncProto(
  config: SyncGeneratorConfig,
  tables: ReflectedSyncTable[]
): string {
  return [
    "// AUTO-GENERATED FILE. DO NOT EDIT.",
    "// Generated by @repo/sync-proto-generator.",
    "",
    'syntax = "proto3";',
    "",
    `package ${config.packageName};`,
    "",
    "message SyncStatusRequest {",
    "  string outletId = 1;",
    "  int64 lastServerEventId = 2;",
    "}",
    "",
    "message SyncStatusResponse {",
    "  repeated string changedTables = 1;",
    "  bool hasChanges = 2;",
    "  int64 latestEventId = 3;",
    "  bool needsFullResync = 4;",
    "  int64 oldestAvailableEventId = 5;",
    "  bool hasOldestAvailableEventId = 6;",
    "}",
    "",
    "message SyncRejectedRow {",
    "  string id = 1;",
    "  string reason = 2;",
    "}",
    "",
    "message SyncTableAck {",
    "  string table = 1;",
    "  repeated string acceptedCreatedIds = 2;",
    "  repeated string acceptedUpdatedIds = 3;",
    "  repeated string acceptedDeletedIds = 4;",
    "  repeated SyncRejectedRow rejected = 5;",
    "}",
    "",
    ...tables.flatMap((table) => [renderRowMessage(table), ""]),
    ...tables.flatMap((table) => [renderChangesMessage(table), ""]),
    renderPushRequest(config, tables),
    "",
    "message SyncPushBatchResponse {",
    "  repeated SyncTableAck tables = 1;",
    "  string serverTime = 2;",
    "  int64 latestEventId = 3;",
    "}",
    "",
    "message SyncPullBatchRequest {",
    "  string outletId = 1;",
    "  int64 afterEventId = 2;",
    "  repeated string tables = 3;",
    "  int32 limit = 4;",
    "  string pageCursor = 5;",
    "}",
    "",
    renderPullResponse(config, tables),
    "",
  ].join("\n");
}
