import type { ReflectedSyncTable } from "./drizzle-reflection";

function rowToProtoFuncName(rowMessageName: string): string {
  return `${rowMessageName}_to_proto`;
}

function renderHelpers(): string {
  return [
    "const INTEGER_STRING_PATTERN = /^-?\\d+$/;",
    "",
    "function int64Field(value: unknown, fieldName: string): bigint {",
    '  if (typeof value === "bigint") return value;',
    '  if (typeof value === "number" && Number.isSafeInteger(value)) return BigInt(value);',
    '  if (typeof value === "string" && INTEGER_STRING_PATTERN.test(value)) return BigInt(value);',
    "  if (value == null) return 0n;",
    '  throw new Error("Invalid int64 value for " + fieldName);',
    "}",
    "",
    "function stringField(value: unknown): string {",
    '  return typeof value === "string" ? value : "";',
    "}",
    "",
    "function boolField(value: unknown): boolean {",
    "  return value === true || value === 1;",
    "}",
    "",
    "function coerceBigInt(value: number | bigint): bigint {",
    '  return typeof value === "bigint" ? value : BigInt(value);',
    "}",
  ].join("\n");
}

function renderRowToProto(table: ReflectedSyncTable): string {
  const funcName = rowToProtoFuncName(table.rowMessageName);
  const lines = [
    `function ${funcName}(row: Record<string, unknown>) {`,
    "  return {",
  ];

  for (const column of table.columns) {
    let valueExpr: string;
    if (column.protoType === "int64") {
      valueExpr = `int64Field(row.${column.propertyName}, "${table.tableName}.${column.propertyName}")`;
    } else if (column.protoType === "bool") {
      valueExpr = `boolField(row.${column.propertyName})`;
    } else {
      valueExpr = `stringField(row.${column.propertyName})`;
    }

    lines.push(`    ${column.protoName}: ${valueExpr},`);
  }

  lines.push("  };");
  lines.push("}");
  return lines.join("\n");
}

function renderMapTableChanges(): string {
  return [
    "function mapTableChanges<Row>(",
    "  changes: { changedRows: Record<string, unknown>[]; deletedIds: string[] } | undefined,",
    "  mapper: (row: Record<string, unknown>) => Row",
    "): { changedRows: Row[]; deletedIds: string[] } | undefined {",
    "  if (!changes) return;",
    "  return {",
    "    changedRows: changes.changedRows.map(mapper),",
    "    deletedIds: changes.deletedIds,",
    "  };",
    "}",
  ].join("\n");
}

function renderDecodeFunction(tables: ReflectedSyncTable[]): string {
  const lines = [
    "export function decodeGeneratedPushBatchRequest(request: Record<string, any>) {",
    "  const changes: Record<string, { changedRows: Record<string, unknown>[]; deletedIds: string[] }> = {};",
    "",
  ];

  for (const table of tables) {
    lines.push(`  if (request.${table.tsProtoFieldName}) {`);
    lines.push(`    changes.${table.serviceKey} = {`);
    lines.push(
      `      changedRows: request.${table.tsProtoFieldName}.changedRows.map((row: any) => ({ ...row })),`
    );
    lines.push(
      `      deletedIds: request.${table.tsProtoFieldName}.deletedIds,`
    );
    lines.push("    };");
    lines.push("  }");
    lines.push("");
  }

  lines.push("  return changes;");
  lines.push("}");
  return lines.join("\n");
}

function renderEncodeFunction(tables: ReflectedSyncTable[]): string {
  const lines = [
    "export function encodeGeneratedPullBatchResponse(result: Record<string, any>) {",
    "  return {",
  ];

  for (const table of tables) {
    const funcName = rowToProtoFuncName(table.rowMessageName);
    lines.push(
      `    ${table.tsProtoFieldName}: mapTableChanges(result.${table.serviceKey}, ${funcName}),`
    );
  }

  lines.push("    hasMore: result.hasMore ?? false,");
  lines.push('    cursor: result.cursor ?? "",');
  lines.push("    serverTime: result.serverTime,");
  lines.push("  };");
  lines.push("}");
  return lines.join("\n");
}

export function renderApiSyncMappers(tables: ReflectedSyncTable[]): string {
  const parts: string[] = [
    "// AUTO-GENERATED FILE. DO NOT EDIT.",
    "// Generated by @repo/sync-proto-generator.",
    "",
    renderHelpers(),
    "",
  ];

  for (const table of tables) {
    parts.push(renderRowToProto(table));
    parts.push("");
  }

  parts.push(renderMapTableChanges());
  parts.push("");
  parts.push(renderDecodeFunction(tables));
  parts.push("");
  parts.push(renderEncodeFunction(tables));
  parts.push("");

  return parts.join("\n");
}
