// Load the frozen AOT manifest before constructing the Worker app —
// workerd bans new Function, so Elysia's lazy JIT cannot run there.
// Generated by `bun run gen:manifest` (see scripts/gen-manifest.mjs).
import "./manifest.generated.js";

import app from "./app";

export default app;
