// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by @repo/sync-proto-generator.

use serde_json::Value;
use std::convert::TryFrom;

use super::sync_proto::{
    AssetsChanges, AssetsRow, CategoriesChanges, CategoriesRow, MerchantsChanges, MerchantsRow,
    OrderItemsChanges, OrderItemsRow, OrdersChanges, OrdersRow, OutletProductsChanges,
    OutletProductsRow, OutletsChanges, OutletsRow, ProductsChanges, ProductsRow, RegistersChanges,
    RegistersRow, StaffChanges, StaffRow, SyncPullBatchResponse, SyncPushBatchRequest,
};

#[derive(Debug, Clone, Default)]
pub(super) struct TablePushChanges {
    pub changed_rows: Vec<Value>,
    pub deleted_ids: Vec<String>,
}

fn value_to_string(row: &Value, keys: &[&str]) -> String {
    for key in keys {
        if let Some(value) = row.get(key) {
            if let Some(string) = value.as_str() {
                return string.to_string();
            }
            if let Some(number) = value.as_i64() {
                return number.to_string();
            }
            if let Some(number) = value.as_u64() {
                return number.to_string();
            }
            if let Some(boolean) = value.as_bool() {
                return boolean.to_string();
            }
        }
    }
    String::new()
}

fn value_to_bool(row: &Value, keys: &[&str]) -> bool {
    for key in keys {
        if let Some(value) = row.get(key) {
            if let Some(boolean) = value.as_bool() {
                return boolean;
            }
            if let Some(number) = value.as_i64() {
                return number != 0;
            }
            if let Some(string) = value.as_str() {
                if let Ok(parsed) = string.parse::<bool>() {
                    return parsed;
                }
                if let Ok(parsed) = string.parse::<i64>() {
                    return parsed != 0;
                }
            }
        }
    }
    false
}

fn value_to_i64(row: &Value, keys: &[&str]) -> i64 {
    for key in keys {
        if let Some(value) = row.get(key) {
            if let Some(number) = value.as_i64() {
                return number;
            }
            if let Some(number) = value.as_u64() {
                return i64::try_from(number).unwrap_or(0);
            }
            if let Some(string) = value.as_str() {
                if let Ok(parsed) = string.parse::<i64>() {
                    return parsed;
                }
            }
        }
    }
    0
}

fn assets_row_from_value(row: &Value) -> AssetsRow {
    AssetsRow {
        id: value_to_string(row, &["id"]),
        merchant_id: value_to_string(row, &["merchantId"]),
        object_key: value_to_string(row, &["objectKey"]),
        original_filename: value_to_string(row, &["originalFilename"]),
        content_type: value_to_string(row, &["contentType"]),
        byte_size: value_to_i64(row, &["byteSize"]),
        content_hash: value_to_string(row, &["contentHash"]),
        kind: value_to_string(row, &["kind"]),
        width: value_to_i64(row, &["width"]),
        height: value_to_i64(row, &["height"]),
        status: value_to_string(row, &["status"]),
        created_by_user_id: value_to_string(row, &["createdByUserId"]),
        deleted_at: value_to_string(row, &["deletedAt"]),
        created_at: value_to_string(row, &["createdAt"]),
        updated_at: value_to_string(row, &["updatedAt"]),
    }
}

fn categories_row_from_value(row: &Value) -> CategoriesRow {
    CategoriesRow {
        id: value_to_string(row, &["id"]),
        merchant_id: value_to_string(row, &["merchantId"]),
        name: value_to_string(row, &["name"]),
        sort_order: value_to_i64(row, &["sortOrder"]),
        is_active: value_to_bool(row, &["isActive"]),
        deleted_at: value_to_string(row, &["deletedAt"]),
        created_at: value_to_string(row, &["createdAt"]),
        updated_at: value_to_string(row, &["updatedAt"]),
    }
}

fn merchants_row_from_value(row: &Value) -> MerchantsRow {
    MerchantsRow {
        id: value_to_string(row, &["id"]),
        name: value_to_string(row, &["name"]),
        deleted_at: value_to_string(row, &["deletedAt"]),
        created_at: value_to_string(row, &["createdAt"]),
        updated_at: value_to_string(row, &["updatedAt"]),
    }
}

fn order_items_row_from_value(row: &Value) -> OrderItemsRow {
    OrderItemsRow {
        id: value_to_string(row, &["id"]),
        order_id: value_to_string(row, &["orderId"]),
        outlet_id: value_to_string(row, &["outletId"]),
        product_id: value_to_string(row, &["productId"]),
        product_name: value_to_string(row, &["productName"]),
        quantity: value_to_i64(row, &["quantity"]),
        unit_price_minor_units: value_to_i64(row, &["unitPriceMinorUnits"]),
        original_price_minor_units: value_to_i64(row, &["originalPriceMinorUnits"]),
        subtotal_minor_units: value_to_i64(row, &["subtotalMinorUnits"]),
        updated_at: value_to_string(row, &["updatedAt"]),
        deleted_at: value_to_string(row, &["deletedAt"]),
        created_at: value_to_string(row, &["createdAt"]),
    }
}

fn orders_row_from_value(row: &Value) -> OrdersRow {
    OrdersRow {
        id: value_to_string(row, &["id"]),
        outlet_id: value_to_string(row, &["outletId"]),
        register_id: value_to_string(row, &["registerId"]),
        staff_id: value_to_string(row, &["staffId"]),
        order_number: value_to_string(row, &["orderNumber"]),
        total_minor_units: value_to_i64(row, &["totalMinorUnits"]),
        payment_method: value_to_string(row, &["paymentMethod"]),
        amount_paid_minor_units: value_to_i64(row, &["amountPaidMinorUnits"]),
        change_amount_minor_units: value_to_i64(row, &["changeAmountMinorUnits"]),
        status: value_to_string(row, &["status"]),
        deleted_at: value_to_string(row, &["deletedAt"]),
        created_at: value_to_string(row, &["createdAt"]),
        updated_at: value_to_string(row, &["updatedAt"]),
    }
}

fn outlet_products_row_from_value(row: &Value) -> OutletProductsRow {
    OutletProductsRow {
        id: value_to_string(row, &["id"]),
        outlet_id: value_to_string(row, &["outletId"]),
        product_id: value_to_string(row, &["productId"]),
        price_minor_units: value_to_i64(row, &["priceMinorUnits"]),
        is_available: value_to_bool(row, &["isAvailable"]),
        sort_order: value_to_i64(row, &["sortOrder"]),
        deleted_at: value_to_string(row, &["deletedAt"]),
        created_at: value_to_string(row, &["createdAt"]),
        updated_at: value_to_string(row, &["updatedAt"]),
    }
}

fn outlets_row_from_value(row: &Value) -> OutletsRow {
    OutletsRow {
        id: value_to_string(row, &["id"]),
        merchant_id: value_to_string(row, &["merchantId"]),
        timezone: value_to_string(row, &["timezone"]),
        name: value_to_string(row, &["name"]),
        address: value_to_string(row, &["address"]),
        receipt_name: value_to_string(row, &["receiptName"]),
        receipt_address: value_to_string(row, &["receiptAddress"]),
        is_active: value_to_bool(row, &["isActive"]),
        deleted_at: value_to_string(row, &["deletedAt"]),
        created_at: value_to_string(row, &["createdAt"]),
        updated_at: value_to_string(row, &["updatedAt"]),
    }
}

fn products_row_from_value(row: &Value) -> ProductsRow {
    ProductsRow {
        id: value_to_string(row, &["id"]),
        merchant_id: value_to_string(row, &["merchantId"]),
        category_id: value_to_string(row, &["categoryId"]),
        name: value_to_string(row, &["name"]),
        price_minor_units: value_to_i64(row, &["priceMinorUnits"]),
        image_url: value_to_string(row, &["imageUrl"]),
        image_asset_id: value_to_string(row, &["imageAssetId"]),
        is_active: value_to_bool(row, &["isActive"]),
        sort_order: value_to_i64(row, &["sortOrder"]),
        deleted_at: value_to_string(row, &["deletedAt"]),
        created_at: value_to_string(row, &["createdAt"]),
        updated_at: value_to_string(row, &["updatedAt"]),
    }
}

fn registers_row_from_value(row: &Value) -> RegistersRow {
    RegistersRow {
        id: value_to_string(row, &["id"]),
        outlet_id: value_to_string(row, &["outletId"]),
        name: value_to_string(row, &["name"]),
        short_id: value_to_string(row, &["shortId"]),
        pairing_code: value_to_string(row, &["pairingCode"]),
        pairing_expires_at: value_to_string(row, &["pairingExpiresAt"]),
        is_active: value_to_bool(row, &["isActive"]),
        last_seen_at: value_to_string(row, &["lastSeenAt"]),
        deleted_at: value_to_string(row, &["deletedAt"]),
        created_at: value_to_string(row, &["createdAt"]),
        updated_at: value_to_string(row, &["updatedAt"]),
    }
}

fn staff_row_from_value(row: &Value) -> StaffRow {
    StaffRow {
        id: value_to_string(row, &["id"]),
        merchant_id: value_to_string(row, &["merchantId"]),
        cloud_user_id: value_to_string(row, &["cloudUserId"]),
        outlet_id: value_to_string(row, &["outletId"]),
        name: value_to_string(row, &["name"]),
        pin: value_to_string(row, &["pin"]),
        role: value_to_string(row, &["role"]),
        is_active: value_to_bool(row, &["isActive"]),
        deleted_at: value_to_string(row, &["deletedAt"]),
        created_at: value_to_string(row, &["createdAt"]),
        updated_at: value_to_string(row, &["updatedAt"]),
    }
}

fn empty_string_to_null(value: &str) -> Value {
    if value.is_empty() {
        Value::Null
    } else {
        Value::String(value.to_string())
    }
}

fn assets_row_to_value(row: &AssetsRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "merchantId": row.merchant_id,
        "objectKey": row.object_key,
        "originalFilename": empty_string_to_null(&row.original_filename),
        "contentType": row.content_type,
        "byteSize": row.byte_size,
        "contentHash": row.content_hash,
        "kind": row.kind,
        "width": row.width,
        "height": row.height,
        "status": row.status,
        "createdByUserId": empty_string_to_null(&row.created_by_user_id),
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn categories_row_to_value(row: &CategoriesRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "merchantId": row.merchant_id,
        "name": row.name,
        "sortOrder": row.sort_order,
        "isActive": row.is_active,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn merchants_row_to_value(row: &MerchantsRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "name": row.name,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn order_items_row_to_value(row: &OrderItemsRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "orderId": row.order_id,
        "outletId": row.outlet_id,
        "productId": empty_string_to_null(&row.product_id),
        "productName": row.product_name,
        "quantity": row.quantity,
        "unitPriceMinorUnits": row.unit_price_minor_units,
        "originalPriceMinorUnits": row.original_price_minor_units,
        "subtotalMinorUnits": row.subtotal_minor_units,
        "updatedAt": row.updated_at,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
    })
}

fn orders_row_to_value(row: &OrdersRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "outletId": row.outlet_id,
        "registerId": empty_string_to_null(&row.register_id),
        "staffId": empty_string_to_null(&row.staff_id),
        "orderNumber": row.order_number,
        "totalMinorUnits": row.total_minor_units,
        "paymentMethod": row.payment_method,
        "amountPaidMinorUnits": row.amount_paid_minor_units,
        "changeAmountMinorUnits": row.change_amount_minor_units,
        "status": row.status,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn outlet_products_row_to_value(row: &OutletProductsRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "outletId": row.outlet_id,
        "productId": row.product_id,
        "priceMinorUnits": row.price_minor_units,
        "isAvailable": row.is_available,
        "sortOrder": row.sort_order,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn outlets_row_to_value(row: &OutletsRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "merchantId": row.merchant_id,
        "timezone": row.timezone,
        "name": row.name,
        "address": empty_string_to_null(&row.address),
        "receiptName": empty_string_to_null(&row.receipt_name),
        "receiptAddress": empty_string_to_null(&row.receipt_address),
        "isActive": row.is_active,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn products_row_to_value(row: &ProductsRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "merchantId": row.merchant_id,
        "categoryId": empty_string_to_null(&row.category_id),
        "name": row.name,
        "priceMinorUnits": row.price_minor_units,
        "imageUrl": empty_string_to_null(&row.image_url),
        "imageAssetId": empty_string_to_null(&row.image_asset_id),
        "isActive": row.is_active,
        "sortOrder": row.sort_order,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn registers_row_to_value(row: &RegistersRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "outletId": row.outlet_id,
        "name": row.name,
        "shortId": row.short_id,
        "pairingCode": empty_string_to_null(&row.pairing_code),
        "pairingExpiresAt": empty_string_to_null(&row.pairing_expires_at),
        "isActive": row.is_active,
        "lastSeenAt": empty_string_to_null(&row.last_seen_at),
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn staff_row_to_value(row: &StaffRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "merchantId": row.merchant_id,
        "cloudUserId": empty_string_to_null(&row.cloud_user_id),
        "outletId": empty_string_to_null(&row.outlet_id),
        "name": row.name,
        "pin": empty_string_to_null(&row.pin),
        "role": row.role,
        "isActive": row.is_active,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn typed_rows_to_json_values<T>(
    changed_rows: &[T],
    deleted_ids: &[String],
    server_time: &str,
    mapper: impl Fn(&T) -> Value,
) -> Vec<Value> {
    let mut rows = changed_rows.iter().map(mapper).collect::<Vec<_>>();
    rows.extend(
        deleted_ids
            .iter()
            .map(|id| serde_json::json!({ "id": id, "deletedAt": server_time })),
    );
    rows
}

pub(super) fn build_assets_row_changes(changes: &TablePushChanges) -> AssetsChanges {
    AssetsChanges {
        changed_rows: changes
            .changed_rows
            .iter()
            .map(assets_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
    }
}

pub(super) fn build_categories_row_changes(changes: &TablePushChanges) -> CategoriesChanges {
    CategoriesChanges {
        changed_rows: changes
            .changed_rows
            .iter()
            .map(categories_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
    }
}

pub(super) fn build_merchants_row_changes(changes: &TablePushChanges) -> MerchantsChanges {
    MerchantsChanges {
        changed_rows: changes
            .changed_rows
            .iter()
            .map(merchants_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
    }
}

pub(super) fn build_order_items_row_changes(changes: &TablePushChanges) -> OrderItemsChanges {
    OrderItemsChanges {
        changed_rows: changes
            .changed_rows
            .iter()
            .map(order_items_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
    }
}

pub(super) fn build_orders_row_changes(changes: &TablePushChanges) -> OrdersChanges {
    OrdersChanges {
        changed_rows: changes
            .changed_rows
            .iter()
            .map(orders_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
    }
}

pub(super) fn build_outlet_products_row_changes(
    changes: &TablePushChanges,
) -> OutletProductsChanges {
    OutletProductsChanges {
        changed_rows: changes
            .changed_rows
            .iter()
            .map(outlet_products_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
    }
}

pub(super) fn build_outlets_row_changes(changes: &TablePushChanges) -> OutletsChanges {
    OutletsChanges {
        changed_rows: changes
            .changed_rows
            .iter()
            .map(outlets_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
    }
}

pub(super) fn build_products_row_changes(changes: &TablePushChanges) -> ProductsChanges {
    ProductsChanges {
        changed_rows: changes
            .changed_rows
            .iter()
            .map(products_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
    }
}

pub(super) fn build_registers_row_changes(changes: &TablePushChanges) -> RegistersChanges {
    RegistersChanges {
        changed_rows: changes
            .changed_rows
            .iter()
            .map(registers_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
    }
}

pub(super) fn build_staff_row_changes(changes: &TablePushChanges) -> StaffChanges {
    StaffChanges {
        changed_rows: changes
            .changed_rows
            .iter()
            .map(staff_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
    }
}

pub(super) fn build_sync_push_batch_request(
    outlet_id: &str,
    client_id: &str,
    idempotency_key: &str,
    assets: Option<AssetsChanges>,
    categories: Option<CategoriesChanges>,
    merchants: Option<MerchantsChanges>,
    order_items: Option<OrderItemsChanges>,
    orders: Option<OrdersChanges>,
    outlet_products: Option<OutletProductsChanges>,
    outlets: Option<OutletsChanges>,
    products: Option<ProductsChanges>,
    registers: Option<RegistersChanges>,
    staff: Option<StaffChanges>,
) -> SyncPushBatchRequest {
    SyncPushBatchRequest {
        outlet_id: outlet_id.to_string(),
        client_id: client_id.to_string(),
        idempotency_key: idempotency_key.to_string(),
        assets,
        categories,
        merchants,
        order_items,
        orders,
        outlet_products,
        outlets,
        products,
        registers,
        staff,
    }
}

pub(super) fn decode_pull_batch_response_tables(
    response: &SyncPullBatchResponse,
) -> Result<std::collections::BTreeMap<String, Value>, String> {
    let mut map = std::collections::BTreeMap::new();

    if let Some(changes) = &response.assets {
        map.insert(
            "assets".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.changed_rows,
                &changes.deleted_ids,
                &response.server_time,
                assets_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.categories {
        map.insert(
            "categories".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.changed_rows,
                &changes.deleted_ids,
                &response.server_time,
                categories_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.merchants {
        map.insert(
            "merchants".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.changed_rows,
                &changes.deleted_ids,
                &response.server_time,
                merchants_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.order_items {
        map.insert(
            "order_items".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.changed_rows,
                &changes.deleted_ids,
                &response.server_time,
                order_items_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.orders {
        map.insert(
            "orders".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.changed_rows,
                &changes.deleted_ids,
                &response.server_time,
                orders_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.outlet_products {
        map.insert(
            "outlet_products".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.changed_rows,
                &changes.deleted_ids,
                &response.server_time,
                outlet_products_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.outlets {
        map.insert(
            "outlets".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.changed_rows,
                &changes.deleted_ids,
                &response.server_time,
                outlets_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.products {
        map.insert(
            "products".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.changed_rows,
                &changes.deleted_ids,
                &response.server_time,
                products_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.registers {
        map.insert(
            "registers".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.changed_rows,
                &changes.deleted_ids,
                &response.server_time,
                registers_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.staff {
        map.insert(
            "staff".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.changed_rows,
                &changes.deleted_ids,
                &response.server_time,
                staff_row_to_value,
            )),
        );
    }

    Ok(map)
}

pub(super) fn pull_batch_response_has_more(response: &SyncPullBatchResponse) -> bool {
    response.has_more
}

pub(super) fn pull_batch_response_cursor(response: &SyncPullBatchResponse) -> String {
    response.cursor.clone()
}

pub(super) fn pull_batch_response_server_time(response: &SyncPullBatchResponse) -> String {
    response.server_time.clone()
}
