// Auto-generated by @repo/sync-proto-generator
// Do not edit manually.

use serde_json::Value;
use std::convert::TryFrom;

use super::sync_proto::{
    AssetChanges, AssetRow, CategoryChanges, CategoryRow, MerchantChanges, MerchantRow,
    OrderChanges, OrderItemChanges, OrderItemRow, OrderRow, OutletChanges, OutletProductChanges,
    OutletProductRow, OutletRow, ProductChanges, ProductRow, RegisterChanges, RegisterRow,
    StaffChanges, StaffRow, SyncPullBatchResponse, SyncPushBatchRequest,
};

#[derive(Debug, Clone, Default)]
pub(super) struct TablePushChanges {
    pub created: Vec<Value>,
    pub updated: Vec<Value>,
    pub deleted_ids: Vec<String>,
}

fn value_to_string(row: &Value, keys: &[&str]) -> String {
    for key in keys {
        if let Some(value) = row.get(key) {
            if let Some(string) = value.as_str() {
                return string.to_string();
            }
            if let Some(number) = value.as_i64() {
                return number.to_string();
            }
            if let Some(number) = value.as_u64() {
                return number.to_string();
            }
            if let Some(boolean) = value.as_bool() {
                return boolean.to_string();
            }
        }
    }
    String::new()
}

fn value_to_bool(row: &Value, keys: &[&str]) -> bool {
    for key in keys {
        if let Some(value) = row.get(key) {
            if let Some(boolean) = value.as_bool() {
                return boolean;
            }
            if let Some(number) = value.as_i64() {
                return number != 0;
            }
            if let Some(string) = value.as_str() {
                if let Ok(parsed) = string.parse::<bool>() {
                    return parsed;
                }
                if let Ok(parsed) = string.parse::<i64>() {
                    return parsed != 0;
                }
            }
        }
    }
    false
}

fn value_to_i64(row: &Value, keys: &[&str]) -> i64 {
    for key in keys {
        if let Some(value) = row.get(key) {
            if let Some(number) = value.as_i64() {
                return number;
            }
            if let Some(number) = value.as_u64() {
                return i64::try_from(number).unwrap_or(0);
            }
            if let Some(string) = value.as_str() {
                if let Ok(parsed) = string.parse::<i64>() {
                    return parsed;
                }
            }
        }
    }
    0
}

fn merchant_row_from_value(row: &Value) -> MerchantRow {
    MerchantRow {
        id: value_to_string(row, &["id"]),
        name: value_to_string(row, &["name"]),
        deleted_at: value_to_string(row, &["deletedAt", "deleted_at"]),
        created_at: value_to_string(row, &["createdAt", "created_at"]),
        updated_at: value_to_string(row, &["updatedAt", "updated_at"]),
    }
}

fn outlet_row_from_value(row: &Value) -> OutletRow {
    OutletRow {
        id: value_to_string(row, &["id"]),
        merchant_id: value_to_string(row, &["merchantId", "merchant_id"]),
        timezone: value_to_string(row, &["timezone"]),
        name: value_to_string(row, &["name"]),
        address: value_to_string(row, &["address"]),
        receipt_name: value_to_string(row, &["receiptName", "receipt_name"]),
        receipt_address: value_to_string(row, &["receiptAddress", "receipt_address"]),
        is_active: value_to_bool(row, &["isActive", "is_active"]),
        deleted_at: value_to_string(row, &["deletedAt", "deleted_at"]),
        created_at: value_to_string(row, &["createdAt", "created_at"]),
        updated_at: value_to_string(row, &["updatedAt", "updated_at"]),
    }
}

fn register_row_from_value(row: &Value) -> RegisterRow {
    RegisterRow {
        id: value_to_string(row, &["id"]),
        outlet_id: value_to_string(row, &["outletId", "outlet_id"]),
        name: value_to_string(row, &["name"]),
        short_id: value_to_string(row, &["shortId", "short_id"]),
        pairing_code: value_to_string(row, &["pairingCode", "pairing_code"]),
        pairing_expires_at: value_to_string(row, &["pairingExpiresAt", "pairing_expires_at"]),
        is_active: value_to_bool(row, &["isActive", "is_active"]),
        last_seen_at: value_to_string(row, &["lastSeenAt", "last_seen_at"]),
        deleted_at: value_to_string(row, &["deletedAt", "deleted_at"]),
        created_at: value_to_string(row, &["createdAt", "created_at"]),
        updated_at: value_to_string(row, &["updatedAt", "updated_at"]),
    }
}

fn category_row_from_value(row: &Value) -> CategoryRow {
    CategoryRow {
        id: value_to_string(row, &["id"]),
        merchant_id: value_to_string(row, &["merchantId", "merchant_id"]),
        name: value_to_string(row, &["name"]),
        sort_order: value_to_i64(row, &["sortOrder", "sort_order"]),
        is_active: value_to_bool(row, &["isActive", "is_active"]),
        deleted_at: value_to_string(row, &["deletedAt", "deleted_at"]),
        created_at: value_to_string(row, &["createdAt", "created_at"]),
        updated_at: value_to_string(row, &["updatedAt", "updated_at"]),
    }
}

fn asset_row_from_value(row: &Value) -> AssetRow {
    AssetRow {
        id: value_to_string(row, &["id"]),
        merchant_id: value_to_string(row, &["merchantId", "merchant_id"]),
        object_key: value_to_string(row, &["objectKey", "object_key"]),
        original_filename: value_to_string(row, &["originalFilename", "original_filename"]),
        content_type: value_to_string(row, &["contentType", "content_type"]),
        byte_size: value_to_i64(row, &["byteSize", "byte_size"]),
        content_hash: value_to_string(row, &["contentHash", "content_hash"]),
        kind: value_to_string(row, &["kind"]),
        width: value_to_i64(row, &["width"]),
        height: value_to_i64(row, &["height"]),
        status: value_to_string(row, &["status"]),
        created_by_user_id: value_to_string(row, &["createdByUserId", "created_by_user_id"]),
        deleted_at: value_to_string(row, &["deletedAt", "deleted_at"]),
        created_at: value_to_string(row, &["createdAt", "created_at"]),
        updated_at: value_to_string(row, &["updatedAt", "updated_at"]),
    }
}

fn product_row_from_value(row: &Value) -> ProductRow {
    ProductRow {
        id: value_to_string(row, &["id"]),
        merchant_id: value_to_string(row, &["merchantId", "merchant_id"]),
        category_id: value_to_string(row, &["categoryId", "category_id"]),
        name: value_to_string(row, &["name"]),
        price_minor_units: value_to_i64(row, &["priceMinorUnits", "price"]),
        image_url: value_to_string(row, &["imageUrl", "image_url"]),
        image_asset_id: value_to_string(row, &["imageAssetId", "image_asset_id"]),
        is_active: value_to_bool(row, &["isActive", "is_active"]),
        sort_order: value_to_i64(row, &["sortOrder", "sort_order"]),
        deleted_at: value_to_string(row, &["deletedAt", "deleted_at"]),
        created_at: value_to_string(row, &["createdAt", "created_at"]),
        updated_at: value_to_string(row, &["updatedAt", "updated_at"]),
    }
}

fn order_row_from_value(row: &Value) -> OrderRow {
    OrderRow {
        id: value_to_string(row, &["id"]),
        outlet_id: value_to_string(row, &["outletId", "outlet_id"]),
        register_id: value_to_string(row, &["registerId", "register_id"]),
        staff_id: value_to_string(row, &["staffId", "staff_id"]),
        order_number: value_to_string(row, &["orderNumber", "order_number"]),
        total_minor_units: value_to_i64(row, &["totalMinorUnits", "total"]),
        payment_method: value_to_string(row, &["paymentMethod", "payment_method"]),
        amount_paid_minor_units: value_to_i64(
            row,
            &["amountPaidMinorUnits", "amountPaid", "amount_paid"],
        ),
        change_amount_minor_units: value_to_i64(
            row,
            &["changeAmountMinorUnits", "changeAmount", "change_amount"],
        ),
        status: value_to_string(row, &["status"]),
        deleted_at: value_to_string(row, &["deletedAt", "deleted_at"]),
        created_at: value_to_string(row, &["createdAt", "created_at"]),
        updated_at: value_to_string(row, &["updatedAt", "updated_at"]),
    }
}

fn order_item_row_from_value(row: &Value) -> OrderItemRow {
    OrderItemRow {
        id: value_to_string(row, &["id"]),
        order_id: value_to_string(row, &["orderId", "order_id"]),
        outlet_id: value_to_string(row, &["outletId", "outlet_id"]),
        product_id: value_to_string(row, &["productId", "product_id"]),
        product_name: value_to_string(row, &["productName", "product_name"]),
        quantity: value_to_i64(row, &["quantity"]),
        unit_price_minor_units: value_to_i64(
            row,
            &["unitPriceMinorUnits", "unitPrice", "unit_price"],
        ),
        original_price_minor_units: value_to_i64(
            row,
            &["originalPriceMinorUnits", "originalPrice", "original_price"],
        ),
        subtotal_minor_units: value_to_i64(row, &["subtotalMinorUnits", "subtotal"]),
        deleted_at: value_to_string(row, &["deletedAt", "deleted_at"]),
        created_at: value_to_string(row, &["createdAt", "created_at"]),
        updated_at: value_to_string(row, &["updatedAt", "updated_at"]),
    }
}

fn outlet_product_row_from_value(row: &Value) -> OutletProductRow {
    OutletProductRow {
        id: value_to_string(row, &["id"]),
        outlet_id: value_to_string(row, &["outletId", "outlet_id"]),
        product_id: value_to_string(row, &["productId", "product_id"]),
        price_minor_units: value_to_i64(row, &["priceMinorUnits", "price"]),
        is_available: value_to_bool(row, &["isAvailable", "is_available"]),
        sort_order: value_to_i64(row, &["sortOrder", "sort_order"]),
        deleted_at: value_to_string(row, &["deletedAt", "deleted_at"]),
        created_at: value_to_string(row, &["createdAt", "created_at"]),
        updated_at: value_to_string(row, &["updatedAt", "updated_at"]),
    }
}

fn staff_row_from_value(row: &Value) -> StaffRow {
    StaffRow {
        id: value_to_string(row, &["id"]),
        merchant_id: value_to_string(row, &["merchantId", "merchant_id"]),
        cloud_user_id: value_to_string(row, &["cloudUserId", "cloud_user_id"]),
        outlet_id: value_to_string(row, &["outletId", "outlet_id"]),
        name: value_to_string(row, &["name"]),
        pin: value_to_string(row, &["pin"]),
        role: value_to_string(row, &["role"]),
        is_active: value_to_bool(row, &["isActive", "is_active"]),
        deleted_at: value_to_string(row, &["deletedAt", "deleted_at"]),
        created_at: value_to_string(row, &["createdAt", "created_at"]),
        updated_at: value_to_string(row, &["updatedAt", "updated_at"]),
    }
}

fn empty_string_to_null(value: &str) -> Value {
    if value.is_empty() {
        Value::Null
    } else {
        Value::String(value.to_string())
    }
}

fn merchant_row_to_value(row: &MerchantRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "name": row.name,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn outlet_row_to_value(row: &OutletRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "merchantId": row.merchant_id,
        "timezone": row.timezone,
        "name": row.name,
        "address": empty_string_to_null(&row.address),
        "receiptName": empty_string_to_null(&row.receipt_name),
        "receiptAddress": empty_string_to_null(&row.receipt_address),
        "isActive": row.is_active,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn register_row_to_value(row: &RegisterRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "outletId": row.outlet_id,
        "name": row.name,
        "shortId": row.short_id,
        "pairingCode": empty_string_to_null(&row.pairing_code),
        "pairingExpiresAt": empty_string_to_null(&row.pairing_expires_at),
        "isActive": row.is_active,
        "lastSeenAt": empty_string_to_null(&row.last_seen_at),
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn category_row_to_value(row: &CategoryRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "merchantId": row.merchant_id,
        "name": row.name,
        "sortOrder": row.sort_order,
        "isActive": row.is_active,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn asset_row_to_value(row: &AssetRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "merchantId": row.merchant_id,
        "objectKey": row.object_key,
        "originalFilename": empty_string_to_null(&row.original_filename),
        "contentType": row.content_type,
        "byteSize": row.byte_size,
        "contentHash": row.content_hash,
        "kind": row.kind,
        "width": row.width,
        "height": row.height,
        "status": row.status,
        "createdByUserId": empty_string_to_null(&row.created_by_user_id),
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn product_row_to_value(row: &ProductRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "merchantId": row.merchant_id,
        "categoryId": empty_string_to_null(&row.category_id),
        "name": row.name,
        "price": row.price_minor_units,
        "imageUrl": empty_string_to_null(&row.image_url),
        "imageAssetId": empty_string_to_null(&row.image_asset_id),
        "isActive": row.is_active,
        "sortOrder": row.sort_order,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn order_row_to_value(row: &OrderRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "outletId": row.outlet_id,
        "registerId": empty_string_to_null(&row.register_id),
        "staffId": empty_string_to_null(&row.staff_id),
        "orderNumber": row.order_number,
        "total": row.total_minor_units,
        "paymentMethod": row.payment_method,
        "amountPaid": row.amount_paid_minor_units,
        "changeAmount": row.change_amount_minor_units,
        "status": row.status,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn order_item_row_to_value(row: &OrderItemRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "orderId": row.order_id,
        "outletId": row.outlet_id,
        "productId": empty_string_to_null(&row.product_id),
        "productName": row.product_name,
        "quantity": row.quantity,
        "unitPrice": row.unit_price_minor_units,
        "originalPrice": row.original_price_minor_units,
        "subtotal": row.subtotal_minor_units,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn outlet_product_row_to_value(row: &OutletProductRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "outletId": row.outlet_id,
        "productId": row.product_id,
        "price": row.price_minor_units,
        "isAvailable": row.is_available,
        "sortOrder": row.sort_order,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn staff_row_to_value(row: &StaffRow) -> Value {
    serde_json::json!({
        "id": row.id,
        "merchantId": row.merchant_id,
        "cloudUserId": empty_string_to_null(&row.cloud_user_id),
        "outletId": empty_string_to_null(&row.outlet_id),
        "name": row.name,
        "pin": empty_string_to_null(&row.pin),
        "role": row.role,
        "isActive": row.is_active,
        "deletedAt": empty_string_to_null(&row.deleted_at),
        "createdAt": row.created_at,
        "updatedAt": row.updated_at,
    })
}

fn typed_rows_to_json_values<T>(
    created: &[T],
    updated: &[T],
    deleted_ids: &[String],
    server_time: &str,
    mapper: impl Fn(&T) -> Value,
) -> Vec<Value> {
    let mut rows = created
        .iter()
        .chain(updated.iter())
        .map(mapper)
        .collect::<Vec<_>>();
    rows.extend(
        deleted_ids
            .iter()
            .map(|id| serde_json::json!({ "id": id, "deletedAt": server_time })),
    );
    rows
}

pub(super) fn build_merchant_changes(changes: &TablePushChanges) -> MerchantChanges {
    MerchantChanges {
        created: changes
            .created
            .iter()
            .map(merchant_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
        updated: changes
            .updated
            .iter()
            .map(merchant_row_from_value)
            .collect::<Vec<_>>(),
    }
}

pub(super) fn build_outlet_changes(changes: &TablePushChanges) -> OutletChanges {
    OutletChanges {
        created: changes
            .created
            .iter()
            .map(outlet_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
        updated: changes
            .updated
            .iter()
            .map(outlet_row_from_value)
            .collect::<Vec<_>>(),
    }
}

pub(super) fn build_register_changes(changes: &TablePushChanges) -> RegisterChanges {
    RegisterChanges {
        created: changes
            .created
            .iter()
            .map(register_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
        updated: changes
            .updated
            .iter()
            .map(register_row_from_value)
            .collect::<Vec<_>>(),
    }
}

pub(super) fn build_category_changes(changes: &TablePushChanges) -> CategoryChanges {
    CategoryChanges {
        created: changes
            .created
            .iter()
            .map(category_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
        updated: changes
            .updated
            .iter()
            .map(category_row_from_value)
            .collect::<Vec<_>>(),
    }
}

pub(super) fn build_asset_changes(changes: &TablePushChanges) -> AssetChanges {
    AssetChanges {
        created: changes
            .created
            .iter()
            .map(asset_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
        updated: changes
            .updated
            .iter()
            .map(asset_row_from_value)
            .collect::<Vec<_>>(),
    }
}

pub(super) fn build_product_changes(changes: &TablePushChanges) -> ProductChanges {
    ProductChanges {
        created: changes
            .created
            .iter()
            .map(product_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
        updated: changes
            .updated
            .iter()
            .map(product_row_from_value)
            .collect::<Vec<_>>(),
    }
}

pub(super) fn build_order_changes(changes: &TablePushChanges) -> OrderChanges {
    OrderChanges {
        created: changes
            .created
            .iter()
            .map(order_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
        updated: changes
            .updated
            .iter()
            .map(order_row_from_value)
            .collect::<Vec<_>>(),
    }
}

pub(super) fn build_order_item_changes(changes: &TablePushChanges) -> OrderItemChanges {
    OrderItemChanges {
        created: changes
            .created
            .iter()
            .map(order_item_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
        updated: changes
            .updated
            .iter()
            .map(order_item_row_from_value)
            .collect::<Vec<_>>(),
    }
}

pub(super) fn build_outlet_product_changes(changes: &TablePushChanges) -> OutletProductChanges {
    OutletProductChanges {
        created: changes
            .created
            .iter()
            .map(outlet_product_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
        updated: changes
            .updated
            .iter()
            .map(outlet_product_row_from_value)
            .collect::<Vec<_>>(),
    }
}

pub(super) fn build_staff_changes(changes: &TablePushChanges) -> StaffChanges {
    StaffChanges {
        created: changes
            .created
            .iter()
            .map(staff_row_from_value)
            .collect::<Vec<_>>(),
        deleted_ids: changes.deleted_ids.clone(),
        updated: changes
            .updated
            .iter()
            .map(staff_row_from_value)
            .collect::<Vec<_>>(),
    }
}

pub(super) fn build_sync_push_batch_request(
    outlet_id: &str,
    idempotency_key: &str,
    merchants: Option<MerchantChanges>,
    outlets: Option<OutletChanges>,
    registers: Option<RegisterChanges>,
    categories: Option<CategoryChanges>,
    assets: Option<AssetChanges>,
    products: Option<ProductChanges>,
    orders: Option<OrderChanges>,
    order_items: Option<OrderItemChanges>,
    outlet_products: Option<OutletProductChanges>,
    staff: Option<StaffChanges>,
) -> SyncPushBatchRequest {
    SyncPushBatchRequest {
        outlet_id: outlet_id.to_string(),
        idempotency_key: idempotency_key.to_string(),
        merchants,
        outlets,
        registers,
        categories,
        assets,
        products,
        orders,
        order_items,
        outlet_products,
        staff,
    }
}

pub(super) fn decode_pull_batch_response_tables(
    response: &SyncPullBatchResponse,
) -> Result<std::collections::BTreeMap<String, Value>, String> {
    let mut map = std::collections::BTreeMap::new();

    if let Some(changes) = &response.merchants {
        map.insert(
            "merchants".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.created,
                &changes.updated,
                &changes.deleted_ids,
                &response.server_time,
                merchant_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.outlets {
        map.insert(
            "outlets".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.created,
                &changes.updated,
                &changes.deleted_ids,
                &response.server_time,
                outlet_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.registers {
        map.insert(
            "registers".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.created,
                &changes.updated,
                &changes.deleted_ids,
                &response.server_time,
                register_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.categories {
        map.insert(
            "categories".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.created,
                &changes.updated,
                &changes.deleted_ids,
                &response.server_time,
                category_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.assets {
        map.insert(
            "assets".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.created,
                &changes.updated,
                &changes.deleted_ids,
                &response.server_time,
                asset_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.products {
        map.insert(
            "products".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.created,
                &changes.updated,
                &changes.deleted_ids,
                &response.server_time,
                product_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.orders {
        map.insert(
            "orders".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.created,
                &changes.updated,
                &changes.deleted_ids,
                &response.server_time,
                order_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.order_items {
        map.insert(
            "order_items".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.created,
                &changes.updated,
                &changes.deleted_ids,
                &response.server_time,
                order_item_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.outlet_products {
        map.insert(
            "outlet_products".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.created,
                &changes.updated,
                &changes.deleted_ids,
                &response.server_time,
                outlet_product_row_to_value,
            )),
        );
    }

    if let Some(changes) = &response.staff {
        map.insert(
            "staff".to_string(),
            Value::Array(typed_rows_to_json_values(
                &changes.created,
                &changes.updated,
                &changes.deleted_ids,
                &response.server_time,
                staff_row_to_value,
            )),
        );
    }

    Ok(map)
}

pub(super) fn pull_batch_response_has_more(response: &SyncPullBatchResponse) -> bool {
    response.has_more
}

pub(super) fn pull_batch_response_next_cursor(response: &SyncPullBatchResponse) -> String {
    response.next_page_cursor.clone()
}

pub(super) fn pull_batch_response_latest_event_id(response: &SyncPullBatchResponse) -> i64 {
    response.latest_event_id
}

pub(super) fn pull_batch_response_server_time(response: &SyncPullBatchResponse) -> String {
    response.server_time.clone()
}

pub(super) fn pull_batch_response_needs_full_resync(response: &SyncPullBatchResponse) -> bool {
    response.needs_full_resync
}
